### ISSUE TITLE
Request? Decoy bodies, when identified, start beeping and explode.

### ISSUE THREAD

**Issue by Aura89** [Bara/TroubleinTerroristTown#101]
Bara told me if i have any suggestions to post them here, since i'm not a programmer, so hopefully that is fine?

My request/suggestion if anyone sees it as a good idea is to add an option within the config to have traitor decoy bodies start beeping, then explode.

Some useful configs would be possibly a damage config, blast radius (both similar to C4/jihad configs), how long the body beeps(aka how long from when they ID it to exploding), etc. Would be good if the body disappeared after exploding as well.

There's not many "traps" the traitors can put out there, so i think this would be used quite often if implemented.

**Comment by popey456963** [comment]
Really like this idea, perhaps to replace the fake body (which, on my server at least, doesn't get much use).  Maybe make people think twice about identifying bodies? :)

**Comment by Bara20** [comment]
#191

**Comment by Bara** [comment]
Here is a preview with a fakebody (nothing special): https://youtu.be/sy4JlA_tahs
