### ISSUE TITLE
Disable TTT programmatically for a round

### ISSUE THREAD

**Issue by popey456963** [Bara/TroubleinTerroristTown#128]
Is there a way to do this so that we can run special days?

**Comment by Bara20** [comment]
I think you mean all functions by ttt or?

**Comment by popey456963** [comment]
Yeah, at the moment we're using a rather long script to disable every TTT module and then enable it on round end, but it can have some nasty side effects.

**Comment by Bara20** [comment]
Not with this version, maybe with a full rewrite or an overhaul.... or anyone make it as pull request.

**Comment by Bara** [comment]
Due the requests in the last days, I'll reopen this issue.
