### ISSUE TITLE
Add an option to make the Detective Wallhack white

### ISSUE THREAD

**Issue by Nachtfrische** [Bara/TroubleinTerroristTown#160]
This was suggested so the detective could still use the wallhack but couldn't see the roles, since all players would have a white glow.

**Comment by Bobakanoosh** [comment]
@Bara20 I was trying to do this and the plugin wont compile even with no changes,

[img]https://i.imgur.com/H0aUQW1.png[/img]

**Comment by Bara20** [comment]
Take a look at this: https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax

**Comment by Bobakanoosh** [comment]
It's something to do with CustomPlayerSkins include, but I have no idea what the problem is. There's no updates the the github for it either.

**Comment by Bara20** [comment]
I don't know. You've not posted the full compile log.. just a little thing of this.

**Comment by Bobakanoosh** [comment]
Odd, i compiled a version I have in my main scripting folder instead of from github and it works.

**Comment by Bobakanoosh** [comment]
There's not much else to post, I'm guessing I just dont have the includes set up properly. Regardless I'll push the changes since it's only 4 lines.

**Comment by Bobakanoosh** [comment]
#194

**Comment by Bara** [comment]
I've found now a way.. I'll try to add it today.

**Comment by Bara** [comment]
https://youtu.be/hOT1zKq_1jM
