### ISSUE TITLE
Spec Menu Showing Wrong Player Name

### ISSUE THREAD

**Issue by omar-damaj** [Bara/TroubleinTerroristTown#178]
When looking at the spec menu player name, it shows up wrong.

**Comment by good-live** [comment]
Under what circumstances does this happen?
A few more details would be nice!

**Comment by omar-damaj** [comment]
when switching back and forth, the names mess up and start showing another person's name. It kinda happens randomly when switching between players in spec.

**Comment by omar-damaj** [comment]
I figured out whats going on. So its showing the names of dead players in the spec menu which is throwing off the names. Is there a way we can have it check the players if they are alive for the names in the menu?

**Comment by omar-damaj** [comment]
Update: So far I have seen it only do it to option number 2 (next player) in spec menu.

**Comment by Bara20** [comment]
@good-live ?

**Comment by good-live** [comment]
I don't really know another way to get the observing target:
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_spec_menu.sp#L326

**Comment by Bara** [comment]
https://github.com/tilastokeskus/sm-PropHunt/blob/d977aab6266f1a23c3b8ab32392171379244dd90/addons/sourcemod/scripting/prophunt/spectate.sp @good-live

**Comment by good-live** [comment]
He's using the same method to determine the current spectating target.
