### ISSUE TITLE
defibrillators

### ISSUE THREAD

**Issue by KrisTheCanadian** [Bara/TroubleinTerroristTown#180]
I'd like to make a request for defibrillators as t weapon to revive fellow traitors. :)

**Comment by Bara20** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=162581348

**Comment by Bara** [comment]
I'll asked [Kaesar](http://steamcommunity.com/profiles/76561197995988196/) to make a weapon model for this. It's done, but currently not interested to add this.

**Comment by Bara** [comment]
https://youtu.be/Xx81yuaucBc instant respawn will be replaced with a menu for the dead player.
