### ISSUE TITLE
Role assignment

### ISSUE THREAD

**Issue by throwawayttt49** [Bara/TroubleinTerroristTown#187]
I'd change role assignment in a few ways first of assign traitors then detectives, not enough people choosing to be a detective choose a random one 
secondly id implement this fixfrom a private ttt plugin

In this example the coinflip odds are dynamic and calculated like so:
1 - (1/(1 + <number of rounds they've been selected for T in a row>))x100
^rounded up.

 

Kittens Nighthawk Ab Q4 and Kakashi are on the server. 

 

Round 1 Kittens and Kakashi are traitors.

There were no prior traitors so there is no coinflip.

Round 2: For Kittens and Kakashi to be eligible to be picked as traitors this round...

Both of them need to roll higher than 1 - 1/(1+1)x100 = 50
Kittens gets a number random'd for him, it turns up 69
Kitten's ID gets added to the T selection array for this round.
Kakashi gets a number random'd for him, it turns up 41
Kakashi's ID does not get added to the T selection array for this round and his chance of been put into the T selection array goes back to 100% for the next round. (he just gets added in, no RNG coin flip roll for him) and we now have 1 guaranteed new traitor this round.

This round the people the plugin can pick to be a Traitor are Kittens, Nighthawk, Ab and Q4.
Yet the playerbase will still think kakashi is elligible to be a T so he isnt "proven"

The Selected Round 2 traitors are Kittens and Q4.

 

Round 3: For Kittens and Q4 to be eligible to be picked as traitors this round...
Kittens has to roll higher than 1 - 1/(1+2)x100 = 67
Kittens gets a number random'd for him, it turns up 80
Kitten's ID gets added to the T selection array for this round.
Q4 has to roll higher than 1 - 1/(1+1)x100 = 50
Q4 gets a number random'd for him, it turns up 99
Q4's ID gets added to the T selection array for this round.

This round the people the plugin can pick to be a Traitor are Kittens, Nighthawk, Ab, Q4 and Kakashi
Both Ts passed their RNG roll so both are elligible to be included in the T selection array for this round.

The Selected Round 3 traitors are Kittens and Q4.

Round 4: For Kittens and Q4 to be eligible to be picked as traitors this round...
Kittens has to roll higher than 1 - 1/(1+3)x100 = 75
Kittens gets a number random'd for him, it turns up 74
Kitten's ID does not get added to the T selection array for this round and his chance of been put into the T selection array goes back to 100% for the next round. We now have 1 guaranteed new traitor this round.
Q4 has to roll higher than 1 - 1/(1+2)x100 = 67
Q4 gets a number random'd for him, it turns up 68
Q4's ID gets added to the T selection array for this round.

This round the people the plugin can pick to be a Traitor are Nighthawk, Ab, Q4 and Kakashi
Kittens failed his coinflip so he cannot be picked as a T by the selection method, Q4 passed it so he can be picked as a T by the selection script.
The Selected Round 4 traitors are Kakashi and Ab. C-C-Combo Breaker

 

Even though Q4 was eligible the main script simply didn't select him and we now have 2 completely new traitors, even though kakashi was a T previously he wasnt a T last round and thus isnt excluded from future rolls/doesnt have to pass the cointoss just yet and has the same chance as everyone else from been picked by the selection method.

 

 

*in this example Kittens is getting extremely lucky, the selection method is picking him repeatedly and he didn't get disqualified by 1/2 and 1/3 odds.

The chance of this occurring in a populated server is very very low.

 

 

*possibly make Ts have a cooloff, eg instead of kittens going straight back into the selection process in round 5 after been skipped round 4 he has to keep rolling against 1-(1+(rounds been t in a row - 1) = X odds that reduces by 1 each time he fails.

 

eg he has to beat a (1-(1/(4-1)) = 67 roll to go into the selection on round 5, failing that he has to beat a (1-(1/(3-1)) = 50 roll to go into T selection on round 6,  and failing that he goes back into the T selection method with the same odds as everyone else. ((1-(1/(2-1)) = 100% on round 7.

 

This would still allow someone who gets traitor 3 rounds in a row to come back on the round after they're skipped but only if they were absurdly lucky, it makes it possible which means "kittens" is never a guaranteed proven, its just "very unlikely" hes a T.

 

 

***My formula in this example can modified via cvar like so.

1 - (1/(1 + <number of rounds they've been selected for T in a row>))x100

1 - (1/(cvar goes here + <number of rounds they've been selected for T in a row>))x100

 

Example, if the cvar is 0 then they wont perform a meaningful coinflip unless selected as a traitor a second time in a row, as the second round will be 1 - (1/(0+1))x100 = 100%

(next round aka "traitor 3 times in a row" will have to pass a 50% coinflip)

 

Conversely if the cvar is set to 2 then the difficulty of the roll will start higher.

eg

The roll they need to pass to be a traitor a second time in a row is now 1 - (1/(2+1))x100 = 67 instead of "50" this allows you to further reduce the odds of people been selected as T multiple times in a row.

**Comment by throwawayttt49** [comment]
also thiis
The Detective/Traitor selection method also has been slightly altered, here's how things will go now:

- Traitors Selected
- Detectives Selected (must have accepted menu), player must not already been chosen as Traitor
- Innocents assigned to everyone else

- Check detective count
- if there isn't enough detectives then give a random person detective (whether menu is accepted or not)

**Comment by good-live** [comment]
Maybe i don't get your point, but currently it's nearly like this. The only difference is that the chance to become a Traitor again isn't scaling with the rounds. I can't really see a big advantage in that.

For the secound part: It should be already linke this. If you've experienced something different let me know your version.

**Comment by popey456963** [comment]
@throwawayttt49 Am I right in understanding you basically want to remove a bit of randomness from role selection?  I'd be for this, a lot of people complain about not getting traitor in `X` rounds.  In my opinion, it's a better player experience for someone to have a higher certainty of getting traitor at least once in a time frame, getting innocent 10+ times in a row can be boring.

**Comment by good-live** [comment]
I won't implement that, because it would make it to predictable. Actually there is already a higher chance if you haven't been traitor the round before.

The current code is (with some slightly modifications and a port to sourcepawn obv) taken from the gmod Version of TTT. The true mess seems to be the random numbers in sourcemod.

**Comment by Bara** [comment]
I've made some changes that should reduce the chance to get traitor role.

**Comment by Bara** [comment]
Chance to get the traitor role in the next round (as innocent and/or detective) should be increased with [this commit](https://github.com/Bara/TroubleinTerroristTown/commit/bd627b027fc510618417b4e736cbc506ff59a73a).

**Comment by Bara** [comment]
Is it now better since the latest changes?

**Comment by popey456963** [comment]
Sure, that works :+1:
