### ISSUE TITLE
Dead Players Default Muted

### ISSUE THREAD

**Issue by omar-damaj** [Bara/TroubleinTerroristTown#202]
I could not find a setting for this but the option in spec menu for "Mute Dead Players" seems to be having issues. When a player dies, they have to mute dead players and unmute dead players to be able to hear anyone talking when dead. Any thoughts on how this can be fixed?

**Comment by Bara20** [comment]
Code looks fine, it just mute the dead player for players their have "Mute Dead" enabled.

**Comment by Bara20** [comment]
or @good-live find the issue.

**Comment by good-live** [comment]
What's your default listening flag (Set through cvars)?

**Comment by omar-damaj** [comment]
sv_alltalk is set to 1 and sv_deadtalk is set to 0 as recommended by the cvars text file from my end.

**Comment by good-live** [comment]
I couldn't reproduce the bug. Do you have any other plugin that's setting voice flags?

**Comment by Bara** [comment]
@omar-damaj

**Comment by omar-damaj** [comment]
I still have not found anything to resolve this. 
Here are all voice, chat, talk related cvars I found using the find command. 
https://hastebin.com/didukicico.vbs

**Comment by good-live** [comment]
Dies it work fine with spec menu disabled?

**Comment by Bara** [comment]
And your plugin list? Maybe an conflict @omar-damaj
