### ISSUE TITLE
New logos, images...

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#204]
It would be very nice, if anyone could create new stuff for the following things:

- **Role-Overlays** - _Traitor, Innocent and Detective_ (currently at the top right screen with the current player role as icon)
- **World-Icons** - _Traitor and Detective_ (currently above players head for traitors and detectives)
- **Overlays** - _Traitor, Innocent and Detective_ (on round end in center of everyone's screen)
- **Github Group Icon** - _https://github.com/TroubleinTerroristTown_ [(Currently custom generated)](https://avatars2.githubusercontent.com/u/32057638?s=200&v=4)

**Comment by popey456963** [comment]
In terms of overlays, it might also be nice if they were smaller.  4MB seems unreasonably high for an image that compromises of like three constant-hue pictures.

**Comment by Bara** [comment]
Nobody?
