### ISSUE TITLE
After Death Deathmatch Mode

### ISSUE THREAD

**Issue by omar-damaj** [Bara/TroubleinTerroristTown#209]
Hey all! 
Was wondering if something like this would be possibly added to TTT.
https://github.com/eminem0091/CSGO-Redie-V2.3-with-translations
This plugin allows you to have the ability to walk around freely and invisibly as a "ghost" and even has a dm mode built into it. 
I tested it with the TTT plugin and the problem I ran into is that when you use the command to turn into a ghost, your body disappears and you are not able to be IDed anymore. I was thinking for a solution for it and one might be that you can drop a "fake body" where the person dies if they choose to do the deathmatch mode. 
It would keep people entertained. This was implemented in GMod TTT as well before where you would be able to do !dm after you die to join the dead deathmatch. 

Thank you!

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/d88b3f65afca093c09cf546cd8ed3abc7129645a could be useful to prevent rdm
