### ISSUE TITLE
Stats/Logging plugin

### ISSUE THREAD

**Issue by kikoplg** [Bara/TroubleinTerroristTown#22]
Round, Round Stats, Damage Log, Player Stats, Players alives per round, Damage logs, Kills, ...

**Comment by iNilo** [comment]
Possibly https://github.com/Bara20/TroubleinTerroristTown/issues/49 
Then implement a custom OnLogAction forward to the database https://sm.alliedmods.net/new-api/logging/OnLogAction

**Comment by iNilo** [comment]
Use OnLogAction to write your own log handling, LogAction has been implemented in https://github.com/Bara20/TroubleinTerroristTown/commit/2bebf231a10cb15234fea8ca920aae00241711ff

**Comment by Drewerth** [comment]
For the stats part I assume you mean something more player-generalized.

sm_stats Name

TTT: Player Statistics for Name
--------------------------------------------------
Kills: xx
Deaths: xx
Traiter Wins: xx
Detective Wins: xx
Innocent Wins: xx

So on and so forth.

??

**Comment by NicronS** [comment]
@Drewerth I think that would be the best option.
