### ISSUE TITLE
Godmode after round end [Cameras and Drones]

### ISSUE THREAD

**Issue by Keplyx** [Bara/TroubleinTerroristTown#222]
I got reports from some players using Cameras and Drones with TTT, saying they get into godmode when the round ends while they where using a camera or a drone.

I couldn't reproduce the bug with cameras and drones alone, so I think there's a little conflict between our plugins.

Could you please tell me how I can debug it with your plugin? I don't really know where to start looking, or what could cause this issue.

I'll try to look more into this, but I don't have much free time, so it may take a while for me to sort this out.

**Comment by Bara20** [comment]
We just use your natives https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_dronescameras.sp#L88 and give tagrenade

**Comment by Keplyx** [comment]
Could you tell me how I can test your plugin alone? I can't start a match if there's less than 3 players and adding bots breaks everything.

I want to be able to start a round, get into a camera or drone, then end the round to check if I'm actually fixing anything.

**Comment by Bara** [comment]
Set
ttt_show_debug_messages "1"
ttt_debug_mode "1"
ttt_required_player "1"

If you've no countdown do: mp_restartgame 1 ( It's a known issue #229 )

**Comment by Keplyx** [comment]
Thank you it worked, but somehow I'm not taking damage at all after round start (from ground, my own grenades or trigger_hurt) with only your plugin installed. Is it normal, since you use the karma stuff to calculate the damage given, or am I doing something wrong?
I could not try with an other player since I'm only testing on a local server.

Sorry for the dumb questions, but I never played TTT in csgo so I don't really know how it works.

**Comment by Bara** [comment]
[Karma damage is by default disabled.](https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/core/config.sp#L9)
But [damage](https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/core/config.sp#L79-L80) is before and after a round [disabled](https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt.sp#L1434).

**Comment by Keplyx** [comment]
Issue seems to be fixed with latest commit https://github.com/Keplyx/cameras-and-drones/commit/b4b2937605572d909b56c2ef0dde57ddfa6c5ab6.

**Comment by Bara** [comment]
👌
