### ISSUE TITLE
Wallhacks

### ISSUE THREAD

**Issue by KJKRR** [Bara/TroubleinTerroristTown#225]
Currently the wallhacks in the traitor shop does not work at all when a traitor buys it.

**Comment by Bara20** [comment]
I'm sure it's fixed with https://github.com/Bara20/TroubleinTerroristTown/commit/3239f4694ac0d598b2868fb89319592845faafcc (tested on my test server)

**Comment by Bobakanoosh** [comment]
Testing now.

**Comment by Bara** [comment]
@Bobakanoosh Any updates?

**Comment by Bobakanoosh** [comment]
https://i.imgur.com/U9QSO7i.jpg

Seems like it doesn't work. However, if you'll notice, my T buddies were outlined in red. I haven't seen this feature before, so maybe that's causing the bug?

**Comment by Bara** [comment]
https://youtu.be/Pr8oUJzJock

**Comment by Bara** [comment]
@KJKRR @Bobakanoosh Try latest build (1348 or higher)

**Comment by Nachtfrische** [comment]
It works for me. There are some issues with the wallhack when it sometimes randomly disappears and reappears but I think it's because of the Valve anti-wallhack update. Can be closed.
