### ISSUE TITLE
Maps randomly turning into deathmatch

### ISSUE THREAD

**Issue by Bobakanoosh** [Bara/TroubleinTerroristTown#229]
For an entire map, each round turns into deathmatch mode. If the map is changed / force changed, its fixed, until it randomly happens again.

**Comment by omar-damaj** [comment]
Can confirm that happened to me as well. No errors in TTT logs

**Comment by Bobakanoosh** [comment]
Not sure if this is the issue, but I played a T round and I bought speed, ak, usp. When I killed the last player, he became outlined in green (like walls) before dieing. Me killing him appeared in the kill feed, and his body was not identifiable. The next round was a deathmatch round.

**Comment by Bara** [comment]
I've this issue without bots and without players (so no player in opponent team). Can anyone confirm this if that's the issue? @omar-damaj @Bobakanoosh 
I'll add a second check for non active rounds.

**Comment by Bara** [comment]
I hope it's partially fixed in my last commit.

**Comment by Bobakanoosh** [comment]
Not sure by what you mean with your first comment. I'm putting the newest version on my serrver, we'll see how it goes

**Comment by Bara** [comment]
Any news ?

**Comment by Bobakanoosh** [comment]
Still waiting on a response from my Head Admin, sorry :P

**Comment by Bobakanoosh** [comment]
Asked somebody, reports are last saturday that they saw it go deathmatch, so maybe?

**Comment by Bobakanoosh** [comment]
Sorry for so many comments, someone said it just happened.

**Comment by Bara** [comment]
Which build id?

**Comment by Bobakanoosh** [comment]
Is there a way to find this without remembering which one I downloaded?

**Comment by Bara** [comment]
Weird, I haven't this issue anymore on my test server...

**Comment by Bara** [comment]
I've added a message on player_spawn with current ttt version and a command (tttversion) that will show your version.

**Comment by Bara** [comment]
Any news here (if you've build 1346 or above) @Bobakanoosh ?
