### ISSUE TITLE
Can't change price of Martydom?

### ISSUE THREAD

**Issue by popey456963** [Bara/TroubleinTerroristTown#230]
I've changed the file in the configuration:

![](https://puu.sh/yp1Mu/cc39d85133.png)

Here you can see me as a traitor.  I checked the `cvar` and it appears to be set to the correct value:

![](https://puu.sh/yp1KG/11d509fb27.png)

Old configuration location doesn't even have a `martydom.cfg` file (since it didn't exist before you migrated to the new configuration system).

![](https://puu.sh/yp1MN/a84704f1b1.png)

Restarted a few times, played with the configuration file, as far as I can tell nothing works.  Am I doing something really wrong?

**Comment by popey456963** [comment]
Also, same thing happening for:

- Kevlar
- Heavy
- Helm
- Kevlar + Helm
- 1-Hit Knife
- M4A1-S
- AWP
- USP-S
- AK47
- Deagle
- Revolver
- Scout

But not for some new items like `Silent Awp` or `Knockout`.  Example broken configs:
- https://hastebin.com/sovuqexuxi.hs
- https://hastebin.com/asupixeqij.hs

Example working config:
- https://hastebin.com/abaranusix.hs

**Comment by Gupy92** [comment]
I think your right popey... i got the same Problem. I wanna change the prices, too. But these weapons and Items dont work.

**Comment by Bara** [comment]
So btw. you can't change the price during the round.

**Comment by Gupy92** [comment]
Bara, I got a question. You fixed the problem #230, but how can i add the fix in my plugin? I can copy your code in the .sp files but that dosent change anything, am i right? I have to compile the files to smx, right ?

**Comment by Bara** [comment]
Right, you must replace the smx files. We've an automated system and you can find the files on [csgottt.com](https://csgottt.com/).

**Comment by popey456963** [comment]
@Bara, I don't believe your fix is functional 😕.

I'm currently on version 1332 and the bug appears to persist.

**Comment by popey456963** [comment]
As far as I can tell it works for everything but `ttt_buyRoles`, even though that still contains "OnConfigsExecuted".

**Comment by popey456963** [comment]
@Bara See above.

**Comment by Bara** [comment]
I'll take a look later.

**Comment by Bara** [comment]
I can't reproduce this issue:
![buyroles](https://user-images.githubusercontent.com/17928280/33176259-c0ad0de4-d05e-11e7-8dbe-0c5b78eaa391.png)
