### ISSUE TITLE
Issue with Karma Hint menu showing /n

### ISSUE THREAD

**Issue by omar-damaj** [Bara/TroubleinTerroristTown#231]
Hints are showing /n in them for some reason now. 
It does it for any type of player. I have had the plugin re-do the config file to add the //n instead of /n but not fixed for me for some reason.

http://steamcommunity.com/id/theikillyou/screenshot/857236050645325536

**Comment by Bara** [comment]
It must be "\n" in your config. \\n is just for config generation.

**Comment by Bara** [comment]
Replace "\n" with "<br>", that's should fix the issue.
