### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by SZOKOZ** [Bara/TroubleinTerroristTown#232]
I don't know if this has brought up in the past (or how many times lul). A leaderboard to show who the best traitors, innocents, detectives would be nice to have. Ranking systems like gameme can't really represent the best players in TTT. I'd like to add this in the future myself but if anyone wants a crack at this, go ahead.

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/issues/22
