### ISSUE TITLE
Add more shop natives

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#233]
Like `TTT_UpdateItemPrice(shortName, newPrice);` or a more generel native to update more properties (role, priority...) + Forward
Remove shop items during rounds, ... + Forward

**Comment by popey456963** [comment]
Maybe a forward like:

    TTT_GetItem(shortname, &int client, &int role, &int price, ....);

Then we can return `Plugin_Changed` and change the pointers to our liking?  This is called on every single item when `sm_menu` or something is run.
