### ISSUE TITLE
Decoy Body not working on real bodies

### ISSUE THREAD

**Issue by Nachtfrische** [Bara/TroubleinTerroristTown#238]
The decoy body item is working if you buy a fake body but it is currently not working on a real body. Potentially I'm just to dumb to figure out how it works. In my opinion, you should buy the decoy body item in the shop, kill someone and then when that body is checked by someone, it explodes. Currently, it simply does nothing.

**Comment by Bara** [comment]
Is "decoy_body_allow_on_real_body" 1 ?
