### ISSUE TITLE
You can scan knocked out ragdoll? Crashes server.

### ISSUE THREAD

**Issue by SZOKOZ** [Bara/TroubleinTerroristTown#239]
So when a traitor knocks a player out and attempts to id the body(press e on the body), the server crashes.
I do not have any logs for this since there is a bug affecting the logging of my tmux console. Also the game can't log the crash if it well... crashed. I'll try and provide one soon but if my memory got anything accurate from the console while I was watching it, it had something to do with a missing attachment called "forward" along with some vphysics error. Again, I'll try and get the logs soon. If this has already been fixed in the future dev builds then my bad.

- Metamod Source 1.10.7 Build 961
- Sourcemod 1.8.0 Build 6036
- The defaults that come with the installation of the SM Build.
- ttt-dev-1.9-2.3.1369-4020b4f
- SM and TTT (That's IT)
- TTT related error logs - You can find the logs under: addons/sourcemod/logs/error_*.log

**Comment by good-live** [comment]
Do you use https://forums.alliedmods.net/showthread.php?t=277703&?

**Comment by SZOKOZ** [comment]
No. I'm guessing I should to aid bug reports?

**Comment by good-live** [comment]
Yes

**Comment by SZOKOZ** [comment]
https://crash.limetech.org/h2eod6rose6l
"This crash was likely caused by incorrect gamedata being used with an SDKCall."

**Comment by SZOKOZ** [comment]
So tried reading the error off console before the restart logs over wrote them in terminal. It's regarding a missing attachment("forward") on a prop_dynamic called fpd_ragdollCam(214).

**Comment by SZOKOZ** [comment]
So after reproducing it some more, I noticed the real error was a bad vphysics swap for prop ragdoll. It was the grabbermod on the knocked out ragdoll causing the problem.

**Comment by Bara** [comment]
@SZOKOZ Just the ragdoll on knockout or general?

**Comment by SZOKOZ** [comment]
Just the ragdoll from knockout.

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/fdf7e012433d86c64851dfb54a3e71db2a0b452a + https://github.com/Bara/TroubleinTerroristTown/commit/f1a413b769dc5f1e6d8d7573e81f9ff4ba07b6c0 should fix  this.

**Comment by SZOKOZ** [comment]
Yeah I can't grab it anymore. This sorted it!

**Comment by Bara** [comment]
I've a issue with the blacklist... and I'll block now fpd_ragdoll by plugin direct (to prevent same issue/crash on a live server) https://github.com/Bara/TroubleinTerroristTown/commit/089d43579b6aa679659749e4d197195eba11e6bf

**Comment by SZOKOZ** [comment]
Ah ur right, after trying it several times again someone was able to grab the ragdoll.

**Comment by Bara** [comment]
Try with latest build, works fine on my Server

**Comment by SZOKOZ** [comment]
Yeah, I tried it multiple times more than the other reproducing tests I did and it seems patched for good. Though I did notice my test partner grab a vent on mirage. It's more funny than it is a bug. xD
