### ISSUE TITLE
Flashlight not working

### ISSUE THREAD

**Issue by Nachtfrische** [Bara/TroubleinTerroristTown#240]
According to a player, the flashlight is not working anymore.
The sound is played but the light "cone" of the flashlight is not shown.

**Comment by Bara** [comment]
Uhm try https://forums.alliedmods.net/showthread.php?t=227224

**Comment by Nachtfrische** [comment]
The plugin from Mitchell worked, thanks. So I guess it's now required to use the flashlight on TTT?

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/58514e24b8bf6221796064ef1fdf8408629e6359
