### ISSUE TITLE
BUG Plugin ttt_blackout.smx

### ISSUE THREAD

**Issue by paulocrash** [Bara/TroubleinTerroristTown#241]
**Version of MetaMod  (meta version):**
> Metamod:Source version 1.10.7-dev
> Built from: https://github.com/alliedmodders/metamod-source/commit/f255fa5
> Build ID: 961:f255fa5
> Loaded As: Valve Server Plugin
> Compiled on: Nov  5 2017
> Plugin interface version: 15:14
> SourceHook version: 5:5
> http://www.metamodsource.net/

**Version of SourceMod (sm version):**
>  SourceMod Version Information:
>     SourceMod Version: 1.8.0.6036
>     SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6036)
>     SourcePawn API: v1 = 4, v2 = 11
>     Compiled on: Nov  3 2017 19:06:38
>     Built from: https://github.com/alliedmodders/sourcemod/commit/fef5583
>     Build ID: 6036:fef5583
>     http://www.sourcemod.net/

 **List of your extensions (sm exts list):**

> [SM] Displaying 17 extensions:
> [01] Automatic Updater (1.8.0.6036): Updates SourceMod gamedata files
> [02] Webternet (1.8.0.6036): Extension for interacting with URLs
> [03] CS Tools (1.8.0.6036): CS extended functionality
> [04] BinTools (1.8.0.6036): Low-level C/C++ Calling API
> [05] SDK Tools (1.8.0.6036): Source SDK Tools
> [06] Client Preferences (1.8.0.6036): Saves client preference settings
> [07] SQLite (1.8.0.6036): SQLite Driver
> [08] Top Menus (1.8.0.6036): Creates sorted nested menus
> [09] SDK Hooks (1.8.0.6036): Source SDK Hooks
> [10] SteamWorks Extension (1.2.2): Exposes SteamWorks functions to Developers
> [11] TAU LIB (1.1): 
> [12] Regex (1.8.0.6036): Provides regex natives for plugins
> [13] DHooks (2.1.1): Dynamic Hooks
> [14] <FAILED> file "steamtools.ext.so": /home/ogp/OGP_User_Files/whmcs/979/csgo/addons/sourcemod/extensions/steamtools.ext.so: cannot open shared object file: No such file or directory
> [15] <FAILED> file "curl.ext.so": /home/ogp/OGP_User_Files/whmcs/979/csgo/addons/sourcemod/extensions/curl.ext.so: cannot open shared object file: No such file or directory
> [16] <FAILED> file "socket.ext.so": /home/ogp/OGP_User_Files/whmcs/979/csgo/addons/sourcemod/extensions/socket.ext.so: cannot open shared object file: No such file or directory
> [17] MySQL-DBI (1.8.0.6036): MySQL driver implementation for DBI

**Version of TTT (sm_tttversion):**
> TTT Version: 2.3.1382

**List of your plugins (sm plugins list):**

> [SM] Listing 60 plugins:
> 01 &quot;Sound Commands&quot; (1.8.0.6036) by AlliedModders LLC
> 02 &quot;Client Preferences&quot; (1.8.0.6036) by AlliedModders LLC
> 03 &quot;Basic Chat&quot; (1.8.0.6036) by AlliedModders LLC
> 04 &quot;Basic Comm Control&quot; (1.8.0.6036) by AlliedModders LLC
> 05 &quot;No Weapon Fix&quot; (3.2) by .#Zipcore
> 06 &quot;Anti-Flood&quot; (1.8.0.6036) by AlliedModders LLC
> 07 &quot;Basic Commands&quot; (1.8.0.6036) by AlliedModders LLC
> 08 &quot;Nextmap&quot; (1.8.0.6036) by AlliedModders LLC
> 09 &quot;Admin File Reader&quot; (1.8.0.6036) by AlliedModders LLC
> 10 &quot;csgotokens.com token changer&quot; (1.4.5) by Adi - live4net
> 11 &quot;Fun Votes&quot; (1.8.0.6036) by AlliedModders LLC
> 12 &quot;Block messages&quot; (1.0.0) by Bara
> 13 &quot;Admin Menu&quot; (1.8.0.6036) by AlliedModders LLC
> 14 &quot;Fun Commands&quot; (1.8.0.6036) by AlliedModders LLC
> 15 &quot;Basic Votes&quot; (1.8.0.6036) by AlliedModders LLC
> 16 &quot;Basic Info Triggers&quot; (1.8.0.6036) by AlliedModders LLC
> 17 &quot;Trouble in Terrorist Town - Items: Ice Knife&quot; (2.3.1382) by TTT-Contributors
> 18 &quot;Trouble in Terrorist Town - Items: Healthshot&quot; (2.3.1382) by TTT-Contributors
> 19 &quot;Trouble in Terrorist Town - Sprint&quot; (2.3.1382) by TTT-Contributors
> 20 &quot;Trouble in Terrorist Town - Radar&quot; (2.3.1382) by TTT-Contributors
> 21 &quot;Trouble in Terrorist Town - Items: Decoy Teleporter&quot; (2.3.1382) by TTT-Contributors
> 22 &quot;Trouble in Terrorist Town - Icons&quot; (2.3.1382) by TTT-Contributors
> 23 &quot;Trouble in Terrorist Town - Hide Radar&quot; (2.3.1382) by TTT-Contributors
> 24 &quot;Trouble in Terrorist Town - Decoy Body&quot; (2.3.1382) by TTT-Contributors
> 25 &quot;Trouble in Terrorist Town - Shop&quot; (2.3.1382) by TTT-Contributors
> 26 &quot;Trouble in Terrorist Town - Items: Taser&quot; (2.3.1382) by TTT-Contributors
> 27 &quot;Trouble in Terrorist Town - Items: Wallhack&quot; (2.3.1382) by TTT-Contributors
> 28 &quot;Trouble in Terrorist Town - Silent AWP&quot; (2.3.1382) by TTT-Contributors
> 29 &quot;Trouble in Terrorist Town - SQL Manager&quot; (2.3.1382) by TTT-Contributors
> 30 &quot;Trouble in Terrorist Town&quot; (2.3.1382) by TTT-Contributors
> 31 &quot;Trouble in Terrorist Town - Hud&quot; (2.3.1382) by TTT-Contributors
> 32 &quot;Trouble in Terrorist Town - Items: Martydom&quot; (2.3.1382) by TTT-Contributors
> 33 &quot;Trouble in Terrorist Town - Knockout&quot; (2.3.1382) by TTT-Contributors
> 34 &quot;Trouble in Terrorist Town - Spec Menu&quot; (2.3.1382) by TTT-Contributors
> 35 &quot;Trouble in Terrorist Town - Health/Hurt Stations&quot; (2.3.1382) by TTT-Contributors
> 36 &quot;Trouble in Terrorist Town - Items: Fake Body&quot; (2.3.1382) by TTT-Contributors
> 37 &quot;Trouble in Terrorist Town - Traitor Doors&quot; (2.3.1382) by zipcore
> 38 &quot;Trouble in Terrorist Town - Grabber Mod&quot; (2.3.1382) by TTT-Contributors
> 39 &quot;Trouble in Terrorist Town - Crash Catcher&quot; (2.3.1382) by TTT-Contributors
> 40 &quot;Trouble in Terrorist Town - Blackout&quot; (2.3.1382) by TTT-Contributors
> 41 &quot;Trouble in Terrorist Town - TA-Grenade&quot; (2.3.1382) by Bara, zipcore &amp; Neuro Toxin
> 42 &quot;Trouble in Terrorist Town - Dna Scanner&quot; (2.3.1382) by TTT-Contributors
> 43 &quot;Trouble in Terrorist Town - Round End Sounds&quot; (2.3.1382) by Bara (&amp; AbNeR_CSS)
> 44 &quot;Trouble in Terrorist Town - Overlays&quot; (2.3.1382) by TTT-Contributors
> 45 &quot;Trouble in Terrorist Town - Talk Override&quot; (2.3.1382) by TTT-Contributors
> 46 &quot;Trouble in Terrorist Town - Items: ID&quot; (2.3.1382) by TTT-Contributors
> 47 &quot;Trouble in Terrorist Town - Glow&quot; (2.3.1382) by Bara &amp; zipcore
> 48 &quot;Trouble in Terrorist Town - Shop Discounts&quot; (2.3.1382) by TTT-Contributors
> 49 &quot;Trouble in Terrorist Town - Items: Weapons&quot; (2.3.1382) by TTT-Contributors
> 50 &quot;Trouble in Terrorist Town - Teleporter&quot; (2.3.1382) by TTT-Contributors
> 51 &quot;Trouble in Terrorist Town - Buy Roles&quot; (2.3.1382) by TTT-Contributors
> 52 &quot;Trouble in Terrorist Town - C4 &amp; Jihad&quot; (2.3.1382) by TTT-Contributors
> 53 &quot;Player Commands&quot; (1.8.0.6036) by AlliedModders LLC
> 54 &quot;SM Franug Hats&quot; (3.3.2) by Franc1sco franug
> 55 &quot;Custom Player Skins (Core)&quot; (1.4) by Mitchell, Root
> 56 &quot;Rock The Vote&quot; (1.8.0.6036) by AlliedModders LLC
> 57 &quot;Admin Help&quot; (1.8.0.6036) by AlliedModders LLC
> 58 &quot;MapChooser&quot; (1.8.0.6036) by AlliedModders LLC
> 59 &quot;Updater&quot; (1.2.2) by GoD-Tony
> 60 &quot;TecnoHard&trade; Admin Manager&quot; (2.0_2017) by AbNeR @CSB

**TTT related error logs:**
[errors_20171128.log](https://github.com/Bara/TroubleinTerroristTown/files/1516497/errors_20171128.log)

The error would be this:
> L 11/28/2017 - 21:33:47: [SM] Exception reported: Entity 439 (439) is invalid
> L 11/28/2017 - 21:33:47: [SM] Blaming: ttt/ttt_blackout.smx
> L 11/28/2017 - 21:33:47: [SM] Call stack trace:
> L 11/28/2017 - 21:33:47: [SM]   [0] DispatchKeyValue
> L 11/28/2017 - 21:33:47: [SM]   [1] Line 121, addons/sourcemod/scripting/ttt/ttt_blackout.sp::SetupBlackout
> L 11/28/2017 - 21:33:47: [SM]   [2] Line 62, addons/sourcemod/scripting/ttt/ttt_blackout.sp::OnConfigsExecuted

**Comment by Bara** [comment]
Which map?

**Comment by paulocrash** [comment]
ttt_minecraft_b5_csgo

My complete list of maps would be this: http://steamcommunity.com/sharedfiles/filedetails/?id=1211909416
