### ISSUE TITLE
GOTV doesn't work with ttt

### ISSUE THREAD

**Issue by quasemago** [Bara/TroubleinTerroristTown#242]
Due to the recent cs:go update the gotv is being required (this was discussed better here: https://forums.alliedmods.net/showthread.php?t=303249).

I'm trying to enable gotv on my server, but when I activate the server it has no map in the server list and the tv does not work. This happens only when ttt is running, while removing the main plugin (ttt.smx) the gotv loads.

On my other server (Zombie Escape), gotv loads perfectly confirming the problem with the ttt plugin. 

Here's is a list what we need:
- Version of MetaMod: 1.10.7-dev (Build ID: 959:4a27e2f)
- Version of SourceMod: 1.8.0.6025 (Build ID: 6025:494f833)
- List of your extensions:

> [SM] Displaying 19 extensions:
> [01] Automatic Updater (1.8.0.6025): Updates SourceMod gamedata files
> [02] Webternet (1.8.0.6025): Extension for interacting with URLs
> [03] CS Tools (1.8.0.6025): CS extended functionality
> [04] BinTools (1.8.0.6025): Low-level C/C++ Calling API
> [05] SDK Tools (1.8.0.6025): Source SDK Tools
> [06] SteamWorks Extension (1.2.2): Exposes SteamWorks functions to Developers
> [07] Top Menus (1.8.0.6025): Creates sorted nested menus
> [08] Regex (1.8.0.6025): Provides regex natives for plugins
> [09] GeoIP (1.8.0.6025): Geographical IP information
> [10] SDK Hooks (1.8.0.6025): Source SDK Hooks
> [11] <FAILED> file "store_sm.ext.so": /home/ogp_agent/OGP_User_Files/whmcs/230/csgo/addons/sourcemod/extensions/store_sm.ext.so: cannot open shared object file: No such file or directory
> [12] Client Preferences (1.8.0.6025): Saves client preference settings
> [13] SQLite (1.8.0.6025): SQLite Driver
> [14] DHooks (2.1.1): Dynamic Hooks
> [15] MySQL-DBI (1.8.0.6025): MySQL driver implementation for DBI

- Version of TTT: https://github.com/Bara/TroubleinTerroristTown/tree/4020b4fe09f4ce36c3e8719989ac8145c8be97de
- Errors logs: none

https://forums.alliedmods.net/showpost.php?p=2563902&postcount=642
_ps: sorry for my english (google translate)._

**Comment by Bara** [comment]
> Due to the recent cs:go update [...] problem with the ttt plugin.
Valve + Community = Nope... I've no motivation to fix valve "bugs".

**Comment by quasemago** [comment]
Honestly, if gotv does not work ONLY WITH TTT it means that the problem is not just with the valve but with its plugin.

And it would be a good point a solution for this because due to the recent update is affecting all the servers.

So will you continue with the same answer?

**Comment by Bara** [comment]
> So will you continue with the same answer?

Yes, and i don't read a thread with 16 sites of mimimi.

**Comment by quasemago** [comment]
Okay, good luck with your ignorance.

**Comment by Bara** [comment]
> Okay, good luck with your ignorance.

Okay. That's just a project in my freetime without any payment. I do what i want, if you don't agree that -> Shit happens

**Comment by Bara** [comment]
![gotv](https://user-images.githubusercontent.com/17928280/33500755-368a6f1c-d6da-11e7-83a5-842f0343300d.png)
> removing the main plugin (ttt.smx) the gotv loads.

👍 without ttt.smx you can't run any ttt_*.smx plugin. You're sure the problem caused by ttt.smx?

**Comment by quasemago** [comment]
Yes, I tested it by running only ttt.smx and ttt_sql.smx.

**Comment by Bara** [comment]
![gotv2](https://user-images.githubusercontent.com/17928280/33500877-c4d58752-d6da-11e7-9a4b-2cc597aa2721.png)
Restarted server (without a player and without bots) + all plugins.

**Comment by quasemago** [comment]
Well, exclude gotv as valid client fixed the problem.
