### ISSUE TITLE
Exception reported: Client 'i' is not connected

### ISSUE THREAD

**Issue by Extremelyd1** [Bara/TroubleinTerroristTown#246]
So when I start up the server with TTT it immediately throws this exception:
L 12/02/2017 - 15:03:00: [SM] Exception reported: Client 2 is not connected
L 12/02/2017 - 15:03:00: [SM] Blaming: ttt_talk_override.smx
L 12/02/2017 - 15:03:00: [SM] Call stack trace:
L 12/02/2017 - 15:03:00: [SM]   [0] IsClientSourceTV
L 12/02/2017 - 15:03:00: [SM]   [1] Line 282, /home/travis/build/Bara/TroubleinTerroristTown/addons/sourcemod/scripting/include/ttt.inc::TTT_IsClientValid
L 12/02/2017 - 15:03:00: [SM]   [2] Line 121, addons/sourcemod/scripting/ttt/ttt_talk_override.sp::Event_PlayerSpawn

And when I join the server it throws the error as stated in the included pastebin.

Apparently the plugin wants to loop through all clients and finds a client that it cannot check with IsClientSourceTV(), because the client is not connected.

Things you might need:
- Version of MetaMod  1.10.7-dev
- Version of SourceMod 1.8.0.6036
- List of your extensions:
    [01] Automatic Updater (1.8.0.6036): Updates SourceMod gamedata files
    [02] Webternet (1.8.0.6036): Extension for interacting with URLs
    [03] <FAILED> file "cleaner.ext.2.csgo.dll": Failed to find signature. Please contact the author.
    [04] CS Tools (1.8.0.6036): CS extended functionality
    [05] BinTools (1.8.0.6036): Low-level C/C++ Calling API
    [06] SDK Tools (1.8.0.6036): Source SDK Tools
    [07] Top Menus (1.8.0.6036): Creates sorted nested menus
    [08] Client Preferences (1.8.0.6036): Saves client preference settings
    [09] SQLite (1.8.0.6036): SQLite Driver
    [10] DHooks (2.0.4): Dynamic Hooks
    [11] SDK Hooks (1.8.0.6036): Source SDK Hooks
    [12] GeoIP (1.8.0.6036): Geographical IP information
    [13] Regex (1.8.0.6036): Provides regex natives for plugins
- Version of TTT 2.3.1401
- List of your plugins:
    All default sourcemod plugins
    TTT
    TTT Crash Catcher
    TTT Glow
    TTT Grabber Mod
    TTT Hide Radar
    TTT Icons
    TTT Overlays
    TTT Hud
    TTT Spec Menu
    TTT SQL Manager
    TTT Talk Override
    TTT Traitor Doors
    TTT Traitor Traps
- TTT related error logs: https://pastebin.com/z9YWxFjg

**Comment by Nachtfrische** [comment]
Can confirm, it throws the error with every single TTT plugin, so my log file is 600MB big 😮 
```
L 12/01/2017 - 23:39:24: [SM] Exception reported: Client 1 is not connected
L 12/01/2017 - 23:39:24: [SM] Blaming: ttt/ttt_playerhud.smx
L 12/01/2017 - 23:39:24: [SM] Call stack trace:
L 12/01/2017 - 23:39:24: [SM]   [0] IsClientSourceTV
L 12/01/2017 - 23:39:24: [SM]   [1] Line 282, /home/travis/build/Bara/TroubleinTerroristTown/addons/sourcemod/scripting/include/ttt.inc::TTT_IsClientValid
L 12/01/2017 - 23:39:24: [SM]   [2] Line 66, addons/sourcemod/scripting/ttt/ttt_playerhud.sp::Timer_UpdateText
L 12/01/2017 - 23:39:24: [SM] Exception reported: Client 1 is not connected
L 12/01/2017 - 23:39:24: [SM] Blaming: ttt/ttt.smx
L 12/01/2017 - 23:39:24: [SM] Call stack trace:
L 12/01/2017 - 23:39:24: [SM]   [0] IsClientSourceTV
L 12/01/2017 - 23:39:24: [SM]   [1] Line 282, /home/travis/build/Bara/TroubleinTerroristTown/addons/sourcemod/scripting/include/ttt.inc::TTT_IsClientValid
L 12/01/2017 - 23:39:24: [SM]   [2] Line 2334, addons/sourcemod/scripting/ttt/ttt.sp::Timer_1
```
