### ISSUE TITLE
Tripwire

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#250]
13:34 - SkippY: http://surfburken.se/forums/topic/ttt-tripwire/

**Comment by Bara** [comment]
Nothing special, but here a little preview: https://youtu.be/7KuUi_xC1Uc

**Comment by SZOKOZ** [comment]
I always thought the official mod had a lasermine lmao. I was going to say the two are similar until I took a look and realised there was none. 
Lasermines explode when someone touches the laser btw.
