### ISSUE TITLE
Round restarts random (solved)

### ISSUE THREAD

**Issue by ctrlvv** [Bara/TroubleinTerroristTown#252]
Round is restarting randomly after a while? 
Here is a clip: https://youtu.be/d_J-xkpB0uM

Here's is a list what we need:
- Version of MetaMod  (version 1.10.7-dev)
- Version of SourceMod (SourceMod 1.8.0.6027)
- List of your extensions
 ( "Automatic Updater" (1.8.0.6027) by AlliedModders LLC: Updates SourceMod gamedata files
 "Webternet" (1.8.0.6027) by AlliedModders LLC: Extension for interacting with URLs
 "CS Tools" (1.8.0.6027) by AlliedModders LLC: CS extended functionality
 "BinTools" (1.8.0.6027) by AlliedModders LLC: Low-level C/C++ Calling API
 "SDK Tools" (1.8.0.6027) by AlliedModders LLC: Source SDK Tools
 "Top Menus" (1.8.0.6027) by AlliedModders: Creates sorted nested menus
 "SDK Hooks" (1.8.0.6027) by AlliedModders LLC: Source SDK Hooks
 "Client Preferences" (1.8.0.6027) by AlliedModders: Saves client preference settings
 "SQLite" (1.8.0.6027) by AlliedModders LLC: SQLite Driver
 "Regex" (1.8.0.6027) by AlliedModders LLC: Provides regex natives for plugins
 "System2" (2.6) by David Ordnung: System and Internet commands for Sourcemod
 "PTaH (P Tools and Hooks)" (1.0.7) by Phoenix (˙·٠●Феникс●٠·˙): Expanding sdkhooks and sdktools
 "SteamWorks Extension" (1.2.1) by Kyle Sanderson: Exposes SteamWorks functions to Developers
 "CollisionHooks" (0.2) by VoiDeD: Hook on entity collision
 "SendProxy Manager" (1.1.4) by Afronanny: Change stuff without actually changing stuff!
 "Socket" (3.0.1) by Player: Socket extension for SourceMod
 "DHooks" (2.1.1) by Dr!fter: Dynamic Hooks
 "MySQL-DBI" (1.8.0.6027) by AlliedModders LLC: MySQL driver implementation for DBI)
- Version of TTT (TTT Version: 2.3.1407)
- List of your plugins 
 "Map Nominations" (1.8.0.6027) by AlliedModders LLC
 "Basic Commands" (1.8.0.6027) by AlliedModders LLC
 "SourceBans++: Bans Checker" (1.6.2) by psychonic, Ca$h Munny, SourceBans++ Dev Team
 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
 "Client Preferences" (1.8.0.6027) by AlliedModders LLC
 "Trouble in Terrorist Town - Teleporter" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: Martydom" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Traitor Traps" (2.3.1331) by TTT-Contributors, R3TROATTACK
 "Trouble in Terrorist Town - Knockout" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Dna Scanner" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Round End Sounds" (2.3.1407) by Bara (& AbNeR_CSS)
 "Trouble in Terrorist Town - Health/Hurt Stations" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: ID" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Hide Radar" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Overlays" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Buy Roles" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Silent AWP" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - TA-Grenade" (2.3.1407) by Bara, zipcore & Neuro Toxin
 "Trouble in Terrorist Town - Items: Weapons" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: Decoy Teleporter" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Talk Override" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: Healthshot" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - SQL Manager" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Poison Smoke" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: Taser" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Radar" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: Wallhack" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Glow" (2.3.1407) by Bara & zipcore
 "Trouble in Terrorist Town - Grabber Mod" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Spec Menu" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Blackout" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: Fake Body" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Items: Ice Knife" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Cameras and Drones" (2.3.1356) by TTT-Contributors
 "Trouble in Terrorist Town - Shop Discounts" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Crash Catcher" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Icons" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Traitor Doors" (2.3.1407) by zipcore
 "Trouble in Terrorist Town - Hud" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Decoy Body" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Shop" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - Sprint" (2.3.1407) by TTT-Contributors
 "Trouble in Terrorist Town - C4 & Jihad" (2.3.1407) by TTT-Contributors
 "SourceBans++: Main Plugin" (1.6.2) by SourceBans Development Team, SourceBans++ Dev Team
 "AdsQL Advertisements System" (2.3.1) by PharaohsPaw
 "Ingame Map Download" (2.2.2) by dordnung
 "Basic Info Triggers" (1.8.0.6027) by AlliedModders LLC
 "Block messages" (1.0.0) by Bara
 "Anti-Flood" (1.8.0.6027) by AlliedModders LLC
 "Rock The Vote" (1.8.0.6027) by AlliedModders LLC
 "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team
 "Playpark hud" (1.0) by playpark
 "CS:GO GiveNamedItem Hook Franug Edition" (5.0.3 private version) by Franc1sco franug and Neuro Toxin
 "Admin File Reader" (1.8.0.6027) by AlliedModders LLC
 "Fun Votes" (1.8.0.6027) by AlliedModders LLC
 "Nextmap" (1.8.0.6027) by AlliedModders LLC
 "fix_knives.smx" fix_knives.smx
 "Basic Comm Control" (1.8.0.6027) by AlliedModders LLC
 "SM Valve Gloves" (1.3.8) by Franc1sco franug and hadesownage
 "Admin Menu" (1.8.0.6027) by AlliedModders LLC
 "vip" (1.1) by Playpark
 "Basic Chat" (1.8.0.6027) by AlliedModders LLC
 "Ghost" (1.0) pp_ghost_1110_noblock.smx
 "SM CS:GO Franug Knives" (3.0.6 private version) by Franc1sco franug
 "No Weapon Fix" (3.2) by .#Zipcore
 "Z-Core: Loot Spawner" (3.9.3) by .#Zipcore
 "Player Commands" (1.8.0.6027) by AlliedModders LLC
 "SM CS:GO Weapon Paints" (6.6.4 private version) by Franc1sco franug
 "SourceBans++: SourceComms" (1.6.2) by Alex, SourceBans++ Dev Team
 "Updater" (1.2.2) by GoD-Tony
 "SourceBans++: Admin Config Loader" (1.6.2) by AlliedModders LLC, SourceBans++ Dev Team
 "Reserved Slots" (1.8.0.6027) by AlliedModders LLC
 "Admin Help" (1.8.0.6027) by AlliedModders LLC
 "Trusted VIP" (1.0) by LnG
 "Basic Votes" (1.8.0.6027) by AlliedModders LLC
 [TTT] KARMA HAS BEEN UPDATED!
 [TTT] TEAMS HAVE BEEN SELECTED!
 [TTT] 1 TRAITORS HAVE BEEN SELECTED
 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
 "VoiceAnnounceEx" (2.1.2) by Franc1sco franug, Mini and GoD-Tony
 "Cameras and Drones" (1.1.3) by Keplyx
 "MapChooser" (1.8.0.6027) by AlliedModders LLC
 "TTT Rank" (1.0) by LnG
 "Weapon-Loot" (1.1.3) by .#Zipcore
 "Self-Mute Intelligence" (1.5) by Otokiru, edit 93x, Accelerator, IT-KiLLER
 "csgotokens.com token changer" (1.2.1) by Adi - live4net
 "Ghost Collision" (1.0) pp_ghostcollision1110_noblock.smx
 "Fun Commands" (1.8.0.6027) by AlliedModders LLC
 "Easy Web Shortcuts" (1.00) by Invex | Byte)
- TTT related error logs - You can find the logs under: addons/sourcemod/logs/error_*.log - No errors

**Comment by Bara** [comment]
Try build 1409

> "Trouble in Terrorist Town - Traitor Traps" (2.3.1331) by TTT-Contributors, R3TROATTACK

Is obsolete, it was merged into the core.
