### ISSUE TITLE
randomly blocking

### ISSUE THREAD

**Issue by e54385991** [Bara/TroubleinTerroristTown#253]
sm version 1.9.0.6157

L 12/06/2017 - 21:21:49: [SM] Exception reported: Script execution timed out
L 12/06/2017 - 21:21:49: [SM] Blaming: ttt\ttt.smx
L 12/06/2017 - 21:21:49: [SM] Call stack trace:
L 12/06/2017 - 21:21:49: [SM]   [1] Line 1221, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 12/06/2017 - 21:21:49: [SM]   [2] Line 991, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection

when use sm_setrole ?

**Comment by good-live** [comment]
Can you confirm that this only happens when you use sm_setrole or buy a role for the next round in the shop?

**Comment by e54385991** [comment]
before TTT_OnClientGetRole use sm_setrole blocking is easy to happen
not yet tested the purchase of the role

**Comment by e54385991** [comment]
L 12/07/2017 - 01:29:23: [SM] Exception reported: Script execution timed out
L 12/07/2017 - 01:29:23: [SM] Blaming: ttt\ttt.smx
L 12/07/2017 - 01:29:23: [SM] Call stack trace:
L 12/07/2017 - 01:29:23: [SM]   [1] Line 1221, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 12/07/2017 - 01:29:23: [SM]   [2] Line 991, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection
L 12/07/2017 - 01:32:19: [SM] Exception reported: Script execution timed out
L 12/07/2017 - 01:32:19: [SM] Blaming: ttt\ttt.smx
L 12/07/2017 - 01:32:19: [SM] Call stack trace:
L 12/07/2017 - 01:32:19: [SM]   [1] Line 1221, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 12/07/2017 - 01:32:19: [SM]   [2] Line 991, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection
L 12/07/2017 - 01:33:11: [SM] Exception reported: Script execution timed out
L 12/07/2017 - 01:33:11: [SM] Blaming: ttt\ttt.smx
L 12/07/2017 - 01:33:11: [SM] Call stack trace:
L 12/07/2017 - 01:33:11: [SM]   [1] Line 1221, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 12/07/2017 - 01:33:11: [SM]   [2] Line 991, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection
L 12/07/2017 - 01:35:47: [SM] Exception reported: Script execution timed out
L 12/07/2017 - 01:35:47: [SM] Blaming: ttt\ttt.smx
L 12/07/2017 - 01:35:47: [SM] Call stack trace:
L 12/07/2017 - 01:35:47: [SM]   [1] Line 1221, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 12/07/2017 - 01:35:47: [SM]   [2] Line 991, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection
L 12/07/2017 - 01:44:43: Error log file session closed.
L 12/07/2017 - 01:44:43: SourceMod error session started
L 12/07/2017 - 01:44:43: Info (map "ttt_malibu") (file "errors_20171207.log")
L 12/07/2017 - 01:44:43: [sbpp_comms.smx] You must set valid `ServerID` value in sourcebans.cfg!
L 12/07/2017 - 01:46:59: [SM] Exception reported: Script execution timed out
L 12/07/2017 - 01:46:59: [SM] Blaming: ttt\ttt.smx
L 12/07/2017 - 01:46:59: [SM] Call stack trace:
L 12/07/2017 - 01:46:59: [SM]   [1] Line 1221, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 12/07/2017 - 01:46:59: [SM]   [2] Line 991, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection


buy role It should happen, too

**Comment by e54385991** [comment]
possible else? It happened on some maps 

		if (g_cInnocentKnife.BoolValue && GetPlayerWeaponSlot(client, CS_SLOT_KNIFE) == -1)
		{
			GivePlayerItem(client, "weapon_knife");
		}


		else
		{
			char sBuffer[32];
			int iEnt;
			
			while ((iEnt = GetPlayerWeaponSlot(client, CS_SLOT_KNIFE)) != -1)
			{
				GetEntityClassname(iEnt, sBuffer, sizeof(sBuffer));
				
				if (StrContains(sBuffer, "knife", false) != -1 || StrContains(sBuffer, "bayonet", false) != -1)
				{
Line ->1221		 TTT_SafeRemoveWeapon(client, iEnt);
				}
			}
		}

**Comment by Bara** [comment]
Has the player a knife or not?

**Comment by good-live** [comment]
I'll ask the other way around. Does this error occure when you don't use sm_setrole or buy a role via the shop?

**Comment by e54385991** [comment]
Some map give player knife

**Comment by Bara** [comment]
Try build 1416 (or above) if its done with buildung. This method works very well on my jail server in combination with csgoitems.

**Comment by e54385991** [comment]
sm plugins info ttt/ttt.smx
  Filename: ttt\ttt.smx
  Title: Trouble in Terrorist Town (The game is about a group of "terrorists" who have traitors among them, out to kill everyone who's not a traitor.)
  Author: TTT-Contributors
  Version: 2.3.1417
  URL: https://github.com/Bara/TroubleinTerroristTown
  Status: running
  Timestamp: 12/07/2017 00:59:32
  Hash: 4517a3dc2a8c967e40d901d28cd89119

Still

L 12/08/2017 - 14:15:30: [SM] Exception reported: Script execution timed out
L 12/08/2017 - 14:15:30: [SM] Blaming: ttt\ttt.smx
L 12/08/2017 - 14:15:30: [SM] Call stack trace:
L 12/08/2017 - 14:15:30: [SM]   [1] Line 1221, addons/sourcemod/scripting/ttt/ttt.sp::TeamInitialize
L 12/08/2017 - 14:15:30: [SM]   [2] Line 991, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection

**Comment by Bara** [comment]
Give build 1418 a chance.

**Comment by e54385991** [comment]
L 12/09/2017 - 13:46:14: Error log file session closed.
L 12/09/2017 - 13:46:15: SourceMod error session started
L 12/09/2017 - 13:46:15: Info (map "ttt_nukehouse_sg_fix1") (file "errors_20171209.log")
L 12/09/2017 - 13:46:15: [sbpp_comms.smx] You must set valid `ServerID` value in sourcebans.cfg!
L 12/09/2017 - 13:48:00: [ttt\ttt.smx] Can't remove knife! Player: "我是卖卖报的小行家y<41><STEAM_1:0:122577506><>"
L 12/09/2017 - 13:50:41: [ttt\ttt.smx] Can't remove knife! Player: "Месть Вернуться<10><STEAM_1:0:196265831><>"
L 12/09/2017 - 13:52:58: [ttt\ttt.smx] Can't remove knife! Player: "ミルク·奶牛<44><STEAM_1:0:152490437><>"
L 12/09/2017 - 14:00:41: [ttt\ttt.smx] Can't remove knife! Player: "大哥大plus<37><STEAM_1:1:114672053><>"
L 12/09/2017 - 14:09:13: [ttt\ttt.smx] Can't remove knife! Player: "AIMWANT.CC<25><STEAM_1:1:149376184><>"
L 12/09/2017 - 14:09:13: [ttt\ttt.smx] Can't remove knife! Player: "silverGoDPOKE<48><STEAM_1:1:122011200><>"
L 12/09/2017 - 14:15:01: [ttt\ttt.smx] Can't remove knife! Player: "ミルク·奶牛<44><STEAM_1:0:152490437><>"
L 12/09/2017 - 14:19:30: [ttt\ttt.smx] Can't remove knife! Player: "一个小可爱<58><STEAM_1:0:181869064><>"
L 12/09/2017 - 14:19:30: [ttt\ttt.smx] Can't remove knife! Player: "大哥大plus<37><STEAM_1:1:114672053><>"
L 12/09/2017 - 14:19:30: [ttt\ttt.smx] Can't remove knife! Player: "< 35 ><62><STEAM_1:0:157145502><>"
should fix script execution timed out

**Comment by Bara** [comment]
And it works (except timed out issue)? Because TTT_SafeRemoveWeapon return false

**Comment by e54385991** [comment]
test works
