### ISSUE TITLE
Incorrect version number printing

### ISSUE THREAD

**Issue by lay295** [Bara/TroubleinTerroristTown#256]
On spawn it print this message to clients "[TTT] Trouble in Terrorist Town - Version: \<VERSION\>"

Could you default ttt_show_advert_message to 0? Or set an actual version number in ttt.inc?
Thanks.

**Comment by good-live** [comment]
For an actual Version number you need to use our build Service. If you compile the sources yourself you need to edit the TTT.inc on your own.

**Comment by lay295** [comment]
Whoops, sorry about that. Was just recompiling all my plugins manually because of the recent crashes, should have looked into it more.
