### ISSUE TITLE
Move Precache out of OnConfigsExecuted

### ISSUE THREAD

**Issue by lay295** [Bara/TroubleinTerroristTown#257]
Could you move [these](https://github.com/Bara/TroubleinTerroristTown/blob/5e52d2c337dd99a3d3bb336d7b8f14669d10b7dd/addons/sourcemod/scripting/ttt/ttt.sp#L187-L192) lines to OnMapStart to prevent crashing with the [recent CS:GO update](https://forums.alliedmods.net/showthread.php?t=303249)?

Thanks.

**Comment by good-live** [comment]
It's not guaranteed, that the config is parsed OnMapStart. I also doubt that precaching those models during OnConfigsExecute is crashing the server. You got a proof of that or can somebody confirm it?

**Comment by lay295** [comment]
I'm not 100% sure it's this plugin, I've just recompiled all of my plugins because I didn't want to enable GOTV for a "fix". My TTT was crashing on map change, however I recompiled 4 other plugins along with this one, so I can't say for certain it was this one causing it.

I'll put the unedited version back on my server and see if there are crashes.

**Comment by lay295** [comment]
Yeah, when I put the original ttt.smx back, the crashes are back.

https://i.imgur.com/C6880IC.png

**Comment by Nachtfrische** [comment]
Wasn't it already confirmed that [Precache is causing server crashes](https://forums.alliedmods.net/showpost.php?p=2563689&postcount=110)?

Having the same kind of crashes on my server, so looking for an update since the server keeps crashing.

**Comment by good-live** [comment]
A post on the forum isn't really a confirmation ^^

Going to move those lines now.

**Comment by good-live** [comment]
ca3dc8ddb91ae097794a7cccfee2ba8ac5b7424b Done. @lay295 @Nachtfrische Can you test this please.

**Comment by Nachtfrische** [comment]
Yes, but it was confirmed by a [Sourcemod Moderator to be working](https://forums.alliedmods.net/showpost.php?p=2564968&postcount=5).

Thanks for that commit. I will test it and report back.

**Comment by rean1020** [comment]
It seems to be running fine, no crashes. Thank you for fixing it.

**Comment by Nachtfrische** [comment]
Seems to be working for me, I haven't heard of any crashes. Thanks for fixing the issue.
