### ISSUE TITLE
Not open window with url in start.cfg

### ISSUE THREAD

**Issue by rsgua** [Bara/TroubleinTerroristTown#258]
Not open window with url in start.cfg(sourcemod/configs/ttt/rules/).
When i press on menu nothing happened
Config:
"Rules"
{
	"1"
	{
		"title"			"Rules"
		"url"			"http://forum.in-g.su/pages/gamerules/"
	}
} 

Here's is a list what we need:
lates stable version of sm and mm
TTT Version: 2.3.1438

**Comment by Bara** [comment]
start.cfg doesn't support "url".
