### ISSUE TITLE
CS_OnTerminateRound do not work

### ISSUE THREAD

**Issue by Pixel333** [Bara/TroubleinTerroristTown#262]
Hello, i found new bug:

When i am innocent and i'll kill the traitor, round do not end.
When i am traitor and i'll kill all innocents and detectives, round do not end,
... 

Sourcemod: 1.8
TTT version: newest
Other plugins: only TTT
Console log: nothing

**Comment by Bara** [comment]
Gamedata updated? https://github.com/alliedmodders/sourcemod/commit/b43ab42d9c09708cc1ce5c15f47fdad4053ada61

**Comment by Pixel333** [comment]
Sure

**Comment by Bara** [comment]
Is ttt_debug_mode 0 ?

**Comment by NicronS** [comment]
We are having the same issue in HeLLsGamers, updated to latest SourceMod this morning and ttt_debug_mode is false.

`L 12/20/2017 - 00:06:39: [SM] Call stack trace:
L 12/20/2017 - 00:06:39: [SM]   [0] CS_TerminateRound
L 12/20/2017 - 00:06:39: [SM]   [1] Line 2718, ttt.sp::CheckTeams
L 12/20/2017 - 00:06:39: [SM]   [2] Line 1819, ttt.sp::Event_PlayerDeath
L 12/20/2017 - 00:10:06: [SM] Exception reported: Failed to locate function
L 12/20/2017 - 00:10:06: [SM] Blaming: ttt/ttt.smx
L 12/20/2017 - 00:10:06: [SM] Call stack trace:
L 12/20/2017 - 00:10:06: [SM]   [0] CS_TerminateRound
L 12/20/2017 - 00:10:06: [SM]   [1] Line 2718, ttt.sp::CheckTeams
L 12/20/2017 - 00:10:06: [SM]   [2] Line 1819, ttt.sp::Event_PlayerDeath
L 12/20/2017 - 00:11:43: [SM] Exception reported: Failed to locate function
L 12/20/2017 - 00:11:43: [SM] Blaming: ttt/ttt.smx`

**Comment by Bara** [comment]
Make sure the signature is updated. You can find it in addons/sourcemod/gamedata/sm-cstrike.games/game.csgo.txt / https://github.com/alliedmodders/sourcemod/blob/309e6ae959bd84bb69d629979c65ae98ad2b7128/gamedata/sm-cstrike.games/game.csgo.txt#L132-L137

**Comment by Pixel333** [comment]
@NicronS, you must rewritten it and restart server

**Comment by NicronS** [comment]
That works, thanks @Bara!
