### ISSUE TITLE
Server crashing after the map change,

### ISSUE THREAD

**Issue by dfarkash** [Bara/TroubleinTerroristTown#263]
When i'm changing the map the server crashing, no other mod then the TTT and the base sourcemod mods is installed,
```
Host_Error: Index error writing string table baseline downloadables
```

**Comment by good-live** [comment]
The posted error isn't the issue. Wenn need more information to help you.

**Comment by dfarkash** [comment]
[tttcrashlogs.txt](https://github.com/Bara/TroubleinTerroristTown/files/1583681/tttcrashlogs.txt)
[tttsmlog.txt](https://github.com/Bara/TroubleinTerroristTown/files/1583683/tttsmlog.

**Comment by Bara** [comment]
You should use [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703).
