### ISSUE TITLE
Blocking radio message bugged

### ISSUE THREAD

**Issue by PRAWKC** [Bara/TroubleinTerroristTown#267]
In ttt.cfg I have the following:
// Block radio messages in chat. 1 = Block, 0 = Don't Block
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
ttt_block_radio_message "1"

Messages are still appearing in chat like below while I have it set to block.
Cryptic (RADIO): FireBomb on the way!
born_confused (RADIO): Flashbang Out!

**Comment by SZOKOZ** [comment]
That cvar doesn't block grenade messages. What you are looking for is sv_ignoregrenaderadio 1

**Comment by PRAWKC** [comment]
🤦‍♂️ Thanks it got rid of my problem. Although I do not believe I even had this "sv_ignoregrenaderadio 1" and it was not displaying these message at some point.

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/79eeb6e7b373cbb1c18d42ef17964c9de9587af1 I've removed it and added to the recommeded cvar list: https://github.com/Bara/TroubleinTerroristTown/blob/master/CVARS.txt#L37
