### ISSUE TITLE
Body Identification in Logs

### ISSUE THREAD

**Issue by Drewerth** [Bara/TroubleinTerroristTown#269]
I already coded this thing but I'm new to Open Source and was advised to create an issue first before making a pull request.

I do the dev work on the Prestige Gaming servers and someone suggested this be (re)added to the sm_log function. If it was removed from the master branch you can just ignore this. If not I guess it was a pG-only thing but it seems like a useful tool because chat logs in console can get scrolled away rather quickly in populated servers.  

Really simple and the message looks like this:
(timestamp) -> Name identified body of DeadBoi (Detective)"

Full commit located at:
https://github.com/Drewerth/TroubleinTerroristTown/commits/patch-found-body-1

If you're fine with this I can go right over and make a pull request.

Thanks.

**Comment by Bara** [comment]
It's a nice Feature, so why not.

**Comment by Bara** [comment]
How about to add the role of client? Like "(timestamp) -> Name (ROLE) identified body of DeadBoi (Detective)"

**Comment by Drewerth** [comment]
I can push that into my repo before making a merge yeah

**Comment by Bara** [comment]
I could merge your commit without a pull request @Drewerth if you've no time.

**Comment by Drewerth** [comment]
Sure, that works. Since my current commit for the generic method is tested (and technically live on the Prestige Gaming server you can merge that one in. Due to travel I won't be able to add the second commit until later when I'm home and have time to work again.

**Comment by Drewerth** [comment]
Cool, looks like this is in.

Yay, I helped for once.

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/b0e4ba7c11bcd1588ebb4c4f0f486fc816ef8051
