### ISSUE TITLE
Request Feature: TTT Logs show who was looking at you when you kill someone.

### ISSUE THREAD

**Issue by SZOKOZ** [Bara/TroubleinTerroristTown#270]
Basically quoting this post on AM: https://forums.alliedmods.net/showthread.php?t=303900

This is a request to help admins determine if the accused is lying when they say they saw a traitor kill someone. On most TTT servers you cannot kill off location and sound but you can have some players that do this and lie about it saying they saw the traitor instead. I want to discuss some ways about what would be the best way to implement something like this.

Methods:
Simple way - On time of death check who is directly aiming at the killer. If there is a player looking at the killer simply log it.
Problem - You don't have to be directly aiming at the killer to actually see them. As long as they are in your field of view you can see them.

Improved way - On time of death, check for clients in visible range of the killer and log them.
Problem - Just because a player could potentially see the killer doesn't mean they were actually looking at the killer at the time of the kill.

Improved improved way: On time of death, check for clients in visible range and also check if the killer was in the actual view of the potential witnesses and log those who actually had the killer in view.
Problem - Implementation? 

The GetClientsInRange function sounds like it could find clients who have an unobstructed view of the target coordinate but I've never used it before so I'm not sure of it's actual method of finding visible clients. Will have to test it out. If it doesn't work how I imagine it does then I'm not fond of using a bajillion trace rays to find clients with potential view of the killer.
Anyway, discuss pl0x.

**Comment by SZOKOZ** [comment]
GetClientsInRange does a potential visible set check so it can retrieve clients who have a potential view of the killer. From there each client can be checked to see if they actually have the killer in view. Think a frustum trace would be a feasible option?

**Comment by whocodes** [comment]
Sounds like this could hog a lot of resources. Definitely should be configurable.

**Comment by SZOKOZ** [comment]
Figuring out a cheaper way to maybe achieve approximations. Maybe...

**Comment by good-live** [comment]
I don't think that this could be usefull. I mean you don't need visual contact to hear that there's somebody killed around the corner. When you then walk around the Corner and there is only one guy running away then the point ist pretty clear?

**Comment by SZOKOZ** [comment]
Kosing off sound and location is not allowed on servers mainly because of the room for error based on an individual's capacity to make sound judgement. The example you describe has the possibility of rdm since another player can appear from another entrance and swap positions with the real killer before the player who heard actually enters the room. Situations like that and others happen all the time on TTT thus to minimise rdm occurances most servers do not allow kos off sound or location. As an admin of a popular TTT server and a player of a few other TTT servers I know something like this would be very useful to admins. Though I do admit it this idea will have varying effectiveness depending on the server. Another reason it should be configurable.

**Comment by SZOKOZ** [comment]
Close to completing the stocks for this. This will not be expensive at all.

**Comment by SZOKOZ** [comment]
I've been making a stock for general use but it seems the "general use" stock will be more expensive than neccessary for TTT, so I'm going to make a pull using the more approximation and cheaper version of the stock. Will come soon, just need to make a time slot to implement the changes.

**Comment by Bara** [comment]
Any updates here?

**Comment by SZOKOZ** [comment]
Yeah, I just need one day where I can sit down and start integrating it to a version of TTT.

**Comment by Bara** [comment]
@SZOKOZ ?

**Comment by SZOKOZ** [comment]
I will add this, promi-

**Comment by Bara** [comment]
I'll play with this shit in a private version. It could be pushed into the public version, but Soon™.
