### ISSUE TITLE
Verbose Karma/Health HUD Message

### ISSUE THREAD

**Issue by drewerth** [Bara/TroubleinTerroristTown#271]
Another message fresh off the Prestige Gaming forums by one of our players...

They'd like to see that the gamemode has the option for us to display more verbose karma and health messages when you look at a player. I don't use this often but I believe it currently just displays integer values and a tag for what is what.

What they want is something more like GMod TTT:
```
-- TargetID health status
L.hp_healthy   = "Healthy"
L.hp_hurt      = "Hurt"
L.hp_wounded   = "Wounded"
L.hp_badwnd    = "Badly Wounded"
L.hp_death     = "Near Death"


-- TargetID karma status
L.karma_max    = "Reputable"
L.karma_high   = "Crude"
L.karma_med    = "Trigger-happy"
L.karma_low    = "Dangerous"
L.karma_min    = "Liability"
```

In your configuration and language files I suppose you could use:
```
"Hud PlayerKarma Verbose Max"
{
		"en"		"Reputable"
}
```
And add config options like:
```
{PlayerKarmaVerbose} {PlayerHealthVerbose}
```

**Comment by Bara** [comment]
We could keep {KARMA} and add new cvars for karma and health display. (like ttt_playerhud_karma_display 0 - Default (Integer), 1 - Text, ...)

**Comment by Drewerth** [comment]
I suppose that works too.

**Comment by Bara** [comment]
How about this as config:
https://pastebin.com/NdhvSrt8

**Comment by Drewerth** [comment]
As a translation name that seems like a great idea.

**Comment by popey456963** [comment]
In your example @Bara, are the keys (e.g. `75-85`) hardcoded, or can they be altered to other values?

**Comment by Bara** [comment]
Other are also possible and more than 5

**Comment by Bara** [comment]
It's finally done and will be added with #351 
https://steamcommunity.com/sharedfiles/filedetails/?id=1445511552
https://steamcommunity.com/sharedfiles/filedetails/?id=1445511399
https://steamcommunity.com/sharedfiles/filedetails/?id=1445511461
https://steamcommunity.com/sharedfiles/filedetails/?id=1445511640
https://steamcommunity.com/sharedfiles/filedetails/?id=1445511721
https://steamcommunity.com/sharedfiles/filedetails/?id=1445511771

**Comment by popey456963** [comment]
Some extra colours would be cool, e.g. on how hurt people are? :)

**Comment by Bara** [comment]
I could add another config entry for colors ("Translation" "Color Hexcode")

**Comment by popey456963** [comment]
My bad, this was not implemented how I thought it was. I'm pretty sure like this we could just implement colours in the strings themselves and it'd be easier? :)

**Comment by Bara** [comment]
You could do it with the translation file, but this will override with an update. ;)

**Comment by Bara** [comment]
@popey456963 Added and here are some example with/without color/s (codes):
https://steamcommunity.com/sharedfiles/filedetails/?id=1445551301
https://steamcommunity.com/sharedfiles/filedetails/?id=1445551340
https://steamcommunity.com/sharedfiles/filedetails/?id=1445551383
(Without color code it's default (white)) https://steamcommunity.com/sharedfiles/filedetails/?id=1445551442
