### ISSUE TITLE
Can you add set random custom skin?

### ISSUE THREAD

**Issue by rsgua** [Bara/TroubleinTerroristTown#272]
Can you add set random skin for t and ct from cfg file?
Cfg file for t:
models/skin1.mdl
models/skin2.mdl
Cfg file for ct:
models/skin1.mdl
models/skin2.mdl

**Comment by good-live** [comment]
Fail wrong issue number :man_facepalming:

**Comment by good-live** [comment]
I'm pretty sure there are plugins for this on AM. I don't see any reason to include this into TTT?

**Comment by Bara** [comment]
@good-live Compatible with TTT? I don't think so

**Comment by good-live** [comment]
What kind of compatibility is needed for TTT? I mean setting models on player spawn should work fine?

**Comment by Bara** [comment]
But if you want innocent/traitor models and separate detective models? For this you need as example [TTT_OnClientGetRole](https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/include/ttt.inc#L87)

**Comment by good-live** [comment]
True, but the request is models for T/CT ^^

**Comment by Bara** [comment]
@rsgua

**Comment by Bara** [comment]
I've ported my old models plugin, but I haven't time to test it. So I'm not sure if it works.
