### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ClydeSheldon** [Bara/TroubleinTerroristTown#278]
- Version of MetaMod  ( 1.10.7-dev)
- Version of SourceMod (SourceMod 1.8.0.6040)
- Version of TTT (TTT Version: 2.3.1449)

Lately I have noticed that for some reason TTT is using a lot of CPU usage. Has anyone else noticed this? Does anyone have any idea what is causing this.

The reason I believe TTT is at fault for the high CPU usage is because when I tested without TTT enabled it was showing normal usage. I was testing with bot_quota 10, sm_cvar sv_stressbots 1, and sm_cvar bot_flipout 1. 

With 10 Bots + me and the above cvars enabled CPU usage spikes to 54
So essentially it is using about 5% cpu per bot/player.  So once server reaches 20+ players it usually results in server restarting because cpu reaches 100%

**Comment by Bara** [comment]
That's a known issue: https://github.com/Bara/TroubleinTerroristTown/issues/5
Do you've installed glow, wallhacks and/or tagrenades?

**Comment by Bara** [comment]
I close this issue since that's a known issue from beginning (bad code base).
