### ISSUE TITLE
Dead body don`t check

### ISSUE THREAD

**Issue by rsgua** [Bara/TroubleinTerroristTown#282]
Some players can`t check dead players! Don`t all players! Please don`t close my issue!

**Comment by SZOKOZ** [comment]
Have you updated your TTT to the latest version.

**Comment by Bara** [comment]
Do you've now working models without issues ?

**Comment by rsgua** [comment]
i test last version of ttt
 i have bugs with models and body check
bug fixed for this player who rejoin to server

**Comment by Bara** [comment]
Can anyone confirm this?

**Comment by Drewerth** [comment]
I don't think I've gotten a bug report on pG about it.

**Comment by rsgua** [comment]
Bara just join to my server and see this bug
