### ISSUE TITLE
1511 errors 

### ISSUE THREAD

**Issue by e54385991** [Bara/TroubleinTerroristTown#285]
L 01/25/2018 - 00:00:00: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:00:00: [SM] Call stack trace:
L 01/25/2018 - 00:00:00: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/25/2018 - 00:00:00: [SM]   [3] Call_Finish
L 01/25/2018 - 00:00:00: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/25/2018 - 00:00:01: [SM] Exception reported: Array index out-of-bounds (index 25, limit 16)
L 01/25/2018 - 00:00:01: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:00:01: [SM] Call stack trace:
L 01/25/2018 - 00:00:01: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/25/2018 - 00:00:01: [SM]   [3] Call_Finish
L 01/25/2018 - 00:00:01: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/25/2018 - 00:00:06: [SM] Exception reported: Array index out-of-bounds (index 21, limit 16)
L 01/25/2018 - 00:00:06: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:00:06: [SM] Call stack trace:
L 01/25/2018 - 00:00:06: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/25/2018 - 00:00:06: [SM]   [3] Call_Finish
L 01/25/2018 - 00:00:06: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/25/2018 - 00:00:07: [SM] Exception reported: Array index out-of-bounds (index 21, limit 16)
L 01/25/2018 - 00:00:07: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:00:07: [SM] Call stack trace:
L 01/25/2018 - 00:00:07: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/25/2018 - 00:00:07: [SM]   [3] Call_Finish
L 01/25/2018 - 00:00:07: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/25/2018 - 00:00:07: [SM] Exception reported: Array index out-of-bounds (index 21, limit 16)
L 01/25/2018 - 00:00:07: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:00:07: [SM] Call stack trace:
L 01/25/2018 - 00:00:07: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/25/2018 - 00:00:07: [SM]   [3] Call_Finish
L 01/25/2018 - 00:00:07: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/25/2018 - 00:00:11: [SM] Exception reported: Array index out-of-bounds (index 21, limit 16)
L 01/25/2018 - 00:00:11: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:00:11: [SM] Call stack trace:
L 01/25/2018 - 00:00:11: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/25/2018 - 00:00:11: [SM]   [3] Call_Finish
L 01/25/2018 - 00:00:11: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/25/2018 - 00:16:20: Error log file session closed.
L 01/25/2018 - 00:16:21: SourceMod error session started
L 01/25/2018 - 00:16:21: Info (map "ttt_69thway_b3") (file "errors_20180125.log")
L 01/25/2018 - 00:16:21: [sbpp_comms.smx] You must set valid `ServerID` value in sourcebans.cfg!
L 01/25/2018 - 00:20:06: [SM] Exception reported: Array index out-of-bounds (index 20, limit 16)
L 01/25/2018 - 00:20:06: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:20:06: [SM] Call stack trace:
L 01/25/2018 - 00:20:06: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/25/2018 - 00:20:06: [SM]   [3] Call_Finish
L 01/25/2018 - 00:20:06: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/25/2018 - 00:20:06: [SM] Exception reported: Array index out-of-bounds (index 20, limit 16)
L 01/25/2018 - 00:20:06: [SM] Blaming: ttt\ttt.smx
L 01/25/2018 - 00:20:06: [SM] Call stack trace:

**Comment by e54385991** [comment]
This may be  dead body don`t check

**Comment by good-live** [comment]
@Bara we should definetly make an issue template 🤦‍
@e54385991 which version are you using?

**Comment by e54385991** [comment]
(2.3.1511)

**Comment by good-live** [comment]
Should be fixed in the latest version.

**Comment by Bara** [comment]
@good-live https://github.com/Bara/TroubleinTerroristTown/blob/master/ISSUE_TEMPLATE.md

**Comment by good-live** [comment]
Hmm okay i didn't knew that one :D :thumpup:
