### ISSUE TITLE
still random errrors

### ISSUE THREAD

**Issue by e54385991** [Bara/TroubleinTerroristTown#286]
sm_rcon sm plugins info ttt/ttt.smx
  Filename: ttt\ttt.smx
  Title: Trouble in Terrorist Town (The game is about a group of "terrorists" who have traitors among them, out to kill everyone who's not a traitor.)
  Author: TTT-Contributors
  Version: 2.3.1512
  URL: https://github.com/Bara/TroubleinTerroristTown
  Status: running
  Timestamp: 01/25/2018 15:18:33
  Hash: d178b3f2f34fd5001d2e36a609a53bd0

L 01/27/2018 - 15:33:24: Info (map "ttt_minecraft_b5_csgo_v1") (file "errors_20180127.log")
L 01/27/2018 - 15:33:24: [sbpp_comms.smx] You must set valid `ServerID` value in sourcebans.cfg!
L 01/27/2018 - 15:47:27: [ttt\ttt.smx] Can't remove knife! Player: "ちゆき<39><STEAM_1:0:180196850><>"
L 01/27/2018 - 15:47:35: [SM] Exception reported: Array index out-of-bounds (index 23, limit 16)
L 01/27/2018 - 15:47:35: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 15:47:35: [SM] Call stack trace:
L 01/27/2018 - 15:47:35: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 15:47:35: [SM]   [3] Call_Finish
L 01/27/2018 - 15:47:35: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/27/2018 - 15:47:46: [SM] Exception reported: Array index out-of-bounds (index 23, limit 16)
L 01/27/2018 - 15:47:46: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 15:47:46: [SM] Call stack trace:
L 01/27/2018 - 15:47:46: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 15:47:46: [SM]   [3] Call_Finish
L 01/27/2018 - 15:47:46: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/27/2018 - 15:47:46: [SM] Exception reported: Array index out-of-bounds (index 23, limit 16)
L 01/27/2018 - 15:47:46: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 15:47:46: [SM] Call stack trace:
L 01/27/2018 - 15:47:46: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 15:47:46: [SM]   [3] Call_Finish
L 01/27/2018 - 15:47:46: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/27/2018 - 15:47:46: [SM] Exception reported: Array index out-of-bounds (index 23, limit 16)
L 01/27/2018 - 15:47:46: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 15:47:46: [SM] Call stack trace:
L 01/27/2018 - 15:47:46: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 15:47:46: [SM]   [3] Call_Finish
L 01/27/2018 - 15:47:46: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/27/2018 - 15:47:47: [SM] Exception reported: Array index out-of-bounds (index 23, limit 16)
L 01/27/2018 - 15:47:47: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 15:47:47: [SM] Call stack trace:
L 01/27/2018 - 15:47:47: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 15:47:47: [SM]   [3] Call_Finish
L 01/27/2018 - 15:47:47: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/27/2018 - 15:47:47: [SM] Exception reported: Array index out-of-bounds (index 23, limit 16)
L 01/27/2018 - 15:47:47: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 15:47:47: [SM] Call stack trace:
L 01/27/2018 - 15:47:47: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 15:47:47: [SM]   [3] Call_Finish
L 01/27/2018 - 15:47:47: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
L 01/27/2018 - 15:47:47: [SM] Exception reported: Array index out-of-bounds (index 23, limit 16)
L 01/27/2018 - 15:47:47: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 15:47:47: [SM] Call stack trace:
L 01/27/2018 - 15:47:47: [SM]   [1] Line 2875, addons/sourcemod/scripting/ttt/ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 15:47:47: [SM]   [3] Call_Finish
L 01/27/2018 - 15:47:47: [SM]   [4] Line 2774, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd

**Comment by good-live** [comment]
Yeah I'm dump :D

**Comment by good-live** [comment]
Should be fixed now ^^

**Comment by e54385991** [comment]
Version: 2.3.1513

L 01/27/2018 - 16:51:49: [SM] Exception reported: String formatted incorrectly - parameter 7 (total 6)
L 01/27/2018 - 16:51:49: [SM] Blaming: ttt\ttt.smx
L 01/27/2018 - 16:51:49: [SM] Call stack trace:
L 01/27/2018 - 16:51:49: [SM]   [0] FormatNativeString
L 01/27/2018 - 16:51:49: [SM]   [1] Line 233, core/natives.sp::Native_LogString
L 01/27/2018 - 16:51:49: [SM]   [3] TTT_LogString
L 01/27/2018 - 16:51:49: [SM]   [4] Line 175, addons/sourcemod/scripting/ttt/ttt_dnascanner.sp::TTT_OnBodyChecked
L 01/27/2018 - 16:51:49: [SM]   [6] Call_Finish
L 01/27/2018 - 16:51:49: [SM]   [7] Line 2833, ttt.sp::TTT_OnButtonPress
L 01/27/2018 - 16:51:49: [SM]   [9] Call_Finish
L 01/27/2018 - 16:51:49: [SM]   [10] Line 2774, ttt.sp::OnPlayerRunCmd

**Comment by e54385991** [comment]
TTT_LogString("-> [%N%s (Detective) scanned a body, Killer was %N%s (%s) with Weapon: %s]", client, sClientID, attacker, sAttackerID, sRole,);

Should be 

TTT_LogString("-> [%N%s (Detective) scanned a body, Killer was %N%s (%s) with Weapon: %s]", client, sClientID, attacker, sAttackerID, sRole,iRagdollC[Weaponused]);

**Comment by Bara** [comment]
Added

**Comment by Bara** [comment]
@e54385991 Do you've tried my last [commit](https://github.com/Bara/TroubleinTerroristTown/commit/267bcc5ccfa36ef1feddb079137051831a56d397)?

**Comment by e54385991** [comment]
Should be fixed
