### ISSUE TITLE
Gamemode not working

### ISSUE THREAD

**Issue by artymo** [Bara/TroubleinTerroristTown#289]
When i set up the ttt gamemode and install everything right i try to run the server but when people join the server the gamemode is just causal and not custom 
i also get this error 
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_tactical_shield.smx
x": Could not find required plugin "tacticalshield"
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt.smx": Native "Sourc
ceBans_BanPlayer" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_taser.smx": Native
"TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_tracer.smx": Native
e "TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [ttt/ttt_grabbermod.smx] [GrabberMod] (LoadWhitelist) A
Add prop to array...
L 01/31/2018 - 10:19:32: [ttt/ttt_grabbermod.smx] [GrabberMod] (LoadWhitelist) A
Add physbox to array...
L 01/31/2018 - 10:19:32: [ttt/ttt_grabbermod.smx] [GrabberMod] (LoadWhitelist) A
Add player to array...
L 01/31/2018 - 10:19:32: [ttt/ttt_grabbermod.smx] [GrabberMod] (LoadWhitelist) A
Add ragdoll to array...
L 01/31/2018 - 10:19:32: [ttt/ttt_grabbermod.smx] [GrabberMod] (LoadBlacklist) A
Add fpd_ragdoll to array...
L 01/31/2018 - 10:19:32: [ttt/ttt_grabbermod.smx] [GrabberMod] (LoadBlacklist) A
Add knockout_ragdoll to array...
L 01/31/2018 - 10:19:32: [ttt/ttt_grabbermod.smx] [GrabberMod] (LoadBlacklist) A
Add door to array...
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_radar.smx": Native
"TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_decoy_teleport.smx"
": Native "TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_poison_smoke.smx":
Native "TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_dnascanner.smx": Na
ative "TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_buyRoles.smx": Nati
ive "TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_weapons.smx": Nativ
ve "TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_blackout.smx": Nati
ive "TTT_GetClientRole" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_glow.smx": Native "
"TTT_IsRoundActive" was not found
L 01/31/2018 - 10:19:32: [SM] Unable to load plugin "ttt/ttt_iceknife.smx": Nati
ive "TTT_IsRoundActive" was not found

**Comment by Bara** [comment]
Which sourcebans version do you use?

**Comment by artymo** [comment]
Im not sure where its located or if i had to download it then i dont have it

**Comment by Bara** [comment]
You should see version at the bottom of the page (example: [Painlessgaming](https://bans.painlessgaming.eu/) with SourceBans++ 1.5.4-dev-git329)

**Comment by artymo** [comment]
Oh well i dont have the webiste with sourceban or whatever but the game mode was perfectly working until last night when it just started doing that

**Comment by Bara** [comment]
Okay... I've reverted both commits.
