### ISSUE TITLE
C4 Wires

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#290]
https://skynetgaming.net/forums/topic/10641-ttt-c4-suggestion/

**Comment by good-live** [comment]
Isn't that already implemented? Let me take a look.

**Comment by good-live** [comment]
Yeah although it's not really nicely implemented:
https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp#L595
You can defuse a bomb with the reload button.

**Comment by Bara** [comment]
Convar for (c4) countdown
