### ISSUE TITLE
Turret

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#291]
https://forums.alliedmods.net/showthread.php?t=304965

https://forums.alliedmods.net/showpost.php?p=2474308&postcount=9
https://forums.alliedmods.net/showpost.php?p=2473507&postcount=3

**Comment by e54385991** [comment]
https://forums.alliedmods.net/showpost.php?p=2589375&postcount=2
Please test  
Added native
New Syntax
but functions not added （no much time）

**Comment by e54385991** [comment]
work for me 
video https://youtu.be/io0CTVAkSiw

you must wait role assign
use sm_cvar ttt_debug_mode 1
let BOT have role
only Innocent or Detective can destroy it

public void TTT_OnClientGetRole(int client, int role)
{
	if (TTT_IsClientValid(client) && IsPlayerAlive(client))
	{	
		if(role == TTT_TEAM_DETECTIVE || role == TTT_TEAM_INNOCENT)
			SetTurretCanAttackClient(client,true);
		else SetTurretCanAttackClient(client,false);
	}
}

**Comment by good-live** [comment]
This one would be nice ^^

https://forums.alliedmods.net/showthread.php?t=306114

**Comment by e54385991** [comment]
no linux game data lol Good work at windows

**Comment by Bara** [comment]
@good-live definitely, but plugins with gamedata require more attention after updates with possible breaking stuff/gamedatas. I don't really like plugins of that kind and avoid them.

**Comment by Bara** [comment]
@e54385991 Okay, it works now on my test server (with bots). Can you create a pull request(?), so we could share it to some other communities to test this stuff.

**Comment by e54385991** [comment]
created

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/pull/311
