### ISSUE TITLE
after 2/9/2018 or 2/8/2018 update some crashs

### ISSUE THREAD

**Issue by e54385991** [Bara/TroubleinTerroristTown#295]
https://crash.limetech.org/47nv5nxeorbb
https://crash.limetech.org/ldl2cf5relnq
server.dll + 0x1b6d8e
It happens only in TTT

mg/ze/cksurf/kz mod not appear

**Comment by e54385991** [comment]
may be https://forums.alliedmods.net/showpost.php?p=2577495

**Comment by Bara** [comment]
This isn't a ttt related error/issue. Disable healthshot feature and try again and wait until it's fixed by valve (kappa) or use a plugin as workaround.
