### ISSUE TITLE
Request: C4 Glow

### ISSUE THREAD

**Issue by therepower** [Bara/TroubleinTerroristTown#296]
hello,
it would be nice if you could make  it so the Planted C4 glows for the traitors.
without it, it causes quite a few RDMs  as the other traitors don't see the planted C4 and don't run away.

**Comment by good-live** [comment]
I remember that i've implemented that in the PLG version. It was a little bit tricky with the glow feature from CS:GO. A beacon or smth like that could be much easier.

**Comment by therepower** [comment]
the trator glow would work i think.

**Comment by therepower** [comment]
@good-live 
btw i tried the old version 
https://github.com/Bara/TroubleinTerroristTown/blob/spec_voice/addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp
it doesn't work atm probably needs some fix

**Comment by Bara** [comment]
@therepower these functions are commented out in this branch
Example: https://github.com/Bara/TroubleinTerroristTown/blob/spec_voice/addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp#L437-L439

**Comment by therepower** [comment]
i know i copied them and uncommented but don't seem to work

**Comment by Bara** [comment]
Preview of the "new" c4 beacon (no glow!) - only traitor see it: https://youtu.be/csYFzt4gjk4
