### ISSUE TITLE
Glow Hook

### ISSUE THREAD

**Issue by popey456963** [Bara/TroubleinTerroristTown#303]
It would be really great to be able to extend `ttt_glow.sp` without having to alter the file itself.  I'm _slightly_ struggling to think of an implementation myself, but my current thoughts are:

```
Native int TTT_GetGlow(int client);
Native int TTT_SetGlow(int client, int value);

...

int  g_glowPlayer[MAXCLIENTS];

public bool shouldGlow(int client) {
  return g_glowPlayer[client] ? true : false;
}

public bool onRoundStart() {
  // reset g_glowPlayer to falsey values
}
```

Then you can do bit arithmetic on the integer values stored within `g_glowPlayer` to, for instance, enable glow for your plugin:

```
// enable glow
TTT_SetGlow(client, TTT_GetGlow(client) | ARBITRARY_PLUGIN_OFFSET);
// disable glow
TTT_SetGlow(client, TTT_GetGlow(client) & !ARBITRARY_PLUGIN_OFFSET);
// disable all glow
TTT_SetGlow(client, 0);
```

This would allow multiple plugins to simultaneously alter glow without interfering with each other, since if any of them are enabled then `g_glowPlayer[client]` would be truthy.

I feel this is a better solution than forcing each plugin to alter `ttt_glow` itself with optional includes due to the far more pluggable nature of plugins to the system, `ttt_glow` doesn't know anything about them.  The only slight issue might be trying to organise the `ARBITRARY_PLUGIN_OFFSET` to not be identical, but you have 31 bits to play with.

**Comment by Bara** [comment]
We've a forward for this: [TTT_OnGlowCheck](https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/include/ttt_glow.inc#L6) - [Example here](https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_wallhack.sp#L240)

**Comment by popey456963** [comment]
Whaaaaaat, that's so cool!  Thanks.
