### ISSUE TITLE
New natives to get role id/name/shortname

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#309]
TTT_GetRoleNameByID
TTT_GetRoleNameByShortName

TTT_GetRoleIDByName
TTT_GetRoleIDByShortName

TTT_GetShortRoleNameByID
TTT_GetShortRoleNameByName

**Comment by good-live** [comment]
For what are those usefull?

**Comment by Bara** [comment]
It's an older request and could save some double checks/format/lines/...
Example: https://github.com/Bara/TroubleinTerroristTown/commit/bf66e46b77c6e3d49f0e17dbae05a5100bb36d01

**Comment by good-live** [comment]
I don't get the point of providing a native for those. It could be just a simple stock in the include file.

**Comment by Bara** [comment]
We could add it to the include, but if you use the include you must have the plugin too. So both works fine and required the same requirements.

**Comment by good-live** [comment]
Yeah but a stock is much more lightweigth compared to a native call.

**Comment by good-live** [comment]
At least thats what i expect.

**Comment by Bara** [comment]
Okay, stocks are slightly faster but that shouldn't affect anything with natives.

Native time for 5000 requests: 0.001128
Stock time for 5000 requests: 0.000650

Test case: https://pastebin.com/nfZfahXZ

**Comment by good-live** [comment]
That's actually nearly twice as fast ^^
