### ISSUE TITLE
Possibility to give players items from the shop

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#317]
I think it would be great to have this possibility to give items from the shop to players. This will allow server owners to implement dice features or implement this benefit to other plugins.

Chat with Bara: 
bool ClientBuyItem(int client, char[] item, bool menu, int price = -1)
and modify price if price != -1
(maybe with && price > 0
or... bool free = false and check it later... other way...

**Comment by Bara** [comment]
Native: TTT_GiveClientItem(client, item(shortName))
Command_ sm_giveitem <Name/#UserID> <item(shortName)>

**Comment by danielsartor** [comment]
Working! Thanks :D
