### ISSUE TITLE
Loot items from dead bodies when inspecting

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#318]
It would be nice to have a possibility to loot items from dead bodies. To setup the items that can be obtained from the loot it will need a cfg file:
i.e.:
{
     "innocent"
     {
          "buyTRole" "0.05" //Item (short name) and chance to loot this item (0.0 to 1.0)
          "taser" "0.5"
     }
     "traitor"
     {
          "taser" "0.3"
          "taser_t" "0.1"
     }
     "detective"
     {
          "taser" "0.5"
          "taser" "0.2"
     }
}

On the CFG you will be able to set multiple items and per role %. If you don't want innocent bodies to "drop" items, just leave empty.

I guess it would be nice to have at least 4 cvars.
**"ttt_loot_dead_bodies" "0"** _//0 = Disabled, 1 = Number of times (players) a bodie can be looted_
**"ttt_loot_block_roles" "0"** _//0 = Everyone can loot, 1 = Innocent only, 2 = Traitor only, 3 = Detective only_
**"ttt_loot_after_inspected" "0"** _//if ttt_loot_block_roles is above 0. 0 = Only the first player (if role allowed) will have a chance to loot. 1 = If a body was inspected by a non allowed role, the allowed role will be able to loot._
**"ttt_loot_assist_kill" "0"** _//0 = Disabled, 1 = Player who assisted on a kill can loot the body too, even if ttt_loot_dead_bodies is set to 1._

I tried to resume it, but if it's not clear enough I can give examples.

**Comment by Bara** [comment]
Would be nice but the current shop is not designed for this kind of stuff. I'll let this feature request open.

**Comment by danielsartor** [comment]
At the moment doesn't need to loot an item if the player had it before. With the new native to give an item from the shop, it's possible to check using the body inspect forward and make a math based on these values. So every body found will have a change of getting an item.

**Comment by Bara** [comment]
It makes no sense for me, when you can loot not exists/bought items. Either the dead player had a item and it can looted or not.

**Comment by danielsartor** [comment]
Well, the client body doesn't need to have credits to gain credits from looting. In MMORPGs wolfs can drop swords, rings, boots etc, but they don't wear it. IMO I think it would be nice to have this option of chance of getting items when inspecting. In the future when the store saves users purchases, then it could create a cvar like "ttt_loot_purchased_items" to only allowing looting the items that the user had when he died, like tasers or unsed c4/jihads for example.

**Comment by Bara** [comment]
test
