### ISSUE TITLE
TTT shop problem with TAgrenade, DNA Scanner

### ISSUE THREAD

**Issue by superblack4** [Bara/TroubleinTerroristTown#320]
And again is me, @good-live @Bara . Another problems for TTT shop are that:

1. TA Grenade can be only buy 1 time only for the whole time in server (Not 1 time for each round)
2. TA Grenade and DNA Scanner do not give any information. Any ideas about this issue?

I am so sorry for interupting you guys but those bugs are really annoying :( 
TTT Version: 1596 | a398e33

[tagrenade.txt](https://github.com/Bara/TroubleinTerroristTown/files/1971587/tagrenade.txt)
[dnascanner.txt](https://github.com/Bara/TroubleinTerroristTown/files/1971588/dnascanner.txt)
[errors_20180503.txt](https://github.com/Bara/TroubleinTerroristTown/files/1971593/errors_20180503.txt)

**Comment by Bara** [comment]
First issue should be fixed (detective ta-grenades was affected)
TA-Grenade works fine: https://steamcommunity.com/sharedfiles/filedetails/?id=1376869538
Also DNA-Scanner (Chat Message with [TTT] DECTIVE Bara Scanned a body....): https://steamcommunity.com/sharedfiles/filedetails/?id=1376869596

**Comment by superblack4** [comment]
@Bara I mean I can buy TA Grenade for the first time when I join the server. However, on the second I became the detective, I cannot buy the TA Grenade

**Comment by Bara** [comment]
And that should be fixed with https://github.com/Bara/TroubleinTerroristTown/commit/424eab5f9e43ed58cf138ad616cdbfcec560838f where I added the missing part while resetting stuff.

**Comment by superblack4** [comment]
@Bara Yeah i did but I did not receive the information when I use TA grenade. However,  this bug is rare

**Comment by Bara** [comment]
If it still happened, create new issue per bug (better to handle).
