### ISSUE TITLE
Weapon Spawner Problem

### ISSUE THREAD

**Issue by superblack4** [Bara/TroubleinTerroristTown#324]
Thank you so much for introducing the plugin @Bara 
So this is my hlspawner in database.cfg
Basically the first time I spawn the gun, it work. However, when i restart the server, the gun wasn't there anymore. Any solution?

"hl_weaponspawner"
{
"driver"	"sqlite"
"host"	"localhost"
"database"	"sourcemod"
"user"	""
"pass"	""
//"timeout"	"0"
//"port"	"0"
}

**Comment by Bara** [comment]
@superblack4 https://github.com/Rachnus/Entity-Spawner new alternative.
