### ISSUE TITLE
How do I install TTT to CSGo

### ISSUE THREAD

**Issue by zSixxMC** [Bara/TroubleinTerroristTown#330]
I don't know and cant understnad how to create a database, if oyu can make a turtioal that would be great. I don't understand it. Thank you. A video would be very helpful.

**Comment by Bara** [comment]
This gamemode should be drag&drop able. If you need mysql (default is sqlite) and didn't know how to create a database you shouldn't use this kind of feature.

**Comment by Bara** [comment]
And I would never provide a video tutorial. Why I should? To provide the lazy guys? No, thanks.

**Comment by zSixxMC** [comment]
I tried, the gamemdoe doesnt work. It doesnt load in.

**Comment by zSixxMC** [comment]
You don't have a turtioal...

**Comment by zSixxMC** [comment]
Also, I can't get bots to now spawn. Ive tried everythingh.

**Comment by zSixxMC** [comment]
How do I get a database.cfg file

**Comment by zSixxMC** [comment]
https://forums.alliedmods.net/showthread.php?t=273960

**Comment by zSixxMC** [comment]
is this what i download?

**Comment by Bara** [comment]
- If it doesn't load, you've error logs.
- Bots aren't supported.
- databases.cfg are located in addons/sourcemod/configs/
- Download TTT [here](https://csgottt.com) in a version in that version you run sourcemod.

**Comment by Bara** [comment]
And please, don't spam. Try to write it in one comment.

**Comment by zSixxMC** [comment]
I got it. Also, File uploads are disabled what do i do.

**Comment by Bara** [comment]
File uploads are disabled? If it true -> 👍

**Comment by zSixxMC** [comment]
I got fast dl. Bots keep spawning though.

**Comment by zSixxMC** [comment]
nvm i got it fully working thansk
