### ISSUE TITLE
[Suggestion] Add menu where players can easily handle items they bought.

### ISSUE THREAD

**Issue by Prefix** [Bara/TroubleinTerroristTown#331]
Hey, like people have to bind and remember many commands, it would be useful to just have a menu, where people get list of choises with items they currently own. (like if they click on menu Put Lasermine it executes sm_lasermine for player)

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/issues/318#issuecomment-386024678
We don't save any informations about bought items per player.

**Comment by popey456963** [comment]
So, when an item is bought seems like an easy thing to determine in the current system, would it be a good idea to have a native called by the plugins themselves to specify when they are used?
