### ISSUE TITLE
The RDM system is not working

### ISSUE THREAD

**Issue by superblack4** [Bara/TroubleinTerroristTown#336]
Even there is a menu pop up when a player got RDM, he/she cannot punish the killer when they choose "Punish" option. There is a message was print out when he/she choose punish option but there is nothing happen to the killer.

This happen for both Inocent vs Inocent, Traitor vs Traitor, Detective vs Detective, Detective vs Inocent.

Any solution to fix this problem? @Bara @good-live 

TTT version: 2.1622

**Comment by Bara** [comment]
@good-live changed something here or ( #315 )?

**Comment by good-live** [comment]
Yeah i changed some stuff, but @superblack4 confirmed that those changes are working. Im going to take a look at it today in the evening.

**Comment by superblack4** [comment]
I hope u can fix this issue as quick as possible :)
Thx you so much for ur effort @good-live  @Bara

**Comment by good-live** [comment]
Are there any errors related to ttt?
I coudn't find an error in the logic by taking a quick look.

Also check your ttt_round_slays_player_rdm_menu cvar pls.

**Comment by good-live** [comment]
ttt_round_slays_player_rdm_menu must be at least 1

**Comment by superblack4** [comment]
But then how can i force my people to instanly kill instead after 1 round @good-live ?

**Comment by good-live** [comment]
The RDM menu already forces an instant slay: https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt.sp#L3677 but that requires the rounds slays to be greater than 0 https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/core/natives.sp#L334

**Comment by superblack4** [comment]
@good-live  Because when i read the description on ttt.cfg, It say that put 0 for instant slay so I thought 0 would be the correct answer :v Anyway thx you so much for helping me and maybe you or @bara can change the description for ttt_round_slays_player_rdm_menu ?
