### ISSUE TITLE
People can't to talk each other while dead

### ISSUE THREAD

**Issue by Prefix** [Bara/TroubleinTerroristTown#337]
- Version of MetaMod  (meta version)
Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/f255fa5
Build ID: 961:f255fa5
Loaded As: Valve Server Plugin
Compiled on: Nov  5 2017
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/
- Version of SourceMod (sm version)
sm version
 SourceMod Version Information:
    SourceMod Version: 1.9.0.6232
    SourcePawn Engine: 1.9.0.6232, jit-x86 (build 1.9.0.6232)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: May 11 2018 06:32:57
    Built from: https://github.com/alliedmodders/sourcemod/commit/e71497e
    Build ID: 6232:e71497e
    http://www.sourcemod.net/
- List of your extensions (sm exts list)
sm exts list
[SM] Displaying 23 extensions:
[01] Automatic Updater (1.9.0.6232): Updates SourceMod gamedata files
[02] Webternet (1.9.0.6232): Extension for interacting with URLs
[03] Accelerator (2.3.3): SRCDS Crash Handler
[04] Equinox Console Cleaner (1.8.0-manual): Bite me alien boi
[05] cURL Extension (1.3.0.0): cURL Extension
[06] CS Tools (1.9.0.6232): CS extended functionality
[07] BinTools (1.9.0.6232): Low-level C/C++ Calling API
[08] SDK Tools (1.9.0.6232): Source SDK Tools
[09] SDK Hooks (1.9.0.6232): Source SDK Hooks
[10] <OPTIONAL> file "steamtools.ext.so": /home/csgoserver/serverfiles/csgo/addons-multigames/sourcemod/extensions/steamtools.ext.so: cannot open shared object file: No such file or directory
[11] SteamWorks Extension (1.2.2): Exposes SteamWorks functions to Developers
[12] Regex (1.9.0.6232): Provides regex natives for plugins
[13] <OPTIONAL> file "socket.ext.so": /home/csgoserver/serverfiles/csgo/addons-multigames/sourcemod/extensions/socket.ext.so: cannot open shared object file: No such file or directory
[14] Client Preferences (1.9.0.6232): Saves client preference settings
[15] MySQL-DBI (1.9.0.6232): MySQL driver implementation for DBI
[16] Top Menus (1.9.0.6232): Creates sorted nested menus
[17] GeoIP (1.9.0.6232): Geographical IP information
[18] GeoIPCity (1.1.2): Geographical IP information
[19] DHooks (2.1.1): Dynamic Hooks
[20] <OPTIONAL> file "store_sm.ext.so": /home/csgoserver/serverfiles/csgo/addons-multigames/sourcemod/extensions/store_sm.ext.so: cannot open shared object file: No such file or directory
[21] PTaH (P Tools and Hooks) (1.0.8): Expanding sdkhooks and sdktools
[22] <OPTIONAL> file "sendproxy.ext.so": /home/csgoserver/serverfiles/csgo/addons-multigames/sourcemod/extensions/sendproxy.ext.so: cannot open shared object file: No such file or directory
[23] SQLite (1.9.0.6232): SQLite Driver
- Version of TTT (sm_tttversion)
sm_tttversion
TTT Version: 2.1662
- List of your plugins (sm plugins list)
sm plugins list
[SM] Listing 146 plugins:
  01 "hl_weaponspawner.smx"
  02 "MotdMod" (1.2.2) by MOTDs Network
  03 "Auto NAV file creator" (1.0) by shavit
  04 "Resetscore" (2.6.0) by shavit
  05 "New Plugin" (1.0) by Unknown
  06 "[Source 2013] Custom Chat Colors" (3.1.2-CSGO) by Dr. McKay | Mitchell
  07 "Discord: SourceComms" (1.1) by .#Zipcore
  08 "Chat-Processor" (2.1.4) by Keith Warren (Shaders Allen)
  09 "[Any] Chat Logging Redux + RTF Support" (1.1.2) by McFlurry, Keith Warren (Drixevel)
  10 "CallAdmin" (0.1.5) by Impact, Popoklopsi
  11 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
  12 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  13 "SourceBans++: SourceSleuth" (1.6.3) by ecca, SourceBans++ Dev Team
  14 "Discord: SourceBans" (1.0) by .#Zipcore
  15 "[ANY] Player Analytics" (1.3.1) by Dr. McKay
  16 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
  17 "Discord API" (1.0) by .#Zipcore, Credits: Shavit, bara, ImACow and Phire
  18 "Discord: CallAdmin" (1.1) by .#Zipcore
  19 "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith Warren (Drixevel)
  20 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
  21 "Auto Recorder" (1.3.0) by Stevo.TVR
  22 "Toggle Music" (3.7.8) by Mitch & Agent Wesker
  23 "Player Commands" (1.9.0.6232) by AlliedModders LLC
  24 "Sound Commands" (1.9.0.6232) by AlliedModders LLC
  25 "Basic Info Triggers" (1.9.0.6232) by AlliedModders LLC
  26 "Anti-Flood" (1.9.0.6232) by AlliedModders LLC
  27 "Nextmap" (1.9.0.6232) by AlliedModders LLC
  28 "Basic Chat" (1.9.0.6232) by AlliedModders LLC
  29 "SQL Admins (Threaded)" (1.8.0.6041) by AlliedModders LLC
  30 "Fun Commands" (1.9.0.6232) by AlliedModders LLC
  31 "Basic Comm Control" (1.9.0.6232) by AlliedModders LLC
  32 "Client Preferences" (1.9.0.6232) by AlliedModders LLC
  33 "Reserved Slots" (1.9.0.6232) by AlliedModders LLC
  34 "Fun Votes" (1.9.0.6232) by AlliedModders LLC
  35 "Admin File Reader" (1.9.0.6232) by AlliedModders LLC
  36 "Basic Commands" (1.9.0.6232) by AlliedModders LLC
  37 "Basic Votes" (1.9.0.6232) by AlliedModders LLC
  38 "Admin Menu" (1.9.0.6232) by AlliedModders LLC
  39 "macrodox" (1.9) by aspi
  40 "Web Shortcuts CS:GO version" (2.3) by Franc1sco franug and James "sslice" Gray
  41 "[CS:GO] In game votes fix" (1.0) by PreFiX
  42 "kita/disable_autokick.smx"
  43 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
  44 "Map configs" (1.3) by Berni
  45 "Very Basic High Ping Kicker" (1.4) by msleeper
  46 "Store - Trade System" (1.0) by Zephyrus
  47 "Coinflip" (1.2) by hAlexr
  48 "Store - Nick bonus" (1.0) by Prefix
  49 "store/flag_credits.smx"
  50 "[ANY] Gifts" (2.3) by Zephyrus
  51 "Thirdperson | Mirrow Mode" (1.11) by Zephyrus
  52 "Stealth Revived" (0.7) by SM9();
  53 "SwapTeam" (1.2.6) by Rogue - Originally by MistaGee
  54 "adminWatch" (1.2.3 fixed by DoPe^) by Pat841
  55 "LAZERRRRSSSS!" (1.3.2) by MitchDizzle_
  56 "Admin loggin" (1.0) by vIr-Dan
  57 "[CSGO] Advanced Admin" (1.6.4) by PeEzZ
  58 "OVERWATCH:Nades" (1.0) by Potatoz
  59 "Anti-Reconnect" (1.1.5) by exvel
  60 "[UMC] Rock The Vote" (3.5.1) by Steell
  61 "[UMC] End of Map Vote" (3.5.1) by Steell
  62 "[UMC] Vote Command" (3.5.1) by Steell
  63 "[UMC] Prefix Exclusion" (3.5.1) by Steell
  64 "[UMC] Map Weight" (3.5.1) by Steell
  65 "[UMC] Post-Played Exclusion" (3.5.1) by Sazpaimon and Steell
  66 "[UMC] Player Limits" (3.5.1) by Steell
  67 "[UMC] Ultimate Mapchooser Core" (3.5.1) by Original:Steell, Update: Powerlord (3.4.6-dev), Mr.Silence (3.5.1)
  68 "[UMC] Nominations" (3.5.1) by Steell
  69 "[UMC] Echo Nextmap" (3.5.1) by Steell
  70 "[UMC] Player Count Monitor" (3.5.1) by Steell
  71 "[UMC] Map Commands" (3.5.1) by Steell
  72 "[UMC] Time Limits" (3.5.1) by Steell
  73 "[UMC] End of Map Vote Warnings" (3.5.1) by Steell
  74 "[UMC] Admin Menu" (3.5.1) by Steell
  75 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
  76 "No Block" (1.0.0.0) by sslice
  77 "Game_Player_Equip Fix" (1.1.1) by Mitch
  78 "Reload Map After Restart" (0.4) by [W]atch [D]ogs
  79 "No Weapon Fix" (1.1) by .#Zipcore
  80 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  81 "Terrible Enable Full Alltalk" (0.02) by Sheepdude
  82 "Disable Radar" (1.2.2) by Internet Bully, some random guy
  83 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
  84 "Advertisements" (0.8.0) by Tsunami, Edit By SimplyJpk
  85 "WebLinks" (1.1) by ESK0
  86 "[CSS/CSP/CSGO/TF2] Autorespawn" (1.4) by shavit
  87 "sbp.smx"
  88 "Store - The Resurrection" (1.0) by Zephyrus
  89 "Trouble in Terrorist Town - Shop Discounts" (2.1662) by TTT-Contributors
  90 "SM First Person View Models Interface" (3.1) by Franc1sco franug
  91 "CS:GO Turret Core" (1.0) by Tast - SDC Edited by Kento & e54385991
  92 "Tactical Shield" (1.1.0) by Keplyx
  93 "Futuristic Grenades v1.3.2" (1.3.4) by Rachnus
  94 "Tripmines 2016 Update" (1.0 ( will be never updated :) )) by 404, Bara
  95 "Trouble in Terrorist Town - Tripmines" (2.1662) by TTT-Contributors
  96 "Trouble in Terrorist Town - Grabber Mod" (2.1662) by TTT-Contributors
  97 "Trouble in Terrorist Town - Items: ID" (2.1662) by TTT-Contributors
  98 "Trouble in Terrorist Town - Futuristic Grenades" (2.1662) by TTT-Contributors
  99 "Trouble in Terrorist Town - Items: Weapons" (2.1662) by TTT-Contributors
  100 "Trouble in Terrorist Town - Shop" (2.1662) by TTT-Contributors
  101 "Trouble in Terrorist Town - Health/Hurt Stations" (2.1662) by TTT-Contributors
  102 "Trouble in Terrorist Town - Sprint" (2.1662) by TTT-Contributors
  103 "Trouble in Terrorist Town - Crash Catcher" (2.1662) by TTT-Contributors
  104 "Trouble in Terrorist Town - Tracer" (2.1662) by bbs.93x.net & zipcore
  105 "Trouble in Terrorist Town - Items: Wallhack" (2.1662) by TTT-Contributors
  106 "Trouble in Terrorist Town - Talk Override" (2.1662) by TTT-Contributors
  107 "Trouble in Terrorist Town - C4 & Jihad" (2.1662) by TTT-Contributors
  108 "Trouble in Terrorist Town - Drop Weapons" (2.1662) by TTT-Contributors
  109 "Trouble in Terrorist Town - Radio" (2.1662) by TTT-Contributors
  110 "Trouble in Terrorist Town - Silent AWP" (2.1662) by TTT-Contributors
  111 "Trouble in Terrorist Town - Round End Sounds" (2.1662) by Bara (& AbNeR_CSS)
  112 "Trouble in Terrorist Town - Tactical Shield" (2.1662) by TTT-Contributors
  113 "Trouble in Terrorist Town - Items: Taser" (2.1662) by TTT-Contributors
  114 "Trouble in Terrorist Town - Items: Martydom" (2.1662) by TTT-Contributors
  115 "Trouble in Terrorist Town - Items: Ice Knife" (2.1662) by TTT-Contributors
  116 "Trouble in Terrorist Town - SQL Manager" (2.1662) by TTT-Contributors
  117 "[CS:GO] Gun Menu" (1.2) by LumiStance (adapting by Grey83)
  118 "Trouble in Terrorist Town - Hud" (2.1662) by TTT-Contributors
  119 "Trouble in Terrorist Town - Parachute" (2.1662) by TTT-Contributors
  120 "Trouble in Terrorist Town - Icons" (2.1662) by TTT-Contributors
  121 "Trouble in Terrorist Town" (2.1662) by TTT-Contributors
  122 "Trouble in Terrorist Town - Nightvision" (2.1662) by TTT-Contributors
  123 "Trouble in Terrorist Town - Models" (2.1662) by Bara
  124 "Trouble in Terrorist Town - Teleporter" (2.1662) by TTT-Contributors
  125 "Trouble in Terrorist Town - Poison Smoke" (2.1662) by TTT-Contributors
  126 "Trouble in Terrorist Town - Turret" (2.1662) by TTT-Contributors & bbs.93x.net
  127 "Trouble in Terrorist Town - Spec Menu" (2.1662) by TTT-Contributors
  128 "Trouble in Terrorist Town - Buy Roles" (2.1662) by TTT-Contributors
  129 "Trouble in Terrorist Town - Items: Fake Body" (2.1662) by TTT-Contributors
  130 "Trouble in Terrorist Town - Items: Random Teleporter" (2.1662) by TTT-Contributors
  131 "Trouble in Terrorist Town - TA-Grenade" (2.1662) by Bara, zipcore & Neuro Toxin
  132 "Trouble in Terrorist Town - Hide Radar" (2.1662) by TTT-Contributors
  133 "Trouble in Terrorist Town - Radar" (2.1662) by TTT-Contributors
  134 "Trouble in Terrorist Town - Items: Decoy Teleporter" (2.1662) by TTT-Contributors
  135 "Trouble in Terrorist Town - Dna Scanner" (2.1662) by TTT-Contributors
  136 "Trouble in Terrorist Town - Glow" (2.1662) by Bara & zipcore
  137 "Trouble in Terrorist Town - Decoy Body" (2.1662) by TTT-Contributors
  138 "Trouble in Terrorist Town - Blackout" (2.1662) by TTT-Contributors
  139 "Trouble in Terrorist Town - Items: Healthshot" (2.1662) by TTT-Contributors
  140 "Trouble in Terrorist Town - Overlays" (2.1662) by TTT-Contributors
  141 "Trouble in Terrorist Town - Knockout" (2.1662) by TTT-Contributors
  142 "Trouble in Terrorist Town - Traitor Doors" (2.1662) by zipcore
  143 "Block messages" (1.0.0) by Bara
  144 "Advanced Parachute" (1.0) by ESK0
  145 "AFK Manager" (4.2.4) by Rothgar
  146 "Flashlight" (1.3.2) by Mitch
- TTT related error logs - You can find the logs under: addons/sourcemod/logs/error_*.log
none
- Steps to reproduce this issue
Dead players can't talk to each other in voice chat, only admins can hear people.
find talk
"sm_deadtalk" = "= "0" min. 0.000000 max. 2.000000                                  - Controls how dead communicate. 0 - Off. 1 - Dead players ignore teams. 2 - Dead" ( def. "0" ) min. 0.000000 max. 2.000000 - Controls how dead communicate. 0 - Off. 1 - Dead players ignore teams. 2 - Dead
"sv_alltalk" = "= "1" ( def. "0" ) game notify replicated                           - Deprecated. Replaced with sv_talk_enemy_dead and sv_talk_enemy_living." ( def. "0" ) game notify replicated - Deprecated. Replaced with sv_talk_enemy_dead and sv_talk_enemy_living.
"sv_auto_full_alltalk_during_warmup_half_end" = "= "1" game                         - When enabled will automatically turn on full all talk mode in warmup, at halftim" ( def. "1" ) game - When enabled will automatically turn on full all talk mode in warmup, at halftim
"sv_deadtalk" = "= "1" ( def. "0" ) game notify replicated                          - Dead players can speak (voice, text) to the living" ( def. "0" ) game notify replicated - Dead players can speak (voice, text) to the living
"sv_full_alltalk" = "= "1" ( def. "0" ) game replicated                             - Any player (including Spectator team) can speak to any other player" ( def. "0" ) game replicated - Any player (including Spectator team) can speak to any other player
"sv_show_voip_indicator_for_enemies" = "= "0" game replicated                       - Makes it so the voip icon is shown over enemies as well as allies when they are" ( def. "0" ) game replicated - Makes it so the voip icon is shown over enemies as well as allies when they are
"sv_talk_enemy_dead" = "= "1" ( def. "0" ) game replicated                          - Dead players can hear all dead enemy communication (voice, chat)" ( def. "0" ) game replicated - Dead players can hear all dead enemy communication (voice, chat)
"sv_talk_enemy_living" = "= "0" game replicated                                     - Living players can hear all living enemy communication (voice, chat)" ( def. "0" ) game replicated - Living players can hear all living enemy communication (voice, chat)
"ttt2_talk_override_version" = "= "2.1662" notify replicated 
"sv_deadtalk" = "1" ( def. "0" ) game notify replicated                          - Dead players can speak (voice, text) to the living"
"sv_talk_enemy_dead" = "1" ( def. "0" ) game replicated                          - Dead players can hear all dead enemy communication (voice, chat)" 
"sv_talk_enemy_living" = "0" game replicated                                     - Living players can hear all living enemy communication (voice, chat)" ( def. "0" ) game replicated - Living players can hear all living enemy communication (voice, chat"

Could be this caused by sv_deadtalk 0 ? or some other convars? I thought TTT handle voice chat by its own

**Comment by good-live** [comment]
This seems like another plugin is interfering.
"Terrible Enable Full Alltalk" might the problem.

**Comment by good-live** [comment]
If only admins are able to hear the dead people it has to be another sourcemod plugin interfering. The ttt talk override doesn't seperate normal players from admins. Neither does the spec Menu. Those are as far as i know the only plugins from ttt that interact with the ListenOverride API.

**Comment by Bara** [comment]
All dead players should hear every new dead player: https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_talk_override.sp#L139
But that could be disabled with SpecMenu ( https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_spec_menu.sp#L88 )

**Comment by Prefix** [comment]
According to feedback from server there is something wrong sometimes with spec list menu (mute alive and mute dead players buttons). They even manage to glitch that alive people can hear dead people

**Comment by Bara** [comment]
I've updated the voice stuff a bit in this pull request (but not merged yet): https://github.com/Bara/TroubleinTerroristTown/pull/343
If you're interested let me know.

**Comment by Bara** [comment]
Any updates here? @Prefix

**Comment by Prefix** [comment]
Empty server can't say anything atm, will reopen if happens again
