### ISSUE TITLE
Infinite round starts

### ISSUE THREAD

**Issue by voidgaming09** [Bara/TroubleinTerroristTown#342]
For some reason rounds are infinitely restarting and making you rechoose teams. 

Here's the error in console

Bogus constraint phys_hinge (attaches paint1 to ENTITY NOT FOUND:paint1_thing)
Bogus constraint phys_hinge (attaches paint1 to ENTITY NOT FOUND:paint1_thing)
Bogus constraint phys_hinge (attaches paint2 to ENTITY NOT FOUND:paint2_thing)
Bogus constraint phys_hinge (attaches paint2 to ENTITY NOT FOUND:paint2_thing)
Bogus constraint phys_hinge (attaches paint3 to ENTITY NOT FOUND:paint3_thing)
Bogus constraint phys_hinge (attaches paint3 to ENTITY NOT FOUND:paint3_thing)
Bogus constraint phys_hinge (attaches paint4 to ENTITY NOT FOUND:paint4_thing)
Bogus constraint phys_hinge (attaches paint4 to ENTITY NOT FOUND:paint4_thing)
Bogus constraint phys_hinge (attaches paint5 to ENTITY NOT FOUND:paint5_thing)
Bogus constraint phys_hinge (attaches paint5 to ENTITY NOT FOUND:paint5_thing)
Bogus constraint chan2_soc (attaches chan2 to ENTITY NOT FOUND:chan2_wire1)
Bogus constraint chan1_soc (attaches chan1 to ENTITY NOT FOUND:chan1_wire1)

**Comment by Prefix** [comment]
I think this was issue with some sourcemod version for me, try to downgrade sm version

**Comment by Bara** [comment]
Please use this template with more informations (like mm/sm/ttt version).
https://github.com/Bara/TroubleinTerroristTown/issues/new?template=Bug_Report.md
