### ISSUE TITLE
When spectating someone, make to show them role, not yours

### ISSUE THREAD

**Issue by Prefix** [Bara/TroubleinTerroristTown#344]
Like person cares about his own role when he is dead already... Ofc person can press tab and see if traitor or not, but that's taking more effort to do tho.

**Comment by Bara** [comment]
Showing the role of the person that you spectate will increase the chance of ghosting or not? We could change it for the players who have access to see the roles of others players.

**Comment by Prefix** [comment]
well I don't restrict seeing people who is who after death tho.

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/3e16b2a956779f2716d1f58dcc21ce7058fa39ae

**Comment by Bara** [comment]
@Prefix Any updates here?

**Comment by Prefix** [comment]
seems to be working fine
