### ISSUE TITLE
Log button errors

### ISSUE THREAD

**Issue by PRAWKC** [Bara/TroubleinTerroristTown#346]
**Issue:**
 Buttons on TTT maps are broken due to the following error below, this error is caused when you click buttons on TTT maps.

Here's is a list what we need:
**- Version of MetaMod  (meta version):** Metamod:Source version 1.10.7-dev
**- Version of SourceMod (sm version):** SourceMod 1.8.0.6040
**- Version of TTT (sm_tttversion):** TTT Version: 2.1687
**- TTT related error logs - You can find the logs under: addons/sourcemod/logs/error_*.log**
```
L 06/10/2018 - 21:21:44: [SM] Call stack trace:
L 06/10/2018 - 21:21:44: [SM]   [1] Line 572, addons/sourcemod/scripting/ttt/ttt.sp::OnButtonPressed
L 06/10/2018 - 21:21:50: [SM] Exception reported: Array index is out of bounds
L 06/10/2018 - 21:21:50: [SM] Blaming: ttt\ttt.smx
```

**- Steps to reproduce this issue**
Click any ttt map button and you will get this error in logs.

I noticed that the config.sp file that creates this convar "the ttt_log_pressed_buttons" is used twice which is likely contributing to this error although I believe I changed the convar and compiled and still got the same error. So I believe something else is wrong somewhere.(https://github.com/Bara/TroubleinTerroristTown/commit/ff3884c9aae05c243aa6396f51c6bb1cbbac7269)

```
g_cLogButtons = AutoExecConfig_CreateConVar("ttt_log_pressed_buttons", "0", "Log pressed buttons?", _, true, 0.0, true, 1.0);
g_cLogButtonsSpam = AutoExecConfig_CreateConVar("ttt_log_pressed_buttons", "5", "Prevent log spamming for the same button - Time in seconds to relog a button");
```

**Comment by Bara** [comment]
Reopen if still happens
