### ISSUE TITLE
Dead players can message/talk to life players. (SOLVED)

### ISSUE THREAD

**Issue by KrisTheCanadian** [Bara/TroubleinTerroristTown#350]
Hi, I'm currently having to following issues and would like some help. 

1- Dead players can message/talk to life players. (game breaking)

Here's is a list what we need:

MetaMod version: Source version 1.10.7-dev.

SM VERSION: 1.8.0.6047.

List of your extensions (sm exts list)

TTT Version: 2.1694

No error logs

Occurs all the time.

01 "Admin File Reader" (1.8.0.6047) by AlliedModders LLC
02 "Admin Help" (1.8.0.6047) by AlliedModders LLC
03 "Admin Menu" (1.8.0.6047) by AlliedModders LLC
04 "Always Weapon Skins" (2.2.6) by Neuro Toxin
05 "Anti-Flood" (1.8.0.6047) by AlliedModders LLC
06 "Basic Ban Commands" (1.8.0.6047) by AlliedModders LLC
07 "Basic Chat" (1.8.0.6047) by AlliedModders LLC
08 "Basic Comm Control" (1.8.0.6047) by AlliedModders LLC
09 "Basic Commands" (1.8.0.6047) by AlliedModders LLC
10 "Basic Info Triggers" (1.8.0.6047) by AlliedModders LLC
11 "Basic Votes" (1.8.0.6047) by AlliedModders LLC
12 "Block messages" (1.0.0) by Bara
13 "CallAdmin" (0.1.5) by Impact, Popoklopsi
14 "Chat-Processor" (2.1.4) by Keith Warren (Shaders Allen)
15 "Client Preferences" (1.8.0.6047) by AlliedModders LLC
16 "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith Warren (Drixevel)
17 "CS:GO Weapons Damage Mod" (2.0) by Accelerator
18 "SM Valve Gloves" (3.0) by Franc1sco franug and hadesownage
19 "[Source 2013] Custom Chat Colors" (3.1.0 CP) by Dr. McKay, Fixed up by Keith Warren (Drixevel)
20 "Custom Player Skins (Core)" (1.4) by Mitchell, Root
21 "Discord API" (1.0) by .#Zipcore, Credits: Shavit, bara, ImACow and Phire
22 "Discord: CallAdmin" (1.1) by .#Zipcore
23 "Discord: SourceBans" (1.0) by .#Zipcore
24 "Discord: SourceComms" (1.1) by .#Zipcore
25 "fix_knives.smx"
26 "[CS:GO] Show legit profile rank on scoreboard" (1.3) by Laam4
27 "CS:GO GiveNamedItem Hook Franug Edition" (6.0 private version) by Franc1sco franug and Neuro Toxin
28 "SM CS:GO Weapon Paints" (6.7.4 private version) by Franc1sco franug
29 "Fun Commands" (1.8.0.6047) by AlliedModders LLC
30 "Futuristic Grenades v1.3.2" (1.3.4) by Rachnus
31 "hextags" (1.32) by Hexah
32 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
33 "Mapchooser Extended Sounds" (1.10.2) by Powerlord
34 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
35 "No Weapon Fix" (3.2) by .#Zipcore
36 "Player Commands" (1.8.0.6047) by AlliedModders LLC
37 "Reserved Slots" (1.8.0.6047) by AlliedModders LLC
38 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
39 "SM CS:GO Franug Knives" (3.1 private version) by Franc1sco franug
40 "Sound Commands" (1.8.0.6047) by AlliedModders LLC
41 "Team Names" (1.1) by Internet Bully
42 "Test Messages" (1.0.0) by Keith Warren (Shaders Allen)
43 "Tripmines 2016 Update" (1.0 ( will be never updated :) )) by 404, Bara
44 "Trouble in Terrorist Town" (2.1694) by TTT-Contributors
45 "Trouble in Terrorist Town - Blackout" (2.1694) by TTT-Contributors
46 "Trouble in Terrorist Town - Buy Roles" (2.1694) by TTT-Contributors
47 "Trouble in Terrorist Town - C4 & Jihad" (2.1694) by TTT-Contributors
48 "Trouble in Terrorist Town - Crash Catcher" (2.1694) by TTT-Contributors
49 "Trouble in Terrorist Town - Decoy Body" (2.1694) by TTT-Contributors
50 "Trouble in Terrorist Town - Items: Decoy Teleporter" (2.1694) by TTT-Contributors
51 "Trouble in Terrorist Town - Dna Scanner" (2.1694) by TTT-Contributors
52 "Trouble in Terrorist Town - Drop Weapons" (2.1694) by TTT-Contributors
53 "Trouble in Terrorist Town - Items: Fake Body" (2.1694) by TTT-Contributors
54 "Trouble in Terrorist Town - Futuristic Grenades" (2.1674) by TTT-Contributors
55 "Trouble in Terrorist Town - Glow" (2.1694) by Bara & zipcore
56 "Trouble in Terrorist Town - Grabber Mod" (2.1694) by TTT-Contributors
57 "Trouble in Terrorist Town - Items: Healthshot" (2.1694) by TTT-Contributors
58 "Trouble in Terrorist Town - Hide Radar" (2.1694) by TTT-Contributors
59 "Trouble in Terrorist Town - Items: Ice Knife" (2.1694) by TTT-Contributors
60 "Trouble in Terrorist Town - Icons" (2.1694) by TTT-Contributors
61 "Trouble in Terrorist Town - Items: ID" (2.1694) by TTT-Contributors
62 "Trouble in Terrorist Town - Knockout" (2.1694) by TTT-Contributors
63 "Trouble in Terrorist Town - Items: Martydom" (2.1694) by TTT-Contributors

64 "Trouble in Terrorist Town - Models" (2.1694) by Bara
65 "Trouble in Terrorist Town - Nightvision" (2.1694) by TTT-Contributors
66 "Trouble in Terrorist Town - Overlays" (2.1694) by TTT-Contributors
67 "Trouble in Terrorist Town - Parachute" (2.1674) by TTT-Contributors
68 "Trouble in Terrorist Town - Hud" (2.1694) by TTT-Contributors
69 "Trouble in Terrorist Town - Poison Smoke" (2.1694) by TTT-Contributors
70 "Trouble in Terrorist Town - Radar" (2.1694) by TTT-Contributors
71 "Trouble in Terrorist Town - Radio" (2.1694) by TTT-Contributors
72 "Trouble in Terrorist Town - Items: Random Teleporter" (2.1694) by TTT-Contributors
73 "Trouble in Terrorist Town - Round End Sounds" (2.1694) by Bara (& AbNeR_CSS)
74 "Trouble in Terrorist Town - Shop" (2.1694) by TTT-Contributors
75 "Trouble in Terrorist Town - Shop Discounts" (2.1694) by TTT-Contributors
76 "Trouble in Terrorist Town - Silent AWP" (2.1694) by TTT-Contributors
77 "Trouble in Terrorist Town - Spec Menu" (2.1694) by TTT-Contributors
78 "Trouble in Terrorist Town - Sprint" (2.1694) by TTT-Contributors
79 "Trouble in Terrorist Town - SQL Manager" (2.1694) by TTT-Contributors
80 "Trouble in Terrorist Town - Health/Hurt Stations" (2.1694) by TTT-Contributors
81 "Trouble in Terrorist Town - Tactical Shield" (2.1694) by TTT-Contributors
82 "Trouble in Terrorist Town - TA-Grenade" (2.1694) by Bara, zipcore & Neuro Toxin
83 "Trouble in Terrorist Town - Talk Override" (2.1694) by TTT-Contributors
84 "Trouble in Terrorist Town - Items: Taser" (2.1694) by TTT-Contributors
85 "Trouble in Terrorist Town - Teleporter" (2.1694) by TTT-Contributors
86 "Trouble in Terrorist Town - Tracer" (2.1694) by bbs.93x.net & zipcore
87 "Trouble in Terrorist Town - Traitor Doors" (2.1694) by zipcore
88 "Trouble in Terrorist Town - Tripmines" (2.1694) by TTT-Contributors
89 "Trouble in Terrorist Town - Turret" (2.1694) by TTT-Contributors & bbs.93x.net
90 "Trouble in Terrorist Town - Items: Wallhack" (2.1694) by TTT-Contributors
91 "Trouble in Terrorist Town - Items: Weapons" (2.1694) by TTT-Contributors
92 "CS:GO Turret Core" (1.0) by Tast - SDC Edited by Kento & e54385991
Errors:
ttt\ttt_parachute.smx (Trouble in Terrorist Town - Parachute): Could not find required plugin "AdvancedParachute"
ttt\ttt_tactical_shield.smx (Trouble in Terrorist Town - Tactical Shield): Could not find required plugin "tacticalshield"

Here are the list of server CVAR

sv_hibernate_when_empty 0
bot_quota 0
sm_cvar mp_weapons_allow_map_placed 1
sgi_groupid 103582791462380369
mp_afterroundmoney 0
mp_autoteambalance 0
mp_backup_round_file 0
mp_backup_round_file_last 0
mp_backup_round_file_pattern 0
sm_cvar mp_footsteps 1
mp_free_armor 0
mp_freezetime 1
mp_match_end_changelevel
mp_ignore_round_win_conditions 1
mp_join_grace_time 30
mp_limitteams 0
mp_match_restart_delay 5
mp_maxmoney 0
mp_maxrounds 10
mp_playercashawards 0
mp_playerid 0
mp_playerid_delay 0.1
mp_playerid_hold 0.3
mp_radar_showall 0
mp_roundtime 5
mp_startmoney 0
mp_teamcashawards 0
mp_teamcashawards 0
mp_teammates_are_enemies 1
mp_timelimit 15
mp_free_armor 1
mp_warmuptime 0
mp_weapons_allow_heavyassaultsuit 1
sv_lan 0
sv_allow_thirdperson 1
sv_allow_votes 0
sv_allow_wait_command 0
sv_alltalk 1
sv_full_alltalk 1
sv_deadtalk 0
mp_match_end_changelevel 0
sv_holiday_mode 0
sv_ignoregrenaderadio 1
cl_downloadfilter all
weapon_reticle_knife_show 1
cd_droneprice "30000"
cd_camprice "30000"
sv_allowdownload 1
sv_hibernate_when_empty 1
sv_hibernate_postgame_delay 240
sm_cvar sv_disable_motd 0
sv_hibernate_when_empty 0
sv_hibernate_postgame_delay -1
sm_cvar sv_hibernate_when_empty 0
sm_cvar sv_hibernate_postgame_delay -1
sv_allowupload 1
writeid
writeip
sv_broadcast_ugc_downloads 1
sm_teamname_t "Citizens"
sm_teamname_ct "Detectives"
sm_weaponpaints_onlyadmin 0
sm_cvar sv_alltalk 1
sm_cvar sv_full_alltalk 1
sm_cvar sv_deadtalk 0

**Comment by good-live** [comment]
Can you try it with the following cvar values:
"sv_full_alltalk" = "0"
"sv_talk_enemy_dead" = "0"
"sv_talk_enemy_living" = "0"

**Comment by KrisTheCanadian** [comment]
It's still an issue. 
![20180619175437_1](https://user-images.githubusercontent.com/31254679/41626384-1d468d62-73ea-11e8-9641-8adc5bd7c523.jpg)

**Comment by KrisTheCanadian** [comment]
Solved. It was a plugin conflict.

**Comment by good-live** [comment]
Which plugin caused the conflict? We had other guys reporting this problem.
