### ISSUE TITLE
debugging in the chat

### ISSUE THREAD

**Issue by Septembers** [Bara/TroubleinTerroristTown#353]
i use verison (2.1697), and I have a problem with debugging in the chat
https://pp.userapi.com/c845221/v845221457/882ad/YL4qSTFb_Rg.jpg (screenshot)

and another question. Detective now has a free scanner?

**Comment by Septembers** [comment]
okay, problem solved gbm_show_name "0"

Detective now has a free scanner?

**Comment by Bara** [comment]
> Detective now has a free scanner?

Yes, related configs for this: dna_spawn_with and dna_free_scanner_count
