### ISSUE TITLE
Changelevel bug

### ISSUE THREAD

**Issue by geison66** [Bara/TroubleinTerroristTown#355]
Here's is a list what we need ( __Please use [Pastebin.com](https://pastebin.com), [hastebin](https://hastebin.com) or other online paste tools for the following things__ ):
- Version of MetaMod (meta version): Metamod:Source version 1.10.7-dev
- Version of SourceMod (sm version): SourceMod Version: 1.9.0.624
- List of your extensions (sm exts list): https://pastebin.com/DbXZUPDq
- Version of TTT (sm_tttversion): TTT Version: 2.1704
- List of your plugins (sm plugins list): https://pastebin.com/DbXZUPDq
- TTT related error logs - (You can find the logs under: addons/sourcemod/logs/error_*.log): No error logs
- Steps to reproduce this issue
Set mp_timelimit 30 and mp_maxrounds 0, when timelimit over, server does not perform the changelevel, gets stucked in same map forever. Need restart to back.

I tried default SM mapchooser, mapchooser extended and ultimate mapchooser, none works.
I have various servers, only this have this bug.

**Comment by Bara** [comment]
What's the value of `mp_match_end_changelevel`?

**Comment by geison66** [comment]
mp_match_end_changelevel 1

**Comment by geison66** [comment]
I tried, but no result.
Sometimes the server changes maps 2 or 3 times correctly, but then it stops working.

Its totally random.
And when happens, i need restart the server.

**Comment by popey456963** [comment]
I'm not sure if this helps, but we had this on our Jailbreak server a while ago and it turned out to be the map somehow messing it up.  If it only won't change on one particular map?

**Comment by geison66** [comment]
No, it's totally random, not in particular map.
I thought it was the workshop maps, then I remove it from my server but the error continued.

I'll do a clean installation of the server to see if the problem persists.

**Comment by geison66** [comment]
Fresh server install worked :)
