### ISSUE TITLE
Negative karma on score

### ISSUE THREAD

**Issue by popey456963** [Bara/TroubleinTerroristTown#356]
```
Metamod:Source: 1.10.7-dev
SourceMod: 1.9.0.6241
TTT: 2.1698
Extensions: https://femto.pw/kuo1.c
Plugins: https://femto.pw/jj9z.c
Errors: Nothing found
Steps to reproduce this issue: Unknown
```

![](https://femto.pw/q68o)

**Comment by good-live** [comment]
You need to describe it a little bit at least ^^. Hard to find the error if its not reproducable.

**Comment by popey456963** [comment]
A fair point, I'm not sure.  This is a completely fresh install on a new server running a fairly recent version of TTT.  I was hoping that people just hadn't been running a later version and this was a bug that could be reproduced just by updating to this version?

If not, I think I'll close this issue.

**Comment by Bara** [comment]
( This will be handled in this function: https://github.com/Bara/TroubleinTerroristTown/blob/c4f6765e2094ec37deb8729923b8489fe89c90a5/addons/sourcemod/scripting/ttt/ttt.sp#L1608-L1637 )

**Comment by popey456963** [comment]
Oh damn.

In which case, thanks for implementing a feature that I get asked if I can create a lot! :+1:
