### ISSUE TITLE
Feature Request: Make people glow after being tased

### ISSUE THREAD

**Issue by popey456963** [Bara/TroubleinTerroristTown#358]
At the moment people have to check chat to see whether the person they've just tased is traitor / innocent / detective.  This is sometimes hard (as sometimes we have a lot of messages saying many differing things), it seems like it might be easier if (as well as a chat message), the player that was just tased is made to glow in red / green / blue.

Unfortunately, glow going through walls might detract from this effect, I'm not sure if there's a way to temporarily make a player glow but make sure it doesn't do it through walls?

**Comment by Bara** [comment]
It's done and will be added with #351
