### ISSUE TITLE
C4 Spawn bug

### ISSUE THREAD

**Issue by ClydeSheldon** [Bara/TroubleinTerroristTown#365]
TTT Version: 2.1728
SM Version: 1.9.0.6245
MM version: 1.10.7-dev

Steps to reproduce:
- Buy C4 as Traitor
- Right click to plant. 
- Close menu by clicking 9

C4 does not get removed when you close menu, someone can place as many C4 as they want. Also when the last C4 is placed and activated then all C4s beep but only one will explode.

https://i.imgur.com/qqhWT3o.jpg

**Comment by Bara** [comment]
Thanks, should be fixed with this: https://github.com/Bara/TroubleinTerroristTown/commit/71307cdaf85c1c21fe94a76988cd9f264642b90c

But that's isn't compatible to the latest stable version and will included with the bigger changes ( #351 ).
