### ISSUE TITLE
a bug to fly

### ISSUE THREAD

**Issue by happymix** [Bara/TroubleinTerroristTown#368]
TTT Version: 2.1728
SM Version: 1.9.0.6245
MM version: 1.10.7-dev
Steps to reproduce:
1.Stand on a func_breakable/prop_dynamic/prop_dynamic_xxxxxxx
2.Press E to what u are standing on
3.Press space,then u will be pushed to sky

**Comment by Bara** [comment]
This is [already fixed](https://github.com/Bara/TroubleinTerroristTown/commit/f4054d832488c926a8374ab82f32acfcb8daa778#diff-006c3765d980a9a1e7e5a5988c717d6c) in the [ghostdm-Branch](https://github.com/Bara/TroubleinTerroristTown/pull/351).

**Comment by happymix** [comment]
thankx and sry for waste ur time QAQ

**Comment by Bara** [comment]
np, there isn't any exist issue about this. 👍 Now we've a reference issue for this.

**Comment by happymix** [comment]
0 0,One more question,is there any list of entities and functions which only supported by ttt plugin?I want to make my map funny qwq

**Comment by Bara** [comment]
Depends on the server configs: https://github.com/Bara/TroubleinTerroristTown/tree/ghostDeathmatch/addons/sourcemod/configs/ttt
https://github.com/Bara/TroubleinTerroristTown/blob/ghostDeathmatch/addons/sourcemod/scripting/ttt/ttt_traitordoors.sp

**Comment by happymix** [comment]
Very thankx,helpfulヽ(=^･ω･^=)丿
