### ISSUE TITLE
Server Crash when some one throw a missile

### ISSUE THREAD

**Issue by nanociaglia** [Bara/TroubleinTerroristTown#373]
[Meta list] https://pastebin.com/SBhQBuka
[Meta version] https://pastebin.com/biiPRMG7
[SM Version] https://pastebin.com/0ZwdUDgK
[SM Exts list] https://pastebin.com/xX7FNCFG
[TTT Version] Last stable https://csgottt.com/downloads/dev/ttt-dev-1.9-3.1924-f22a8045-442667852.zip
[SM Plugins list] https://pastebin.com/epyVj3WT
[Logs] nothing
[Crash ID from Accelerator] https://crash.limetech.org/xglnwhwvpzo2

Simple, the server crash after i throw a missile (there's no problem when i buy it, it just crash when i throw the nade/missile [every style of missile])

**Comment by Bara** [comment]
Try the latest version (at least 1927)

**Comment by nanociaglia** [comment]
It happened again, i'm using 1930 now

https://crash.limetech.org/db3cki4w233p

**Comment by nanociaglia** [comment]
i've tested it only me (ttt_debug_mode 1) to see if it works, and it does. Also i've tested it with +2 players (they wanted to help me to test the missiles) and it WORKS TOO. The problem appears when the server have +4 people.

**Comment by Bara** [comment]
And the crash dump is equal to the first one?

**Comment by nanociaglia** [comment]
Fixed! I just started to disabling plugins and i found a trouble between ttt_missiles and another obsolete plugin for a different mode, so there's no problem with missiles, i'm so sorry

**Comment by Bara** [comment]
👌
