### ISSUE TITLE
Dead players can't talk until next round (after the 30 seconds of warmup)

### ISSUE THREAD

**Issue by nanociaglia** [Bara/TroubleinTerroristTown#374]
There's a problem with dead players, they can't talk until a new round begins, after the 30 seconds of warmup round

**Comment by SZOKOZ** [comment]
To clarify, they can't use the text chat?

**Comment by nanociaglia** [comment]
I've a text chat blocker, dead people can read only dead people, and alive people can read only alive people

**Comment by nanociaglia** [comment]
Dead players = They only can talk with others dead players 

Alive players = They only can talk with others alive players

So when round start again, people that were dead, could not talk until the warmup round end (the first 30s to hide and find weapons at round start). After these 30 seconds, ppl that were dead in the last round will be able to start speaking. So only these people that who survived can talk in the warmup.

I think all people should be able to talk on warmup

**Comment by SZOKOZ** [comment]
That seems like typical CSGO behaviour. Well, one way of circumventing this would be to revive players who have died during warmup immediately instead of after the warmup time. @Bara

**Comment by nanociaglia** [comment]
I think that did not happen with the previous TTT version (before TTT 3)

**Comment by SZOKOZ** [comment]
So when a player dies on the previous TTT round, communication wise they are considered dead until the next TTT round start regardless of them being alive on warmup. I see... I'll check properly if it is common on other servers.

**Comment by nanociaglia** [comment]
Exactly! sorry for my very bad english.
Thank you.

**Comment by SZOKOZ** [comment]
It was more like I couldn't believe what you intended so I thought you meant something else.
