### ISSUE TITLE
Native to block a few entities from grabbermod

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#375]
I would like to block a few entities from being grabbed, but the only way to identify my entity is through "m_iGlobalname".

Every update I need to add manually this snipped of code after line 175.
`char myentity[128];
    GetEntPropString(ent, Prop_Data, "m_iGlobalname", myentity, sizeof(myentity));
    if (StrContains(myentity, "MyEntityName", false) != -1)
    {
        return;
    }`

**Comment by good-live** [comment]
I don't think that this should be done via native, but instead via a config.

**Comment by danielsartor** [comment]
I agree, but expanding the possibilities from the blacklist_grabbermod.ini will probably cause other issues, no?

I thought about the native because developers could use it for other reasons too, like checking entities or enabling disabled other things.

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/include/ttt_grabbermod.inc
We've a forward.
