### ISSUE TITLE
Turret Core Issue

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#376]
L 10/18/2018 - 10:55:21: [SM] Exception reported: Fatal error creating dynamic native!
L 10/18/2018 - 10:55:21: [SM] Blaming: ttt/turret_core.smx
L 10/18/2018 - 10:55:21: [SM] Call stack trace:
L 10/18/2018 - 10:55:21: [SM]   [0] CreateNative
L 10/18/2018 - 10:55:21: [SM]   [1] Line 507, addons/sourcemod/scripting/turret_core.sp::AskPluginLoad2
L 10/18/2018 - 10:55:21: [SM] Failed to load plugin "ttt/turret_core.smx": unexpected error 23 in AskPluginLoad callback.

**Comment by nanociaglia** [comment]
"AskPluginLoad" you should have another plugin with the same name inside sourcemod/plugins or sourcemod/plugins/ttt

**Comment by danielsartor** [comment]
Thanks. It was there from previous versions and tests.

I will test now.

**Comment by danielsartor** [comment]
Working.
