### ISSUE TITLE
Bug that allows the use of tasers before it's loaded

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#378]
The players in my server reported that if they drop the taser and pick it up again, they can use it before the loaded message.

![image](https://user-images.githubusercontent.com/1349833/47218264-89be6b80-d381-11e8-9559-7a0714256fa8.png)

**Comment by happymix** [comment]
yes

**Comment by danielsartor** [comment]
Not sure if this has to do with it

L 10/19/2018 - 14:48:14: [SM] Exception reported: Invalid timer handle 3cec0770 (error 1)
L 10/19/2018 - 14:48:14: [SM] Blaming: ttt/ttt_taser.smx
L 10/19/2018 - 14:48:14: [SM] Call stack trace:
L 10/19/2018 - 14:48:14: [SM]   [0] KillTimer
L 10/19/2018 - 14:48:14: [SM]   [1] Line 848, /home/travis/build/Bara/TroubleinTerroristTown/addons/sourcemod/scripting/include/ttt.inc::TTT_ClearTimer
L 10/19/2018 - 14:48:14: [SM]   [2] Line 183, addons/sourcemod/scripting/ttt/ttt_taser.sp::TTT_OnRoundStart
L 10/19/2018 - 14:48:14: [SM]   [4] Call_Finish
L 10/19/2018 - 14:48:14: [SM]   [5] Line 1191, addons/sourcemod/scripting/ttt/ttt.sp::Timer_Selection
