### ISSUE TITLE
Missile following player

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#382]
Missiles sometimes follow players and doesn't kill them but if the player touch other players they kill those players.

My staff didn't find a pattern to this issue, if I have more information I will post here.

Probably it has to do with it:
https://media.discordapp.net/attachments/425647919052488704/503738969679331339/unknown.png?width=949&height=683

**Comment by danielsartor** [comment]
https://media.discordapp.net/attachments/397887973825183755/504022004865826827/unknown.png?width=1013&height=684

**Comment by danielsartor** [comment]
Usually it keeps following the player when he is alone, but when there are more players together it explodes.

**Comment by Bara** [comment]
Noblock doesn't call StartTouch.
