### ISSUE TITLE
Spec Glitch/Bug

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#384]
> i can't spec other people, i think is glitched
> for example there're 30 people in the server but i can only spec 3 or 4 niggers
> using mouse1 and 2

**Comment by good-live** [comment]
Specmenu should help with this.

**Comment by Bara** [comment]
Should fixed with https://github.com/Bara/TroubleinTerroristTown/commit/77b887959f91e08f6595a594d1029cd75142544e
