### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by nanociaglia** [Bara/TroubleinTerroristTown#386]
https://crash.limetech.org/kjpl6h7cay24

https://crash.limetech.org/wffkmpyfn4g5

i've a lot of this crash issues on my Accelerator logs 
I posted them here cause is better than discord.
Not gonna use the TTT plugin anymore until it's fixed because those crash are very annoying

**Comment by Bara** [comment]
The crashes are unique. Are you pretty sure, that this comes from TTT? I never saw or heard of that kind of crashes from other communities.

**Comment by Bara** [comment]
Or other question: Did you update your server to a new version?

**Comment by nanociaglia** [comment]
i've the last version of everything in my server. I can give you access to the logs if you want
