### ISSUE TITLE
ttt_spec_menu Entity is invalid

### ISSUE THREAD

**Issue by Septembers** [Bara/TroubleinTerroristTown#389]
version 3.1986

L 11/05/2018 - 13:34:54: [SM] Exception reported: Entity 20 (20) is invalid
L 11/05/2018 - 13:34:54: [SM] Blaming: ttt/ttt_spec_menu.smx
L 11/05/2018 - 13:34:54: [SM] Call stack trace:
L 11/05/2018 - 13:34:54: [SM]   [0] SetEntPropEnt
L 11/05/2018 - 13:34:54: [SM]   [1] Line 177, addons/sourcemod/scripting/ttt/ttt_spec_menu.sp::Command_SpecPlayer

**Comment by Septembers** [comment]
Why in the last build the shop does not work after the end of the round?

sorry for my eng

**Comment by Septembers** [comment]
ok, sorry

**Comment by Septembers** [comment]
build 2006
L 11/27/2018 - 14:59:11: [SM] Exception reported: Entity 12 (12) is invalid
L 11/27/2018 - 14:59:11: [SM] Blaming: ttt/ttt_spec_menu.smx
L 11/27/2018 - 14:59:11: [SM] Call stack trace:
L 11/27/2018 - 14:59:11: [SM]   [0] SetEntPropEnt
L 11/27/2018 - 14:59:11: [SM]   [1] Line 182, addons/sourcemod/scripting/ttt/ttt_spec_menu.sp::Command_SpecPlayer

**Comment by nanociaglia** [comment]
This still happening:

L 12/04/2018 - 10:34:58: Info (map "ttt_minecraft_cg13") (file "errors_20181204.log")
L 12/04/2018 - 10:34:58: [SM] Exception reported: Array index out-of-bounds (index -2, limit 66)
L 12/04/2018 - 10:34:58: [SM] Blaming: ttt/ttt_spec_menu.smx
L 12/04/2018 - 10:34:58: [SM] Call stack trace:
L 12/04/2018 - 10:34:58: [SM]   [1] Line 466, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\ttt_spec_menu.sp::GetNextClient
L 12/04/2018 - 10:34:58: [SM]   [2] Line 147, C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\addons\sourcemod\scripting\ttt_spec_menu.sp::Command_SpecPrev

**Comment by Bara** [comment]
That's fixed in a privat version. Interested? Contact me in Steam or Discord for privat (free) support. 

I'm no longer interested in updating and fixing TTT.
