### ISSUE TITLE
can't pickup new items

### ISSUE THREAD

**Issue by e54385991** [Bara/TroubleinTerroristTown#397]
hammer / axe / spanner drop ground can't  picked up

**Comment by Bara** [comment]
That's the same issue with knife. In Danger Zone you can pick up the melee weapons, but not in other gamemodes.

**Comment by e54385991** [comment]
int c = GivePlayerItem(i,"weapon_axe");
					EquipPlayerWeapon(i,c);
it's possible

**Comment by Bara** [comment]
So just GivePlayerItem drops the weapon on ground? I just tested it with EquipPlayerWeapon ( https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/tests/commands.sp#L127-L131 ).

**Comment by e54385991** [comment]
Should

This can  spawn turret tested.must precache first.


public Action CMD_SpawnDroneGun(int client, int args)
{
	if(!IsClientInGame(client))
	{
		return Plugin_Handled;
	}
	
	int precache = PrecacheModel("models/props_survival/dronegun/dronegun.mdl", true);
	if (precache == 0) {
		return Plugin_Handled;
	}
	
	PrecacheModel("models/props_survival/dronegun/dronegun_gib1.mdl", true);
	PrecacheModel("models/props_survival/dronegun/dronegun_gib2.mdl", true);
	PrecacheModel("models/props_survival/dronegun/dronegun_gib3.mdl", true);
	PrecacheModel("models/props_survival/dronegun/dronegun_gib4.mdl", true);
	PrecacheModel("models/props_survival/dronegun/dronegun_gib5.mdl", true);
	PrecacheModel("models/props_survival/dronegun/dronegun_gib6.mdl", true);
	PrecacheModel("models/props_survival/dronegun/dronegun_gib7.mdl", true);
	PrecacheModel("models/props_survival/dronegun/dronegun_gib8.mdl", true);
	
	PrecacheSound("sound/survival/turret_death_01.wav", true);
	PrecacheSound("sound/survival/turret_idle_01.wav", true);
	
	PrecacheSound("sound/survival/turret_takesdamage_01.wav", true);
	PrecacheSound("sound/survival/turret_takesdamage_02.wav", true);
	PrecacheSound("sound/survival/turret_takesdamage_03.wav", true);
	
	PrecacheSound("sound/survival/turret_lostplayer_01.wav", true);
	PrecacheSound("sound/survival/turret_lostplayer_02.wav", true);
	PrecacheSound("sound/survival/turret_lostplayer_03.wav", true);
	
	PrecacheSound("sound/survival/turret_sawplayer_01.wav", true);
	

	
	float vec[2][3];
	GetClientEyePosition(client, vec[0]);
	GetClientEyeAngles(client, vec[1]);
	
	Handle trace = TR_TraceRayFilterEx(vec[0], vec[1], MASK_SOLID, RayType_Infinite, Filter_ExcludePlayers);
	if(!TR_DidHit(trace))
	{
		delete trace;
		return Plugin_Handled;
	}
	TR_GetEndPosition(vec[0], trace);
	delete (trace);
	
	int dronegun = CreateEntityByName("dronegun");
	if(dronegun == -1 || !IsValidEntity(dronegun))
	{
		//PrintToServer("dronegun %d",dronegun);
		return Plugin_Handled;
	}
	
	//PrintToServer("A dronegun %d",dronegun);
	
	
	vec[0][2] = vec[0][2] + 16.0;
	TeleportEntity(dronegun, vec[0], NULL_VECTOR, NULL_VECTOR);
	DispatchSpawn(dronegun);
	
	
	return Plugin_Handled;
}

**Comment by Bara** [comment]
How about to post that snippet [here for all](https://forums.alliedmods.net/forumdisplay.php?f=112)?
