### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Septembers** [Bara/TroubleinTerroristTown#398]
i use last build sourcemod and last version TTT 2031
The server crashes for unknown reasons.
The accelerator displays information that the TTT plugin is to blame and the function <<<ttt.smx::OnPlayerRunCmd>>>

error logs 

```
L 01/13/2019 - 17:39:29: [SM] Exception reported: Client index 0 is invalid
L 01/13/2019 - 17:39:29: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 17:39:29: [SM] Call stack trace:
L 01/13/2019 - 17:39:29: [SM]   [0] GetClientUserId
L 01/13/2019 - 17:39:29: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 17:39:29: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 17:39:29: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD

```

**Comment by Septembers** [comment]
The server crashes every 2-3 minutes.
There were 3 people on the server

**Comment by Septembers** [comment]
build  2024 - works fine
starting with build 2025-2031 crash every round

**Comment by Septembers** [comment]
version 2029 logs

``
L 01/13/2019 - 18:34:01: [SM] Exception reported: Invalid entity index -1
L 01/13/2019 - 18:34:01: [SM] Blaming: ttt/ttt_hurtshot.smx
L 01/13/2019 - 18:34:01: [SM] Call stack trace:
L 01/13/2019 - 18:34:01: [SM]   [0] EntIndexToEntRef
L 01/13/2019 - 18:34:01: [SM]   [1] Line 150, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::OnWeaponDrop
L 01/13/2019 - 18:34:01: [SM]   [3] ForcePlayerSuicide
L 01/13/2019 - 18:34:01: [SM]   [4] Line 42, csgo_teamlimits.sp::Command_JoinTeam
L 01/13/2019 - 18:34:39: [SM] Exception reported: Invalid entity index -1
L 01/13/2019 - 18:34:39: [SM] Blaming: ttt/ttt_hurtshot.smx
L 01/13/2019 - 18:34:39: [SM] Call stack trace:
L 01/13/2019 - 18:34:39: [SM]   [0] EntIndexToEntRef
L 01/13/2019 - 18:34:39: [SM]   [1] Line 150, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::OnWeaponDrop
L 01/13/2019 - 18:34:39: [SM] Exception reported: Client index 1702129765 is invalid
L 01/13/2019 - 18:34:39: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:34:39: [SM] Call stack trace:
L 01/13/2019 - 18:34:39: [SM]   [0] GetClientUserId
L 01/13/2019 - 18:34:39: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 18:34:39: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 18:34:39: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
L 01/13/2019 - 18:34:40: [SM] Exception reported: Client index 1702129765 is invalid
L 01/13/2019 - 18:34:40: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:34:40: [SM] Call stack trace:
L 01/13/2019 - 18:34:40: [SM]   [0] GetClientUserId
L 01/13/2019 - 18:34:40: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 18:34:40: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 18:34:40: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
L 01/13/2019 - 18:34:41: [SM] Exception reported: Client index 1702129765 is invalid
L 01/13/2019 - 18:34:41: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:34:41: [SM] Call stack trace:
L 01/13/2019 - 18:34:41: [SM]   [0] GetClientUserId
L 01/13/2019 - 18:34:41: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 18:34:41: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 18:34:41: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
L 01/13/2019 - 18:34:42: [SM] Exception reported: Client index 1702129765 is invalid
L 01/13/2019 - 18:34:42: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:34:42: [SM] Call stack trace:
L 01/13/2019 - 18:34:42: [SM]   [0] GetClientUserId
L 01/13/2019 - 18:34:42: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 18:34:42: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 18:34:42: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
L 01/13/2019 - 18:34:43: [SM] Exception reported: Client index 1702129765 is invalid
L 01/13/2019 - 18:34:43: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:34:43: [SM] Call stack trace:
L 01/13/2019 - 18:34:43: [SM]   [0] GetClientUserId
L 01/13/2019 - 18:34:43: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 18:34:43: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 18:34:43: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
L 01/13/2019 - 18:34:44: [SM] Exception reported: Client index 1702129765 is invalid
L 01/13/2019 - 18:34:45: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:34:45: [SM] Call stack trace:
L 01/13/2019 - 18:34:45: [SM]   [0] GetClientUserId
L 01/13/2019 - 18:34:45: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 18:34:45: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 18:34:45: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
L 01/13/2019 - 18:34:46: [SM] Exception reported: Client index 1702129765 is invalid
L 01/13/2019 - 18:34:46: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:34:46: [SM] Call stack trace:
L 01/13/2019 - 18:34:46: [SM]   [0] GetClientUserId
L 01/13/2019 - 18:34:46: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/13/2019 - 18:34:46: [SM]   [3] TTT_WasBodyFound
L 01/13/2019 - 18:34:46: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
L 01/13/2019 - 18:34:46: [SM] Exception reported: Invalid entity index -1
L 01/13/2019 - 18:34:46: [SM] Blaming: ttt/ttt_hurtshot.smx
L 01/13/2019 - 18:34:46: [SM] Call stack trace:
L 01/13/2019 - 18:34:46: [SM]   [0] EntIndexToEntRef
L 01/13/2019 - 18:34:46: [SM]   [1] Line 150, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::OnWeaponDrop
L 01/13/2019 - 18:35:17: [SM] Exception reported: Invalid entity index -1
L 01/13/2019 - 18:35:17: [SM] Blaming: ttt/ttt_hurtshot.smx
L 01/13/2019 - 18:35:17: [SM] Call stack trace:
L 01/13/2019 - 18:35:17: [SM]   [0] EntIndexToEntRef
L 01/13/2019 - 18:35:17: [SM]   [1] Line 150, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::OnWeaponDrop
L 01/13/2019 - 18:35:17: [SM] Exception reported: Invalid entity index -1
L 01/13/2019 - 18:35:17: [SM] Blaming: ttt/ttt_hurtshot.smx
L 01/13/2019 - 18:35:17: [SM] Call stack trace:
L 01/13/2019 - 18:35:17: [SM]   [0] EntIndexToEntRef
L 01/13/2019 - 18:35:17: [SM]   [1] Line 150, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::OnWeaponDrop
L 01/13/2019 - 18:35:20: [SM] Exception reported: Stack leak detected: sp:148500 should be 148492!
L 01/13/2019 - 18:35:20: [SM] Blaming: ttt/ttt.smx
L 01/13/2019 - 18:35:20: [SM] Call stack trace:
L 01/13/2019 - 18:35:20: [SM]   [0] Call_Finish
L 01/13/2019 - 18:35:20: [SM]   [1] Line 3361, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
``

**Comment by Septembers** [comment]
upd: server is absolutely no plugins, only TTT mod - crash

**Comment by quasemago** [comment]
Problem is https://github.com/Bara/TroubleinTerroristTown/commit/67442bed1478fc82c784e4f06b37d5ff3fda1b20 commit. Server crashs when found body.

**Comment by Bara** [comment]
If you've a crash, then you should install [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703) and provide us your latest crash id.

**Comment by Septembers** [comment]
> If you've a crash, then you should install [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703) and provide us your latest crash id.

https://throttle.zizt.ru

VQHB-ND45-3J63
OWSQ-GAQ6-QQA6
34HG-PMKI-WE32
QQ3J-FANJ-CQMZ
5TJA-RPVG-3JZ3
IZXG-DYEJ-TDKR
ZGBT-NRES-VPH5
ORVL-GWAZ-ALXA

**Comment by Bara** [comment]
Any reason why you don't use the public version?

**Comment by Septembers** [comment]
> Any reason why you don't use the public version?

This version is modified, and displays the latest plugin and function of the plug-in that was acquired during the crash. That is, in 80 percent of crashes, I see which plug-in is to blame.

Sorry for my English

**Comment by Septembers** [comment]
I installed the last build, the server crashes

```
L 01/20/2019 - 19:45:17: [SM] Exception reported: Invalid entity index -1
L 01/20/2019 - 19:45:17: [SM] Blaming: ttt/ttt_hurtshot.smx
L 01/20/2019 - 19:45:17: [SM] Call stack trace:
L 01/20/2019 - 19:45:17: [SM]   [0] EntIndexToEntRef
L 01/20/2019 - 19:45:17: [SM]   [1] Line 158, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::OnWeaponDrop
L 01/20/2019 - 19:45:17: [SM]   [3] ForcePlayerSuicide
L 01/20/2019 - 19:45:17: [SM]   [4] Line 42, csgo_teamlimits.sp::Command_JoinTeam
```

```
L 01/20/2019 - 19:44:22: [SM] Exception reported: Stack leak detected: sp:147836 should be 147820!
L 01/20/2019 - 19:44:22: [SM] Blaming: ttt/ttt.smx
L 01/20/2019 - 19:44:22: [SM] Call stack trace:
L 01/20/2019 - 19:44:22: [SM]   [0] Call_Finish
L 01/20/2019 - 19:44:22: [SM]   [1] Line 3361, addons/sourcemod/scripting/ttt/ttt.sp::OnPlayerRunCmd
```

```
L 01/20/2019 - 19:44:16: [SM] Exception reported: Client index 829645160 is invalid
L 01/20/2019 - 19:44:16: [SM] Blaming: ttt/ttt.smx
L 01/20/2019 - 19:44:16: [SM] Call stack trace:
L 01/20/2019 - 19:44:16: [SM]   [0] GetClientUserId
L 01/20/2019 - 19:44:16: [SM]   [1] Line 247, addons/sourcemod/scripting/ttt/core/natives.sp::Native_WasBodyFound
L 01/20/2019 - 19:44:16: [SM]   [3] TTT_WasBodyFound
L 01/20/2019 - 19:44:16: [SM]   [4] Line 325, addons/sourcemod/scripting/ttt/ttt_overlay.sp::Timer_HUD
```

**Comment by Bara** [comment]
Do you use an modified SM Version? I'm wondering that just you has the crash issue and error logs (except the hurtshot issue).

**Comment by Septembers** [comment]
> Do you use an modified SM Version? I'm wondering that just you has the crash issue and error logs (except the hurtshot issue).

no, standard sourcemod

```
 SourceMod Version Information:
    SourceMod Version: 1.9.0.6273
    SourcePawn Engine: 1.9.0.6275, jit-x86 (build 1.9.0.6275)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: Jan  1 2019 12:39:44
    Built from: https://github.com/alliedmodders/sourcemod/commit/95027e0
    Build ID: 6273:95027e0
    http://www.sourcemod.net/
```

**Comment by Septembers** [comment]
I kill a person from a distance - everything is ok.
I kill a man close, come up to his dead body - crash

**Comment by quasemago** [comment]
I am using the latest build and also had this problem, after reversing the commit change https://github.com/Bara/TroubleinTerroristTown/commit/67442bed1478fc82c784e4f06b37d5ff3fda1b20 the problem has been solved.

@Bara Do you know why the increase in blocksize causes this problem?

**Comment by Septembers** [comment]
> I am using the latest build and also had this problem, after reversing the commit change [67442be](https://github.com/Bara/TroubleinTerroristTown/commit/67442bed1478fc82c784e4f06b37d5ff3fda1b20) the problem has been solved.
> 
> @Bara Do you know why the increase in blocksize causes this problem?

thx man.
open ttt.sp
g_aRagdoll = new ArrayList(296);
=>
g_aRagdoll = new ArrayList(104);

work fine

**Comment by Bara** [comment]
But this will result is this: #396

**Comment by Septembers** [comment]
> But this will result in this: #396

everything is working fine for me

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/c457a13fca1f582bede0551e23db755d64a0955c
