### ISSUE TITLE
Night Vision not working

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#401]
Sourcemod: Build 6275
Metamod: Build 968
TTT: Build 2034

Player bought the item from the shop but nothing changed.

Is there a trigger to activate it or just buying?

**Comment by Mrkl21full** [comment]
Actually, yes.

If you bought this item you must write !nvg command in the chat.

**Comment by danielsartor** [comment]
I will ask them to test.

Sorry that I can't test or check that. I'm quite busy and I rely on my players to test and report ):.

**Comment by danielsartor** [comment]
Working.
