### ISSUE TITLE
Silecend AWP with full ammo.

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#402]
Sourcemod: Build 6275
Metamod: Build 968
TTT: Build 2034

If you have an AWP from the map or any AWP before buying the silenced AWP, you will get a silenced AWP with full ammo.

To fix I suggest to drop and destroy the current weapon before giving another one. (I can work on that if you want)

**Comment by Bara** [comment]
Primary weapon should already removed.

**Comment by Bara** [comment]
I've pushed an commit to change the ammo/clip without removing the awp.

**Comment by danielsartor** [comment]
I will update it. Thank you.

**Comment by danielsartor** [comment]
![image](https://user-images.githubusercontent.com/1349833/52080028-9c962e00-2575-11e9-80ac-ceaf446b6ba7.png)
It's in portuguese, but you can read that a Silenced AWP was bought and he doesn't have it equipped.

**Comment by danielsartor** [comment]
Also there are these errors:
`L 02/06/2019 - 14:39:47: [SM] Exception reported: This plugin use a different version as ttt.smx
L 02/06/2019 - 14:39:47: [SM] Blaming: ttt/ttt_silent_awp.smx
L 02/06/2019 - 14:39:47: [SM] Call stack trace:
L 02/06/2019 - 14:39:47: [SM]   [0] SetFailState
L 02/06/2019 - 14:39:47: [SM]   [1] Line 1105, /home/travis/build/Bara/TroubleinTerroristTown/addons/sourcemod/scripting/include/ttt.inc::TTT_CheckVersion
L 02/06/2019 - 14:39:47: [SM]   [2] Line 80, addons/sourcemod/scripting/ttt/ttt_silent_awp.sp::TTT_OnLatestVersion
L 02/06/2019 - 14:39:47: [SM]   [4] Call_Finish
L 02/06/2019 - 14:39:47: [SM]   [5] Line 103, addons/sourcemod/scripting/ttt/core/version.sp::OnHTTPCallback`

**Comment by Bara** [comment]
Looks like you updated just one smx and not all, but that's unrelated to this isuse.
