### ISSUE TITLE
bugs with 2070 build

### ISSUE THREAD

**Issue by Septembers** [Bara/TroubleinTerroristTown#412]
Vesion SM 1.9 6281
Version TTT - 2070

1.L 06/29/2019 - 16:49:00: [SM] Exception reported: Array index out-of-bounds (index -2, limit 66)
L 06/29/2019 - 16:49:00: [SM] Blaming: ttt/ttt_spec_menu.smx
L 06/29/2019 - 16:49:00: [SM] Call stack trace:
L 06/29/2019 - 16:49:00: [SM]   [1] Line 466, addons/sourcemod/scripting/ttt/ttt_spec_menu.sp::GetNextClient
L 06/29/2019 - 16:49:00: [SM]   [2] Line 147, addons/sourcemod/scripting/ttt/ttt_spec_menu.sp::Command_SpecPrev

2. L 06/29/2019 - 16:37:59: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 06/29/2019 - 16:37:59: [SM] Blaming: ttt/ttt_knockout.smx
L 06/29/2019 - 16:37:59: [SM] Call stack trace:
L 06/29/2019 - 16:37:59: [SM]   [0] ConVar.BoolValue.get
L 06/29/2019 - 16:37:59: [SM]   [1] Line 383, addons/sourcemod/scripting/ttt/ttt_knockout.sp::Timer_Delete

3. L 06/29/2019 - 16:31:17: [SM] Exception reported: Weapon 110 is not owned by client 2
L 06/29/2019 - 16:31:17: [SM] Blaming: ttt/ttt_hurtshot.smx
L 06/29/2019 - 16:31:17: [SM] Call stack trace:
L 06/29/2019 - 16:31:17: [SM]   [0] CS_DropWeapon
L 06/29/2019 - 16:31:17: [SM]   [1] Line 231, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::TTT_OnItemPurchased
L 06/29/2019 - 16:31:17: [SM]   [3] Call_Finish
L 06/29/2019 - 16:31:17: [SM]   [4] Line 707, addons/sourcemod/scripting/ttt/ttt_shop.sp::ClientBuyItem
L 06/29/2019 - 16:31:17: [SM]   [5] Line 646, addons/sourcemod/scripting/ttt/ttt_shop.sp::Menu_ShopHandler

4. Bug from players: the function "Kill or forgive for pdm" does not work properly. I explain - after a player has forgiven or killed for RDM, then at the last second, when roles are issued, this player dies (kills him), and the round restarts.

sorry for my eng

5. L 06/29/2019 - 16:24:52: [SM] Exception reported: Entity 5 (5) is invalid
L 06/29/2019 - 16:24:52: [SM] Blaming: ttt/ttt_exojump.smx
L 06/29/2019 - 16:24:52: [SM] Call stack trace:
L 06/29/2019 - 16:24:52: [SM]   [0] SetEntProp
L 06/29/2019 - 16:24:52: [SM]   [1] Line 101, addons/sourcemod/scripting/ttt/ttt_exojump.sp::SetClientExojump
L 06/29/2019 - 16:24:52: [SM]   [2] Line 91, addons/sourcemod/scripting/ttt/ttt_exojump.sp::ResetExojump
L 06/29/2019 - 16:24:52: [SM]   [3] Line 59, addons/sourcemod/scripting/ttt/ttt_exojump.sp::OnClientDisconnect

6. L 06/29/2019 - 16:22:06: [SM] Exception reported: Weapon 154 is not owned by client 2
L 06/29/2019 - 16:22:06: [SM] Blaming: ttt/ttt_hurtshot.smx
L 06/29/2019 - 16:22:06: [SM] Call stack trace:
L 06/29/2019 - 16:22:06: [SM]   [0] CS_DropWeapon
L 06/29/2019 - 16:22:06: [SM]   [1] Line 231, addons/sourcemod/scripting/ttt/ttt_hurtshot.sp::TTT_OnItemPurchased
L 06/29/2019 - 16:22:06: [SM]   [3] Call_Finish
L 06/29/2019 - 16:22:06: [SM]   [4] Line 707, addons/sourcemod/scripting/ttt/ttt_shop.sp::ClientBuyItem
L 06/29/2019 - 16:22:06: [SM]   [5] Line 646, addons/sourcemod/scripting/ttt/ttt_shop.sp::Menu_ShopHandler

**Comment by Septembers** [comment]
Another bug. Detective can hear the lost players.
How to do it: The player must die and go to the "ct" side, in turn, another player must buy a detective role in this round
 
and they hear each other

**Comment by Bara** [comment]
1 Issue, 1 Bug.
