### ISSUE TITLE
Detective can hear the dead players

### ISSUE THREAD

**Issue by Septembers** [Bara/TroubleinTerroristTown#415]
Vesion SM 1.9 6281
Version TTT - 2070

Another bug. Detective can hear the dead players.
How to do it: The player must die and go to the "ct" side, in turn, another player must buy a detective role in this round and they hear each other

**Comment by Bara** [comment]
Try again with this commit: https://github.com/Bara/TroubleinTerroristTown/commit/1e039eeb71fb366f2fe6f0e216448538d6c5ecd7
