### ISSUE TITLE
Respaw after round start

### ISSUE THREAD

**Issue by guilhermexx9** [Bara/TroubleinTerroristTown#417]
Sourcemod: 1.9 Stable
Metamod: 1.10
TTT: Build 2071

![bug ttt](https://user-images.githubusercontent.com/52174388/60529989-32251d80-9cce-11e9-8b86-76fa4e7331bf.png)

Players can enter after the round start (respawn), but without a role. How to fix this?
They use the "retry" command on the console, to join and respawn when they die.

**Comment by Bara** [comment]
Set `ttt_slay_after_start` to `1`. If it doesn't help reopen this issue.
