### ISSUE TITLE
Bug with voice chat

### ISSUE THREAD

**Issue by Septembers** [Bara/TroubleinTerroristTown#418]
Vesion SM 1.9 6281
Version TTT - 2077

The bug is associated with voice chat.
If you punish a player for RDM (a traitor killed a traitor or a detective killed a detective), then the player will die 5 rounds. As he dies, all living things will hear him.

Maybe I have a problem with some cvar?
A similar problem is here https://github.com/Bara/TroubleinTerroristTown/issues/415

**Comment by Bara** [comment]
https://github.com/Bara/TroubleinTerroristTown/commit/e17579401c0f69ae121b99aae74ef1a37e6f6450
https://github.com/Bara/TroubleinTerroristTown/commit/d220ef3add09a3bfa93fb18da23cf4f408353fc4
should be fixed with 2073.

**Comment by Septembers** [comment]
Not. Players complain massively about this bug. Installed version 3.2077

> [e175794](https://github.com/Bara/TroubleinTerroristTown/commit/e17579401c0f69ae121b99aae74ef1a37e6f6450)
> [d220ef3](https://github.com/Bara/TroubleinTerroristTown/commit/d220ef3add09a3bfa93fb18da23cf4f408353fc4)
> should be fixed with 2073.

**Comment by Septembers** [comment]
Any thoughts?

**Comment by Bara** [comment]
Not yet, no time for this.
