### ISSUE TITLE
Small things that could possibly be fixed to fine-tune the gamemode

### ISSUE THREAD

**Issue by Tashboss** [Bara/TroubleinTerroristTown#422]
Hi I just wanted to write to you to see if you could change a few small things in the game that'll make the gamemode better. No mass coding will need to be done just small minor adjustments.

Fix the issue with dead bodies being id'd when the dead player leaves the game. For e.g. There were three people left on the leaderboard, One was a T, One was an inno and one was a dead inno (unid'd). If the dead inno leaves the game fully, then the body becomes id'd on the leaderboard so it allows the inno to call KOS on T. 

Implement a !checktick command (from !timeleft) which tells you the current tick of the map you are playing in. This makes it easier to log rdms or anything you would like to check later on. It is also easier than re watching the entire demo.

Re-order the T shop efficiently so that more important things are in the first page (Health-shot is last page come on). Things that could be put in the first/second page are: Health shot, taser, tracer (radar), one-hit knife, teleporter, usps, m4a1s, silenced awp.

Fix the decoy teleporter. It comes up with a 'stuck problem' everytime when I have thrown in. I'm not sure if I am throwing it wrong but it hasnt worked for me ever.

Tasers bought as innocents should be kept if they stay alive for the next round similar to how a healthshot stays with you on round restarts if you previously bought one but havent used it.

**Comment by Bara** [comment]
It would be much easier to split this into multiple issues (one suggestion/report per issue). Otherwise it's too much for all in one person issue.

**Comment by Tashboss** [comment]
> 
> 
> It would be much easier to split this into multiple issues (one suggestion/report per issue). Otherwise it's too much for all in one person issue.

I have created seperate issue threads for the multiple problems
