### ISSUE TITLE
Dead unid'd bodies being auto-id'd upon leaving

### ISSUE THREAD

**Issue by Tashboss** [Bara/TroubleinTerroristTown#423]
Fix the issue with dead bodies being id'd when the dead player leaves the game. For e.g. There were three people left on the leaderboard, One was a T, One was an inno and one was a dead inno (unid'd). If the dead inno leaves the game fully, then the body becomes id'd on the leaderboard so it allows the inno to call KOS on T.

**Comment by Bara** [comment]
I'll check it if I found a bit time for this.

**Comment by Tashboss** [comment]
Ok thank you

**Comment by Tashboss** [comment]
Any way to fix this?

**Comment by Bara** [comment]
Can you try it with the latest build (2140+)?

**Comment by Tashboss** [comment]
> 
> 
> Can you try it with the latest build (2140+)?

I do not know the build version of the server I play on. I will let them know but it may take some time. I will mark it as solved for now as it is not that big of an issue.
