### ISSUE TITLE
Implementing a !checktick command

### ISSUE THREAD

**Issue by Tashboss** [Bara/TroubleinTerroristTown#424]
Implement a !checktick command (from !timeleft) which tells you the current tick of the map you are playing in. This makes it easier to log rdms or anything you would like to check later on. It is also easier than re watching the entire demo.

**Comment by Bara** [comment]
Possible with SourceTVManager: https://forums.alliedmods.net/showthread.php?t=280402
I think it's not necessary to add this into ttt. I could provide an simple sp file with !tick as command.
