### ISSUE TITLE
Re-order t shop items

### ISSUE THREAD

**Issue by Tashboss** [Bara/TroubleinTerroristTown#425]
Re-order the T shop efficiently so that more important things are in the first page (Health-shot is last page come on). Things that could be put in the first/second page are: Health shot, taser, tracer (radar), one-hit knife, teleporter, usps, m4a1s, silenced awp.

**Comment by Bara** [comment]
You can do it with the items config, every item should have a convar for this. Take a look at your config files (cfg/ttt).
