### ISSUE TITLE
tasers kept on round restart 

### ISSUE THREAD

**Issue by Tashboss** [Bara/TroubleinTerroristTown#426]
Tasers bought as innocents should be kept if they stay alive for the next round similar to how a healthshot stays with you on round restarts if you previously bought one but havent used it.

They are pretty expensive to buy being 3k credits for innocents which makes it more expensive than healthshots.

**Comment by Mrkl21full** [comment]
I added a pull request for your issue.

After Bara check that you should be able to use that.

**Comment by Bara** [comment]
I would prefer to remove every item, since you don't know which role you get next round. It could be funny, but instead items next round, i don't know especially Detective Item as Traitor or T Item as Detective.

With a convar to remove that item or not would an option.
