### ISSUE TITLE
Bug at random teleporter

### ISSUE THREAD

**Issue by TRONZINHO** [Bara/TroubleinTerroristTown#430]
**TRAITOR** can change her position with a **SPECTATOR** when he got **RANDOM TELEPORT** in shop.
![Screenshot_71](https://user-images.githubusercontent.com/52174388/66263827-8f4dd500-e7cf-11e9-865e-45aff198bdcb.png)

**Comment by Bara** [comment]
And it doesn't exist any ragdoll from this player?

**Comment by TRONZINHO** [comment]
Nope

**Comment by Bara** [comment]
Can you test it again with the latest build (2138+)?

**Comment by TRONZINHO** [comment]
Yeap, i will

**Comment by TRONZINHO** [comment]
Now its fixed, thank you for all <3
