### ISSUE TITLE
Reset Karma after map change 

### ISSUE THREAD

**Issue by xFlume** [Bara/TroubleinTerroristTown#437]
Reset Karma after map change for everyone could i got guide how to do that ?

**Comment by jnatalejr** [comment]
Ideally you'd want to wait for a map change and set peoples' karma to the default using TTT_SetClientKarma. Don't quote me on that, but it's a start.

https://github.com/Bara/TroubleinTerroristTown/blob/9812536bf2a1b41f8c04ef49a12a7c88d320c451/addons/sourcemod/scripting/include/ttt.inc#L318

**Comment by Bara** [comment]
I'll don't add more feature to TTT anymore, it's limited to bug fixes only. #391 

But requests are still welcome, if they are useful.
