### ISSUE TITLE
Discord Logs 

### ISSUE THREAD

**Issue by xFlume** [Bara/TroubleinTerroristTown#440]
hey i connect my bot in the cfg files and put the smx in files but when i am starting the server and write in console sm plugins list its give me this error : 
ttt\ttt_discord.smx (Trouble in Terrorist Town - Discord): Native "DiscordBot.GetGuilds" was not found

**Comment by Bara** [comment]
I updated the discord includes, but based on the changes it shouldn't fix the issue.

**Comment by xFlume** [comment]
can i get the download of the updates ?

**Comment by Bara** [comment]
You can find every build/update on https://csgottt.com/ for SourceMod 1.9, 1.10 and since today 1.11.

**Comment by xFlume** [comment]
i did updated the 1.9 version and the discord bot still not working
i still got this error
ttt\ttt_discord.smx (Trouble in Terrorist Town - Discord): Native "DiscordBot.GetGuilds" was not found

**Comment by Bara** [comment]
Try this version
[discord_api.zip](https://github.com/Bara/TroubleinTerroristTown/files/3746671/discord_api.zip)

**Comment by xFlume** [comment]
ok, i will check that

**Comment by xFlume** [comment]
thank you very much its works.

**Comment by Bara** [comment]
The `discord_api.smx` is now included in ttt build package. **Attention**: To avoid conflicts, the `Discord.cfg` must be located in `addons/sourcemod/configs/ttt` now.
