### ISSUE TITLE
Revive don't work

### ISSUE THREAD

**Issue by Raku17** [Bara/TroubleinTerroristTown#441]
- Version of MetaMod  (meta version)
Metamod:Source version 1.10.7-dev

- Version of SourceMod (sm version)
SourceMod Version: 1.9.0.6282

- List of your extensions (sm exts list)
[SM] Displaying 16 extensions:
[01] Automatic Updater (1.9.0.6282): Updates SourceMod gamedata files
[02] Webternet (1.9.0.6282): Extension for interacting with URLs
[03] CS Tools (1.9.0.6282): CS extended functionality
[04] BinTools (1.9.0.6282): Low-level C/C++ Calling API
[05] SDK Tools (1.9.0.6282): Source SDK Tools
[06] Regex (1.9.0.6282): Provides regex natives for plugins
[07] SDK Hooks (1.9.0.6282): Source SDK Hooks
[08] Top Menus (1.9.0.6282): Creates sorted nested menus
[09] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[10] Client Preferences (1.9.0.6282): Saves client preference settings
[11] SQLite (1.9.0.6282): SQLite Driver
[12] GeoIP (1.9.0.6282): Geographical IP information
[13] DHooks (2.2.0-detours9): Dynamic Hooks
[14] SMJansson (2.3.1/3): JSON parser/writer
[15] System2 (3.2.1): HTTP/FTP Request and System API for Sourcemod
[16] MySQL-DBI (1.9.0.6282): MySQL driver implementation for DBI

- Version of TTT (sm_tttversion)
TTT Version: 3.2126

- List of your plugins (sm plugins list)

[SM] Listing 94 plugins:
01 "SM Fortnite Emotes Extended" (1.2.2) by Kodua, Franc1sco franug, TheBO$$
02 "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith Warren (Shaders Allen)
03 "SourceBans++: SourceSleuth" (1.6.3) by ecca, SourceBans++ Dev Team
04 "Basic Commands" (1.9.0.6282) by AlliedModders LLC
05 "Chat-Processor" (2.1.5) by Keith Warren (Drixevel)
06 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
07 "Block messages" (1.0.0) by Bara
08 "[PluginySM] Wygenerowany VIP" (1.0.0) by Bioly / Roberrt
09 "Admin Help" (1.9.0.6282) by AlliedModders LLC
10 "Basic Info Triggers" (1.9.0.6282) by AlliedModders LLC
11 "Trouble in Terrorist Town - Hide Radar" (3.2126) by TTT-Contributors
12 "Trouble in Terrorist Town - Dna Scanner" (3.2126) by TTT-Contributors
13 "Trouble in Terrorist Town - Spec Menu" (3.2126) by TTT-Contributors
14 "Trouble in Terrorist Town - Fake Name" (3.2126) by TTT-Contributors
15 "Trouble in Terrorist Town - Nightvision" (3.2126) by TTT-Contributors
16 "Trouble in Terrorist Town - Blackout" (3.2126) by TTT-Contributors
17 "Trouble in Terrorist Town - Glow" (3.2126) by TTT-Contributors
18 "Trouble in Terrorist Town - Knockout" (3.2126) by TTT-Contributors
19 "Trouble in Terrorist Town - Sprint" (3.2126) by TTT-Contributors
20 "Trouble in Terrorist Town - Items: Revive" (3.2126) by TTT-Contributors
21 "Trouble in Terrorist Town" (3.2126) by TTT-Contributors
22 "Trouble in Terrorist Town - Traitor Doors" (3.2126) by TTT-Contributors
23 "Trouble in Terrorist Town - Shop Discounts" (3.2126) by TTT-Contributors
24 "Trouble in Terrorist Town - Revolver" (3.2126) by TTT-Contributors
25 "Trouble in Terrorist Town - Poison Smoke" (3.2126) by TTT-Contributors
26 "Trouble in Terrorist Town - Turret" (3.2126) by TTT-Contributors & bbs.93x.net
27 "Trouble in Terrorist Town - Round End Sounds" (3.2126) by TTT-Contributors
28 "Trouble in Terrorist Town - Items: Ice Knife" (3.2126) by TTT-Contributors
29 "Trouble in Terrorist Town - Grabber Mod" (3.2126) by TTT-Contributors
30 "Trouble in Terrorist Town - Silent AWP" (3.2126) by TTT-Contributors
31 "Trouble in Terrorist Town - Overlays" (3.2126) by TTT-Contributors
32 "Trouble in Terrorist Town - Tracer" (3.2126) by bbs.93x.net & zipcore
33 "Trouble in Terrorist Town - SQL Manager" (3.2126) by TTT-Contributors
34 "Trouble in Terrorist Town - Items: Weapons" (3.2126) by TTT-Contributors
35 "Trouble in Terrorist Town - TA-Grenade" (3.2126) by TTT-Contributors
36 "Trouble in Terrorist Town - Items: ID" (3.2126) by TTT-Contributors
37 "Trouble in Terrorist Town - Items: Decoy Teleporter" (3.2126) by TTT-Contributors
38 "Trouble in Terrorist Town - Buy Roles" (3.2126) by TTT-Contributors
39 "Trouble in Terrorist Town - Crash Catcher" (3.2126) by TTT-Contributors
40 "Trouble in Terrorist Town - Decoy Body" (3.2126) by TTT-Contributors
41 "Trouble in Terrorist Town - Hurtshot" (3.2126) by TTT-Contributors
42 "Trouble in Terrorist Town - Teleporter" (3.2126) by TTT-Contributors
43 "Trouble in Terrorist Town - Items: Fake Body" (3.2126) by TTT-Contributors
44 "Trouble in Terrorist Town - Hud" (3.2126) by TTT-Contributors
45 "Trouble in Terrorist Town - Health/Hurt Stations" (3.2126) by TTT-Contributors
46 "Trouble in Terrorist Town - Traitor Buttons" (3.2126) by TTT-Contributors
47 "Trouble in Terrorist Town - Items: Healthshot" (3.2126) by TTT-Contributors
48 "Trouble in Terrorist Town - Tripmines" (3.2126) by TTT-Contributors
49 "Trouble in Terrorist Town - Drop Weapons" (3.2126) by TTT-Contributors
50 "Trouble in Terrorist Town - Icons" (3.2126) by TTT-Contributors
51 "Trouble in Terrorist Town - Items: Wallhack" (3.2126) by TTT-Contributors
52 "Trouble in Terrorist Town - Items: Martydom" (3.2126) by TTT-Contributors
53 "Trouble in Terrorist Town - C4 & Jihad" (3.2126) by TTT-Contributors
54 "Trouble in Terrorist Town - Radar" (3.2126) by TTT-Contributors
55 "Trouble in Terrorist Town - Items: Random Teleporter" (3.2126) by TTT-Contributors
56 "Trouble in Terrorist Town - Models" (3.2126) by TTT-Contributors
57 "Trouble in Terrorist Town - Shop" (3.2126) by TTT-Contributors
58 "Trouble in Terrorist Town - Exojump" (3.2126) by TTT-Contributors
59 "Trouble in Terrorist Town - Items: Taser" (3.2126) by TTT-Contributors
60 "Trouble in Terrorist Town - Bullets (Fire, Freeze, Poison)" (3.2126) by TTT-Contributors
61 "Trouble in Terrorist Town - Radio" (3.2126) by TTT-Contributors
62 "Trouble in Terrorist Town - Items: Missiles" (good_live) by TTT-Contributors
63 "Trouble in Terrorist Town - Talk Override" (3.2126) by TTT-Contributors
64 "CS:GO Turret Core" (1.0) by Tast - SDC Edited by Kento & e54385991
65 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
66 "hextags" (1.47) by Hexah
67 "ServerAdvertisements3" (3.1.3) by ESK0
68 "Fun Votes" (1.9.0.6282) by AlliedModders LLC
69 "Advanced Parachute" (1.0) by ESK0
70 "Reserved Slots" (1.9.0.6282) by AlliedModders LLC
71 "Admin File Reader" (1.9.0.6282) by AlliedModders LLC
72 "Useful commands" (4.2) by Eyal282
73 "No Weapon Fix" (3.2) by .#Zipcore
74 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
75 "Basic Comm Control" (1.9.0.6282) by AlliedModders LLC
76 "Player Commands" (1.9.0.6282) by AlliedModders LLC
77 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
78 "VoiceAnnounceEx" (2.2.0) by Franc1sco franug, Mini and GoD-Tony
79 "Anti-Flood" (1.9.0.6282) by AlliedModders LLC
80 "Opis" (1.0) by xBBBay
81 "Fun Commands" (1.9.0.6282) by AlliedModders LLC
82 "Nextmap" (1.9.0.6282) by AlliedModders LLC
83 "Sound Commands" (1.9.0.6282) by AlliedModders LLC
84 "Basic Votes" (1.9.0.6282) by AlliedModders LLC
85 "Menu" (1.0) by Raa
86 "Basic Chat" (1.9.0.6282) by AlliedModders LLC
87 "Client Preferences" (1.9.0.6282) by AlliedModders LLC
88 "[Roberrt] Automatyczny Sklep Usług [#GSHOP]" (IMPORTANT! DEBUG VERSION) by Roberrt..
89 "Tripmines 2016 Update" (1.0 ( will be never updated :) )) by 404, Bara
90 "SM Speaker Icon" (2.1) by Franc1sco steam: franug
91 "SM Most Active" (2.6) by Franc1sco Steam: franug / shanapu
92 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
93 "Admin Menu" (1.9.0.6282) by AlliedModders LLC
94 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team

- TTT related error logs - You can find the logs under: addons/sourcemod/logs/error_*.log
----
- Steps to reproduce this issue
Item Revive don't work
Revive: When i buy revive i see on chat that my friend has xx seconds to accept revive request, but he dont have any menu to accept

**Comment by Bara** [comment]
I pushed an update with a debug message. Try that version and share the chat result, if you see this message `[Revive] Something went wrong here. (g_bHasRevive: X, g_bWait: X)`. If you don't see that message, let me know.

**Comment by Raku17** [comment]
Okay i tested it.
- i dont see "[Revive] Something went wrong here. (g_bHasRevive: X, g_bWait: X)."
- On chat i see that i will revive him.
- He see that he can accept revive request in 5 seconds.
- if i press E on him once, i see in top left corner "Reviving xxx... 0.0%" but disappear when i stop presssing E
- i can tell you more, but i dont know what you want, i have no error logs
btw. when i plant C4 as a traitor, nobody can defuse it, or i just don't know how it works 

(https://user-images.githubusercontent.com/24883069/67227742-1dfd5b80-f438-11e9-80d5-cd73f91d217e.png)

**Comment by Bara** [comment]
Create new issues for the other reports.

**Comment by Raku17** [comment]
Okay, but what about this issue?

**Comment by Bara** [comment]
I'll take a look when I have time.

**Comment by Raku17** [comment]
Okay, thank you very much!
btw. your plugin is awesome i used it 2 years ago

**Comment by Bara** [comment]
Can you try the latest build (2134+), if it's done?

**Comment by Raku17** [comment]
No, same as before

**Comment by Bara** [comment]
Try this change, otherwise I'll test it tomorrow on my test server.

**Comment by Raku17** [comment]
Nope ;/ Same as before

**Comment by Bara** [comment]
If it still happen, feel free to reopen the issue. On my test server it works fine now.
