### ISSUE TITLE
MySQL not working

### ISSUE THREAD

**Issue by Toby-TFrag** [Bara/TroubleinTerroristTown#442]
MetaMod 1.10
SM 1.10
EXTS: https://pastebin.com/mH90Urdu
TTT Version: 3.2132
Plugins: https://pastebin.com/9xSySdDh
Error log: https://pastebin.com/rtP2vLyK

**MySQL not working**

I´ve successfully made it sync with my database, and the karma and credits is loaded in it. But whenever i change map, the players still start with 800 credits and 100 karma - almost like it doesn't download from my database. Any idea to why?

Pictures: 
[![Screenshot from Gyazo](https://gyazo.com/512b48960b059747f5b0beef6b6a4e3f/raw)](https://gyazo.com/512b48960b059747f5b0beef6b6a4e3f)

[![Screenshot from Gyazo](https://gyazo.com/c77426a74954af218e6eef3d56818153/raw)](https://gyazo.com/c77426a74954af218e6eef3d56818153)

[![Screenshot from Gyazo](https://gyazo.com/961f336d98133bc00698a6e52aadbd46/raw)](https://gyazo.com/961f336d98133bc00698a6e52aadbd46)

**Comment by Bara** [comment]
It would helpful if you post the related log which you can find here: `addons/sourcemod/logs/ttt/ttt-karma-*.log`

And if you want credits over mysql you need to change `ttt_sql_credits` to `1`.

**Comment by Toby-TFrag** [comment]
Worked, ty!
