### ISSUE TITLE
Inifinity test body 

### ISSUE THREAD

**Issue by TRONZINHO** [Bara/TroubleinTerroristTown#445]
We can test those body infinity times 
https://cdn.discordapp.com/attachments/618242555586412545/639502451174539274/unknown.png

This was start to happen after 2138 version

- **Version of MetaMod:**  1.10 Stable
- **Version of SourceMod:** 1.10 Stable
- **Version of TTT:** TTT Version: 3.2140

**Comment by Bara** [comment]
If it still happens, let me know or reopen this issue.

**Comment by TRONZINHO** [comment]
https://media.discordapp.net/attachments/594995140238508063/639608355945447469/Captura_de_tela_2019-10-31_17-34-24.png?width=1202&height=677

Still happens :(

- **Version of TTT:** TTT Version: 3.2143

**Comment by Bara** [comment]
I tested it successfully with build 2142 on sourcemod 1.10 build 6453.

**Comment by Raku17** [comment]
Any solution to this Bug?

**Comment by Bara** [comment]
Not yet.

**Comment by TRONZINHO** [comment]
I got the last version of the plugin ttt at csgottt.com and Using SM 1.10 (stable), so still working.

**Comment by TRONZINHO** [comment]
Sry, the last version of 1.09 Stable at csgottt.com

**Comment by Bara** [comment]
I'll try to take look tomorrow with a workaround.

**Comment by ClydeSheldon** [comment]
When I compiled TTT today I got 9 warnings for "warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs". I believe this is related to this issue.

[https://pastebin.com/sh3QcszK](https://pastebin.com/sh3QcszK)
[https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs](https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs)

**Comment by TRONZINHO** [comment]
@ClydeSheldon Try to use the newest includes
