### ISSUE TITLE
ghost with glow when use taser

### ISSUE THREAD

**Issue by Raku17** [Bara/TroubleinTerroristTown#446]
- Version of MetaMod  (meta version)
Metamod:Source version 1.10.7-dev

- Version of SourceMod (sm version)
SourceMod Version: 1.10.0.6453

- List of your extensions (sm exts list)

[SM] Displaying 21 extensions:
[01] Automatic Updater (1.10.0.6453): Updates SourceMod gamedata files
[02] Webternet (1.10.0.6453): Extension for interacting with URLs
[03] CS Tools (1.10.0.6453): CS extended functionality
[04] BinTools (1.10.0.6453): Low-level C/C++ Calling API
[05] SDK Tools (1.10.0.6453): Source SDK Tools
[06] Regex (1.10.0.6453): Provides regex natives for plugins
[07] SDK Hooks (1.10.0.6453): Source SDK Hooks
[08] Top Menus (1.10.0.6453): Creates sorted nested menus
[09] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[10] Client Preferences (1.10.0.6453): Saves client preference settings
[11] SQLite (1.10.0.6453): SQLite Driver
[12] <OPTIONAL> file "vphysics.ext.so": /home/container/csgo/addons/sourcemod/extensions/vphysics.ext.so: cannot open shared object file: No such file or directory
[13] GeoIP (1.10.0.6453): Geographical IP information
[14] PTaH (1.1.1): Additional CS:GO Hooks and Natives
[15] <OPTIONAL> file "steamtools.ext.so": /home/container/csgo/addons/sourcemod/extensions/steamtools.ext.so: cannot open shared object file: No such file or directory
[16] <OPTIONAL> file "curl.ext.so": /home/container/csgo/addons/sourcemod/extensions/curl.ext.so: cannot open shared object file: No such file or directory
[17] <OPTIONAL> file "socket.ext.so": /home/container/csgo/addons/sourcemod/extensions/socket.ext.so: cannot open shared object file: No such file or directory
[18] DHooks (2.2.0): Dynamic Hooks
[19] SMJansson (2.3.1/3): JSON parser/writer
[20] System2 (3.2.1): HTTP/FTP Request and System API for Sourcemod
[21] MySQL-DBI (1.10.0.6453): MySQL driver implementation for DBI

- Version of TTT (sm_tttversion)
TTT Version: 3.2143

- List of your plugins (sm plugins list)

[SM] Listing 97 plugins:
01 "Komendy" by Raa
02 "SM Fortnite Emotes Extended" (1.2.2) by Kodua, Franc1sco franug, TheBO$$
03 "SourceBans++: SourceSleuth" (1.6.3) by ecca, SourceBans++ Dev Team
04 "Basic Commands" (1.10.0.6453) by AlliedModders LLC
05 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
06 "Block messages" (1.0.0) by Bara
07 "Admin Help" (1.10.0.6453) by AlliedModders LLC
08 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
09 "Basic Info Triggers" (1.10.0.6453) by AlliedModders LLC
10 "SM Parachute" (2.5) by SWAT_88
11 "Trouble in Terrorist Town - Hide Radar" (3.2143) by TTT-Contributors
12 "Trouble in Terrorist Town - Dna Scanner" (3.2143) by TTT-Contributors
13 "Trouble in Terrorist Town - Spec Menu" (3.2143) by TTT-Contributors
14 "Trouble in Terrorist Town - Fake Name" (3.2143) by TTT-Contributors
15 "Trouble in Terrorist Town - Nightvision" (3.2143) by TTT-Contributors
16 "Trouble in Terrorist Town - Blackout" (3.2143) by TTT-Contributors
17 "Trouble in Terrorist Town - Glow" (3.2143) by TTT-Contributors
18 "Trouble in Terrorist Town - Knockout" (3.2143) by TTT-Contributors
19 "Trouble in Terrorist Town - Sprint" (3.2143) by TTT-Contributors
20 "Trouble in Terrorist Town - Items: Revive" (3.2143) by TTT-Contributors
21 "Trouble in Terrorist Town" (3.2143) by TTT-Contributors
22 "Trouble in Terrorist Town - Traitor Doors" (3.2143) by TTT-Contributors
23 "Trouble in Terrorist Town - Shop Discounts" (3.2143) by TTT-Contributors
24 "Trouble in Terrorist Town - Revolver" (3.2143) by TTT-Contributors
25 "Trouble in Terrorist Town - Poison Smoke" (3.2143) by TTT-Contributors
26 "Trouble in Terrorist Town - Turret" (3.2143) by TTT-Contributors & bbs.93x.net
27 "Trouble in Terrorist Town - Round End Sounds" (3.2143) by TTT-Contributors
28 "Trouble in Terrorist Town - Items: Ice Knife" (3.2143) by TTT-Contributors
29 "Trouble in Terrorist Town - Grabber Mod" (3.2143) by TTT-Contributors
30 "Trouble in Terrorist Town - Silent AWP" (3.2143) by TTT-Contributors
31 "Trouble in Terrorist Town - Overlays" (3.2143) by TTT-Contributors
32 "Trouble in Terrorist Town - Tracer" (3.2143) by bbs.93x.net & zipcore
33 "Trouble in Terrorist Town - SQL Manager" (3.2143) by TTT-Contributors
34 "Trouble in Terrorist Town - Items: Weapons" (3.2143) by TTT-Contributors
35 "Trouble in Terrorist Town - TA-Grenade" (3.2143) by TTT-Contributors
36 "Trouble in Terrorist Town - Items: ID" (3.2143) by TTT-Contributors
37 "Trouble in Terrorist Town - Items: Decoy Teleporter" (3.2143) by TTT-Contributors
38 "Trouble in Terrorist Town - Buy Roles" (3.2143) by TTT-Contributors
39 "Trouble in Terrorist Town - Crash Catcher" (3.2143) by TTT-Contributors
40 "Trouble in Terrorist Town - Decoy Body" (3.2143) by TTT-Contributors
41 "Trouble in Terrorist Town - Hurtshot" (3.2143) by TTT-Contributors
42 "Trouble in Terrorist Town - Teleporter" (3.2143) by TTT-Contributors
43 "Trouble in Terrorist Town - Items: Fake Body" (3.2143) by TTT-Contributors
44 "Trouble in Terrorist Town - Hud" (3.2143) by TTT-Contributors
45 "Trouble in Terrorist Town - Health/Hurt Stations" (3.2143) by TTT-Contributors
46 "Trouble in Terrorist Town - Traitor Buttons" (3.2143) by TTT-Contributors
47 "Trouble in Terrorist Town - Items: Healthshot" (3.2143) by TTT-Contributors
48 "Trouble in Terrorist Town - Tripmines" (3.2143) by TTT-Contributors
49 "Trouble in Terrorist Town - Drop Weapons" (3.2143) by TTT-Contributors
50 "Trouble in Terrorist Town - Icons" (3.2143) by TTT-Contributors
51 "Trouble in Terrorist Town - Items: Wallhack" (3.2143) by TTT-Contributors
52 "Trouble in Terrorist Town - Items: Martydom" (3.2143) by TTT-Contributors
53 "Trouble in Terrorist Town - C4 & Jihad" (3.2143) by TTT-Contributors
54 "Trouble in Terrorist Town - Radar" (3.2143) by TTT-Contributors
55 "Trouble in Terrorist Town - Items: Random Teleporter" (3.2143) by TTT-Contributors
56 "Trouble in Terrorist Town - Models" (3.2143) by TTT-Contributors
57 "Trouble in Terrorist Town - Shop" (3.2143) by TTT-Contributors
58 "Trouble in Terrorist Town - Exojump" (3.2143) by TTT-Contributors
59 "Trouble in Terrorist Town - Items: Taser" (3.2143) by TTT-Contributors
60 "Trouble in Terrorist Town - Bullets (Fire, Freeze, Poison)" (3.2143) by TTT-Contributors
61 "Trouble in Terrorist Town - Radio" (3.2143) by TTT-Contributors
62 "Trouble in Terrorist Town - Items: Missiles" (good_live) by TTT-Contributors
63 "Trouble in Terrorist Town - Talk Override" (3.2143) by TTT-Contributors
64 "CS:GO Turret Core" (1.0) by Tast - SDC Edited by Kento & e54385991
65 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
66 "hextags" (1.47) by Hexah
67 "sbp.smx"
68 "SM Valve Gloves" (3.0.2) by Franc1sco franug
69 "ServerAdvertisements3" (3.1.3) by ESK0
70 "Fun Votes" (1.10.0.6453) by AlliedModders LLC
71 "Reserved Slots" (1.10.0.6453) by AlliedModders LLC
72 "Admin File Reader" (1.10.0.6453) by AlliedModders LLC
73 "Useful commands" (4.3) by Eyal282
74 "No Weapon Fix" (3.2) by .#Zipcore
75 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
76 "Basic Comm Control" (1.10.0.6453) by AlliedModders LLC
77 "Player Commands" (1.10.0.6453) by AlliedModders LLC
78 "[CSGO] Zaawansowany system VIP na serwery CSGO" (1.5) by Mesharsky
79 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
80 "Chat-Processor" (2.2.1) by Drixevel
81 "VoiceAnnounceEx" (2.2.0) by Franc1sco franug, Mini and GoD-Tony
82 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
83 "Anti-Flood" (1.10.0.6453) by AlliedModders LLC
84 "Fun Commands" (1.10.0.6453) by AlliedModders LLC
85 "Nextmap" (1.10.0.6453) by AlliedModders LLC
86 "Sound Commands" (1.10.0.6453) by AlliedModders LLC
87 "Basic Votes" (1.10.0.6453) by AlliedModders LLC
88 "Weapons & Knives" (1.4.2) by kgns | oyunhost.net
89 "Basic Chat" (1.10.0.6453) by AlliedModders LLC
90 "Client Preferences" (1.10.0.6453) by AlliedModders LLC
91 "[Roberrt] Automatyczny Sklep Usług [#GSHOP]" (1.0.4) by Roberrt..
92 "Tripmines 2016 Update" (1.0 ( will be never updated :) )) by 404, Bara
93 "SM Speaker Icon" (2.1) by Franc1sco steam: franug
94 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
95 "Admin Menu" (1.10.0.6453) by AlliedModders LLC
96 "[CS:GO] VIP Info" (1.0) by Yamakashi
97 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
[NET] Cannot send 5319-byte packet to 80.87.193.51:51223. MTU is 1200. ff ff ff ff 45
[NET] Cannot send 5319-byte packet to 85.194.244.53:57139. MTU is 1200. ff ff ff ff 45

- TTT related error logs - You can find the logs under: addons/sourcemod/logs/error_*.log
no logs

- Steps to reproduce this issue
if someone use taser on someone this happens:
![ttt_closequarters0004](https://user-images.githubusercontent.com/24883069/68065859-6b7aa200-fd2f-11e9-9ac6-2ed9968890ef.png)

**Comment by Tashboss** [comment]
Yes I have seen this ghost many times as well. When I am  a T and sometimes I can see one one of my T buddies red outline just in one spot and it won't disappear.
