### ISSUE TITLE
Player can talk with alive after suicide

### ISSUE THREAD

**Issue by Raku17** [Bara/TroubleinTerroristTown#447]
SourceMod Version: 1.10.0.6453
TTT Version: 3.2137

like in title, player who suicide can talk with alive, player who is killed by someone can't talk with alive

**Comment by Mrkl21full** [comment]
Okey according to ttt core you shouldn't have "give" players opportunity to kill themselfs with commands like "kill" or "explode".

But if this is not the case I will explain to you in "another" way.

In ttt core in line (at the moment) 2943 there is "if (!TTT_IsClientValid(iAttacker) || iAttacker == client)" so players who commited suicide are not passed to ttt_talk_override plugin.

I suggest to you to change "TTT_OnClientDeath" to player death event in the ttt_talk_override. It should do the job.

**Comment by Bara** [comment]
@Mrkl21full feel free to change it with a pull request 👍
