### ISSUE TITLE
Player slayed with rslays can talk to living

### ISSUE THREAD

**Issue by PRAWKC** [Bara/TroubleinTerroristTown#449]
SourceMod Version: 1.9.0.6282
TTT Version: 3.2148

Players who are given rslays can be heard by living players. I think the issue is similar to #447 

How to reproduce?:
1. You will need a friend or another PC.
2. Add 1 extra bot.
3. /rslays YourName 1
4. Wait for the round to begin.
5. Speak while dead. Living players can hear you.

**Comment by Bara** [comment]
I'll close this issue with the Merge, if it still happens feel free to reopen this issue.

**Comment by Prefix** [comment]
Bug is still not fixed. Reproduce same as PRAWKC mentioned. I'm using latest build.
