### ISSUE TITLE
Players who have rslays get assigned roles

### ISSUE THREAD

**Issue by PRAWKC** [Bara/TroubleinTerroristTown#450]
SourceMod Version: 1.9.0.6282
TTT Version: 3.2148

Players who have rslays are getting assigned roles before being slayed.

**Comment by jnatalejr** [comment]
I can see where this could be considered a bug or issue. If a T is slain his team is now down a player for no fault of their own.

I'll add a cvar to disable relay people from becoming a traitor, have it enabled by default. Sometime this weekend.

**Comment by Bara** [comment]
I'll close this issue with the Merge, if it still happens feel free to reopen this issue.
