### ISSUE TITLE
2020 - The Revive of TTT(?)

### ISSUE THREAD

**Issue by Bara** [Bara/TroubleinTerroristTown#455]
At first, Happy New Year!

Maybe some of you have noticed, that I've removed my issue regarding my cancelled development for new features.

Yes I've tried but I simply can't, it's too big to discontinue. I'm possibly looking into merging the private version (yes there is a private version that exists for 3 communities at the moment). The current private version has a lot of Quality of Life changes, new features, items and more. 

**Why do I want to merge?** 
The way I see it working, is I will keep the private version going but it'll be more so for a select few communities to test out the brand new features so it will be a beta. This way that all the big changes will come out for the private version before I release it on the public repository. 

**Can I join the beta?**
Sure, contact me (I prefer Discord as requirement for the beta) with [some] details about your community (please only contact me if you've an active player base, otherwise there'll no point in you testing) and we shall discuss further.

**Comment by rautamiekka** [comment]
Oh great.

**Comment by JoanJuan10** [comment]
I have been waiting a lot for this. Looking forward to it. Thanks for reviving it :)

**Comment by rautamiekka** [comment]
> I have been waiting a lot for this. Looking forward to it. Thanks for reviving it :)

Making it private ain't exactly a good thing.

**Comment by Bara** [comment]
> Making it private ain't exactly a good thing.

I had and have some reasons. As example the behavior of some communities, which is a factor that bothers me the most.

**Comment by jnatalejr** [comment]
I've encouraged a merge since gaining access to the private branch.

Let's so it.

**Comment by Bara** [comment]
Small update:


We're nearly done and just need some time to test all the new features, changes and bug fixes.

**Comment by Bara** [comment]
Preview of new chat colors:
https://steamcommunity.com/sharedfiles/filedetails/?id=1987078621

We also overhauled some phrases to fix some grammars and shortened some messages to reduce the amount chat spam with 2 liners. Preview: https://steamcommunity.com/sharedfiles/filedetails/?id=1987227954

**Important note**: Since we can't update all languages phrases, we decided to remove all languages except english and start from scratch. Another reason is that we updated exist phrases, so can't garantuee the correct translation anymore.

**Comment by Bara** [comment]
Here's a __preview__ of the changelogs: https://i.imgur.com/BLRHyER.png

As I already wrote on Discord, I don't add more details. If you want to know more, ask your question here and all questions (if it worth) will land on a wiki page here on github as FAQ. __BUT__ before your ask a question make sure it isn't already descripted in a config file/api site.
