### ISSUE TITLE
Accents for translation

### ISSUE THREAD

**Issue by Niilyx** [Bara/TroubleinTerroristTown#469]
Hi, I tried to translate TTT in French, but it seems the font TTT uses doesn't have any. I wanted to submit that translation so that the gamemode would include it everywhere, and it would be inconvenient for French players to have questions marks everywhere.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mrkl21full** [comment]
I do not understand the first sentence.

But... if you want to translate it in your own language, fork repo and make changes in translation file and then create pull request with that file from your forket repo.

**Comment by Niilyx** [comment]
>I do not understand the first sentence. ...

@Mrkl21full In the first sentence I said that I tried to translate TTT in French (which uses character as é, è, à etc...) and some character seem to bug (that <?> character)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mrkl21full** [comment]
Sorry for late response, but...

Are you sure you are doing it right? Encoding must be utf-8 for those things. 

I just tested all french letters I could find and those are results

![French chars](https://user-images.githubusercontent.com/29057579/80321157-39985300-881b-11ea-901b-ed2a447321a1.png)

**Comment by Niilyx** [comment]
>Sorry for late response, but... ...

@Mrkl21full I think I did it right? Plus this screen contains characters of another font, not the default TTT font. What I have done is I copied the english.lua file, renamed french.lua, and changed the texts as well as the name of the language. I will check if the problem is the encoding.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mrkl21full** [comment]
Do we even talking about the same gamemode for the same game? 

This is a repo for TTT gamemode for csgo servers.

Lua is used in gmod.

**Comment by Bara** [comment]
What @Mrkl21full said. This repository is for TTT in CSGO and not for GMod.

**Comment by Niilyx** [comment]
>What @Mrkl21full said. This repository is for TTT in CSGO and not for GMod.

@Bara aight, my mistake. I was indeed talking about gmod, isn't there any support for it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
