### ISSUE TITLE
Kill Replays

### ISSUE THREAD

**Issue by beavr27** [Bara/TroubleinTerroristTown#471]
Hello, 
I was wondering if it would be possible to add a short kill replay after you die.
This would be very useful for regular players to see if they were rdmed and save a lot of time and hassle for admins.
I have no idea about coding and the limits of this, but I was thinking something like this would be good: https://www.youtube.com/watch?v=NrMANyKWOaE

Thanks, Beavr

**Comment by sneak-it** [comment]
You can get this functionality with base CS:GO using GOTV and `"spec_replay_enable" = "1" `

**Comment by beavr27** [comment]
Thanks, didn't realise it would be that easy
