### ISSUE TITLE
Fake nickname / invisible nickname

### ISSUE THREAD

**Issue by kikoplg** [Bara/TroubleinTerroristTown#6]
New items TTT shop for TRAITORS:
 fake nickname (~15 sec)
 invisible nickname (~15 sec)
Need mp_playerid 2 and small code Show nickname on HUD :)

**Comment by good-live** [comment]
Okay how long do you need? :D

**Comment by good-live** [comment]
Should be easy to do with the latest commit to the playerhud. I'm goign to take a look at it when i have some time.
One question: Does invisible nickname mean there shouldnt be a hint displayed or just remove the name from the hint?

**Comment by Bara20** [comment]
@good-live ?

**Comment by good-live** [comment]
Haven't looked into it yet. Proparly the whole hud needs a rewrite as i guess it's pretty much unperformant.

**Comment by Bara** [comment]
Invisible name = No PlayerHUD? @good-live what do you think?

**Comment by good-live** [comment]
Y
